import type {Guide} from '../ui/RuleGuide';
const guide=(edition:string,quick:string[],sections:[string,...string[]][]):Guide=>({edition,quick,sections:sections.map(([title,...text])=>({title,text}))});
export const classicGuides={
 doudizhu:{zh:guide('斗地主 · 3 人 · 54 张牌 · 经典叫分桌规',[
 '每人 17 张，三张底牌留给地主。依次叫分，最高分者成为地主。','地主先出；另外两人合作。点选手牌后确认出牌，也可用提示选牌。','跟牌须同牌型同张数且更大，炸弹和王炸可以跨牌型压制。','连续两家不出，由最后出牌者重新领出。','地主先出完则地主胜；任一农民先出完则两位农民共同获胜。'],[
 ['发牌与叫分','单副牌含大小王。依次不叫或叫 1、2、3 分，必须高于已叫分；叫 3 分立即定地主。三人都不叫则重新发牌并轮换起叫者。地主获得三张公开底牌。'],
 ['牌型','单张、对子、三张、三带一、三带一对；顺子至少五张、连对至少三对、飞机至少连续两个三张。顺子、连对和飞机主体不含 2 与王。飞机可带等组数的单牌或互异对子；单翼允许成对，不能从主体拆第四张，也不能同时带大小王。','四带二可带两张单牌或一对，但不能同时带大小王；四带两对必须是两个不同点数的对子。四带牌不是炸弹。'],
 ['大小与回合','3 最小，依次到 A、2、小王、大王。普通牌按主体点数比较，并要求同牌型同张数；四张同点为炸弹，大小王合出为王炸。新一轮领出不能不出。提示提供一种合法出法，不代表最优策略。'],
 ['计分与春天','底分为地主叫分，每个炸弹或王炸翻倍。地主获胜且农民从未出牌为春天；农民获胜且地主只出过一手为反春天，均再翻倍。地主输赢为底分×倍数×2，每位农民为底分×倍数，积分零和。','本项目无金币、现金、加倍竞叫或癞子扩展；一轮结束即结算。']]),
 en:guide('Dou Dizhu · 3 players · 54 cards · Classic bidding',[
 'Deal 17 cards each and reserve three for the landlord. The highest bidder becomes landlord.','The landlord leads; the other two players cooperate. Select cards, then confirm. Hint selects a legal play.','Match the previous type and card count with a higher rank, or use a bomb or rocket.','Two passes clear the trick. Its winner leads again.','The landlord wins by emptying their hand first; either farmer finishing wins for both farmers.'],[
 ['Deal and bidding','Bid 1, 2 or 3 above the current bid, or pass. Three immediately ends bidding. If everyone passes, redeal and rotate the opening bidder. The landlord takes the three publicly revealed bottom cards.'],
 ['Combinations','Singles, pairs, triples, triple with a single or pair; runs of at least five singles, three pairs or two triples. Runs exclude 2 and jokers. Airplanes may carry one single or one distinct pair per triple. Single wings may form pairs, but cannot include a fourth card of a body rank or both jokers.','Four with two singles (possibly a pair) cannot carry both jokers. Four with two pairs requires distinct pair ranks. Neither is a bomb.'],
 ['Comparison and turns','Ranks ascend 3 through A, 2, small joker, big joker. Ordinary plays require matching type and length. Four equal cards form a bomb; both jokers form the highest rocket. A fresh lead cannot pass. Hints provide a legal option, not an optimal strategy.'],
 ['Scoring','The winning bid is the base. Each bomb or rocket doubles it. A landlord win before either farmer plays, or a farmer win after only one landlord play, doubles it again. The landlord gains or loses twice the final base; each farmer receives the opposite single amount. Scores sum to zero.','One deal per game. No money, bonus bidding or wildcard expansion.']])},
 guandan:{zh:guide('掼蛋 · 4 人 · 双副牌 · Mocha 3/2/1 升级桌规',[
 '两副牌共 108 张，每人 27 张；座位 1 与 3、2 与 4 为对家。','从打 2 开始；红桃级牌是逢人配，可代替非王牌。','点选手牌并确认，提示会选出一种可出的牌。','争取你和对家尽早出完，头游一方依对家名次升 3、2 或 1 级。','每轮结算后继续；先成功打过 A 的队伍赢得比赛。'],[
 ['级牌与牌型','点数为大王、小王、级牌、A 到 2（级牌按级牌大小）。单张逢人配仍是级牌；组合中可代任意非王牌。','支持单、对、三张、三带一对、恰五张顺子、恰三连对、恰两组三张的钢板、四张及以上炸弹、五张同花顺、四王。级牌在顺子中按原数字。A 可作最低 1 或最高 A，不能 K-A-2 环绕。'],
 ['压制与接风','普通牌必须同型同张数。四王最大；六张及以上炸弹高于同花顺，同花顺高于四炸与五炸；炸弹先比张数再比点数。逢人配最多两张，最高可组成十张炸弹。','玩家出完后，其余人仍可压最后一手；若都不压，由尚有牌的对家接风，否则由下一位有牌者领出。提示只使用本人的手牌。选牌有多种合法解释时，可用牌型下拉框明确宣告；默认选择可压过上一手的最强组合。'],
 ['升级与过 A','头游与对家同为前两名时升 3 级；对家第三升 2 级；对家末位升 1 级。两队各自保留等级，下轮使用上一轮赢家的等级。等级最多到 A，必须实际打一轮 A 并由本队拿头游、对家不为末位，才获胜。','一方双上即结算，未出完的两人按座位顺序记录末两名，双贡的分配仍按贡牌大小决定。积分栏显示本轮赢方升级数，不是货币。'],
 ['进贡、还贡、抗贡','下一轮末游向头游进贡；双下时两名输家分别进贡。系统选取除红桃级牌外最大的牌，大贡给头游，小贡给二游；同大按从头游顺时针的座次。','受贡者自己选一张非级牌且不大于 10 的牌还贡；没有此类牌时可还任意牌。贡牌与还贡牌公开。大贡者先出，同大也按上述座次；单贡由进贡者先出。','单贡者持两张大王，或双贡者合持两张大王，则抗贡，由上轮头游先出。不采用打 A 三次失败降级等地区扩展。']]),
 en:guide('Guan Dan · 4 players · Two decks · Mocha 3/2/1 progression',[
 'Deal 27 cards each from two complete decks. Opposite seats form teams.','Start at level 2. Hearts of the current level are wild, except for jokers.','Select cards and confirm; Hint selects one legal option.','The first finisher’s team advances 3, 2 or 1 levels according to their partner’s place.','Continue between deals. Win a level-A deal with your partner not last to win the match.'],[
 ['Ranks and combinations','Big joker, small joker, level rank, then A down to 2. A single heart-level card keeps its level rank; in combinations it may stand for any non-joker.','Singles, pairs, triples, triple with pair, exactly five-card straights, three consecutive pairs, two consecutive triples, bombs of four or more, straight flushes and four jokers. Runs use natural ranks, with A low or high but no K-A-2 wrapping.'],
 ['Comparison and partner lead','Match ordinary type and length. Four jokers are highest; bombs of six or more beat straight flushes, which beat four- and five-card bombs. Bombs compare length before rank. Two wildcards can extend a bomb to ten cards.','After someone empties their hand, opponents may still beat the last play. If everyone passes, the finisher’s partner leads when still holding cards; otherwise the next remaining seat leads. Hints use only your own hand. When selected cards have multiple legal interpretations, choose one in the combination selector; the strongest legal interpretation is the default.'],
 ['Progression','First and second together advance three; first and third advance two; first and last advance one. Teams retain separate levels; the previous winner’s level is used next. Progress caps at A. Actually win at A, with the partner not last, to finish the match.','A team taking the first two places ends the deal; the other seats receive the remaining places in seat order. Tribute is still ordered by gift strength. Displayed points are the winning team’s level gain for that deal.'],
 ['Tribute and return','The last player gives their highest non-heart-level card to the first. When a team takes both top places, both losers give tribute: higher gift to first, lower to second. Equal gifts use clockwise distance from first place.','Recipients choose a non-level card of rank 10 or lower to return; if none exists, any card may be returned. Gifts and returns are public. The higher giver leads, using the same seat tie-break. A single giver leads after single tribute.','Two big jokers held by the single giver, or jointly by both givers, cancel tribute; the previous first finisher leads. No regional three-failed-A demotion rule.']])},
 mahjong:{zh:guide('麻将 · 4 人 · 广麻 / 四川血战 / 血流 / 红中赖子 · Mocha 聚会桌规',[
 '创建房间时选择玩法；四人按东南西北就座，东家先出。','四川与血流先选同花色三张换给下家，再各自定缺一门。','点选手牌抬起，再点同一张牌打出；点桌面或按 Esc 取消。新摸牌放在最右侧，碰、杠、胡在手牌右上方。','无碰、杠、胡机会时自动过；有机会时手动选择响应或过。胡牌优先，可一炮多响。','广东与赖子一轮胡牌即结算；血战胡者离场，血流胡后继续，牌墙空时结算。'],[
 ['四种玩法','广东推倒胡：136 张，万筒条与字牌，无花；不吃牌，可碰、明杠、暗杠、补杠、点炮胡或自摸。','四川血战：108 张序数牌，顺时针换三张与定缺，缺门牌必须优先打完，缺门未清不能胡或碰杠。胡牌后离场，三家胡牌或牌墙空时结束。','血流成河：同样换三张与定缺；胡后仍在局，可多次胡。第一次胡牌后锁定手牌，不再碰杠，仅打出新摸牌；不能原地重复自摸，之后仍可多次自摸或点炮胡。点炮胡不把他人的弃牌加入手牌。','红中赖子：136 张，红中是万能牌，可补顺子、刻子或将；红中不能碰杠，也不能胡别人打出的红中。其余与广东模式相同。'],
 ['成牌与响应','胡牌为四组顺子/刻子加一对将；每个副露算一组。无副露时支持七对，四张相同可算两对；无赖子的闭门牌另支持十三幺。','碰杠不能吃牌。弃牌后无合法胡、碰、杠的座位自动过，其余玩家手动响应，决定对他人不可见；胡高于碰杠，多个胡全部结算；无人胡时碰杠按距出牌者顺时针最近者优先。','补杠先开抢杠胡窗口；被抢时原碰保留，第四张归入弃牌。暗杠不被抢，其他玩家看不到其牌面。没有补牌可摸时不能杠。'],
 ['听牌提示','可听牌的弃牌标有“听”；选中后，手牌上方直接显示可胡的牌。已经听牌时自动显示，点击“听”可查看大图与预估倍数。'],
 ['Mocha 计分','基础 1 分，七对 ×2、清一色 ×4、碰碰胡 ×2 可叠加，基础封顶 16。碰碰胡按手牌点数分组判断，不另算龙七对、根、买马或地区复杂番型。','自摸 ×2，杠后自摸/杠后点炮/抢杠 ×2，最终单家封顶 32。点炮者向每位胡者付分；自摸由其他仍在局者各付分。','直杠由放杠者付 2；暗杠其他在局者各付 2；补杠各付 1。抢杠成功不收补杠分。所有转账零和，只记录游戏积分。'],
 ['流局与胜负','四川与血流流局时：未清缺门者向每位已清缺门的在局者付 16（查花猪）；清缺但未听者向每位听牌者支付其最高基础胡分（查大叫）；未听者退还收到的所有杠分。已胡离场的血战玩家不参与查叫与花猪。','最终正积分最高者为胜者，同分共享；全桌 0 分为和局。广东与赖子流局保留已结杠分，不查叫。没有自动倒计时或离线代打。'],
 ['版本范围','暂不包含吃牌、花牌、买马、海底特殊番、过手胡限制或复杂地方番型。开始前请四位玩家共同阅读本页；每次结算后可重新开桌选择另一模式。']]),
 en:guide('Mahjong · 4 players · Guangdong / Sichuan / Blood Flow / Red Dragon Wild · Mocha house rules',[
 'Choose a variant before creating the room. Seats are East, South, West and North; East leads.','Sichuan and Blood Flow exchange three same-suit tiles clockwise, then each player chooses a missing suit.','Tap a tile to raise it; tap it again to discard. Tap the table or press Escape to cancel. Drawn tiles sit on the right; legal claims appear above the hand.','Passes are automatic when no pung, kong or win is possible; otherwise choose a response or pass. Wins take priority, including multiple winners.','Guangdong and Wild end after wins; Sichuan winners leave, while Blood Flow continues until the wall is empty.'],[
 ['Variants','Guangdong Push Down: 136 tiles including honors, without flowers. No chow. Pung, exposed/concealed/added kong, discard wins and self-draw are supported.','Sichuan Blood Battle: 108 suited tiles, clockwise three-tile exchange and missing-suit selection. Discard the missing suit first; clear it before winning or claiming a meld. Winners leave; end after three winners or an empty wall.','Blood Flow: same opening, but players remain after winning and may win repeatedly. After the first win, lock the hand: no more meld claims; discard only the newly drawn tile. A self-draw cannot be repeated without a new draw. Later self-draws and discard wins remain possible. Discard wins do not add that tile to the winner’s hand.','Red Dragon Wild: 136 tiles; red dragons can fill sets or the pair. They cannot be punged, konged, or claimed as a discarded winning tile. Otherwise uses Guangdong rules.'],
 ['Winning hands and responses','Four sets and a pair, counting each meld as one set. Closed seven pairs allow quads as two pairs. Closed thirteen orphans are supported without wildcards.','No chow. Seats without a legal pung, kong or win pass automatically; other opponents choose their private response. All wins resolve first; if nobody wins, the closest clockwise pung/kong claimant has priority.','Added kongs open a robbing window. If robbed, keep the old pung and discard the fourth tile. Concealed kongs cannot be robbed and hide their face values from others. A kong requires a replacement tile in the wall.'],
 ['Winning waits','Tiles marked Ready leave a winning wait when discarded. Select one to see its winning tiles above your hand. Existing waits appear automatically; select Ready for larger tiles and estimated multipliers.'],
 ['Mocha scoring','Base one; seven pairs ×2, pure single suit ×4, all triplets ×2, stacking up to a base of 16. All-triplet scoring uses rank counts. No luxury pairs, roots, horses or complex regional fan tables.','Self-draw ×2; win after kong, discard after kong or robbing kong ×2; final payment caps at 32 per payer. The discarder pays every winner, or all remaining opponents pay on self-draw.','Exposed kong costs its discarder two. Concealed kong costs each remaining opponent two; added kong costs each one. Robbed added kongs earn nothing. All transfers are zero-sum game points.'],
 ['Wall exhaustion and results','Sichuan/Blood Flow: each player retaining the missing suit pays 16 to every cleared, remaining player. Cleared non-ready players pay each ready player their highest base winning value. Non-ready players return all kong income. Departed Sichuan winners do not enter readiness or missing-suit penalties.','Highest positive final score wins, with shared ties. All-zero scores draw. Guangdong/Wild retain kong scores at wall exhaustion without readiness penalties. No timers or offline autoplay.'],
 ['Scope','No chow, flowers, horses, special last-tile bonuses, passed-win restrictions or complex regional scoring. Read these rules together before starting. After settlement, open another game to choose a different variant.']])}
};
