import {sushiGuides} from './sushiGuides';
import {classicGuides} from './classicGuides';
import type {GameKind} from '../core/types';
import type {Guide} from '../ui/RuleGuide';
const guide=(edition:string,quick:string[],sections:[string,...string[]][]):Guide=>({edition,quick,sections:sections.map(([title,...text])=>({title,text}))});
export const guides:Record<GameKind,{zh:Guide;en:Guide}>={...classicGuides,
drawrelay:{zh:guide('你画我猜（接龙版） · Draw & Guess 传话玩法 · 3–12 人。',[
'每人开一本画册，写一句开场句。','按座位传递，文字与绘画交替；只看当前任务紧邻的前一页。','默认待办队列：各本画册独立推进，回来后可处理积累的画图或猜图任务。','每人参与每本画册一次，全部完成后一起看画册。'],[
['待办队列','任务不限时。提交一本画册后立即传给下一位，不必等待其他画册；同一人可同时有多项待办，并选择处理顺序。切换任务前等待文字草稿保存。','其他玩家离线不会阻止你处理已有任务；轮到离线玩家的那本画册会等待。局域网仍需要房主在线。'],
['同步轮次','开局也可选择同步轮次，所有人交完本步后统一传递。可设不限时或每步 60、90、120 秒；超时保存已同步草稿，空白页记为未完成。断线暂停计时，重连继续。'],
['画板与隐私','画笔工具提供颜色、五档粗细与橡皮擦；支持撤销和确认清空。每页最多 96 笔，每笔最多 48 点；文字最多 120 字。提交后不能修改。','完成前只发送当前任务的前一页及自己的草稿，任务列表不含其他页内容。换座需重新打开接龙页；所有画册完成后揭晓。局域网房主和同屏设备持有完整牌局。'],
['范围','采用 Draw & Guess 的文字、画图交替传话方式，另提供独立待办队列。不包含其竞分、投票、动画或外部画库模式。']]),en:guide('Drawing Relay · Draw & Guess telephone format · 3–12 players.',[
'Each player starts an album with a sentence.','Pass albums in seat order, alternating drawing and text. See only the immediately preceding page.','Task queue is the default: albums advance independently and pending drawings or guesses can accumulate.','Everyone contributes once to every album. Reveal when all albums are complete.'],[
['Task queue','Tasks have no timer. Submit one album to pass it immediately without waiting for other albums. Choose the order of multiple pending tasks. Wait for text drafts to save before switching.','Other players going offline does not block your available tasks. An album waits when it reaches an offline player. LAN rooms still need the host online.'],
['Synchronous rounds','Optionally advance all albums together after everyone submits. Choose unlimited time or 60, 90 or 120 seconds per step. Deadlines save synchronized drafts and mark empty pages incomplete. Disconnects pause the timer until reconnection.'],
['Canvas and privacy','Drawing tools offer colors, five widths and an eraser, plus undo and confirmed clearing. Each page allows 96 strokes of up to 48 points, or 120 text characters. Submission is final.','Before the reveal, only the active task’s previous page and your draft are sent to you. Task lists contain no page contents. Reopen your page after switching seats. All albums must finish before reveal. LAN hosts and shared devices hold the full match.'],
['Scope','Uses the alternating text-and-drawing telephone format from Draw & Guess, with an additional independent task queue. Scoring, voting, animation and external image-library modes are not included.']])},
gems:{zh:guide('晶石商会 · 2–4 人 · 基础 90 张发展牌与 10 张贵族，15 分触发末轮。',[
'先看市场中便宜的一级牌，决定要收集哪些颜色。','轮到你时，取三种不同颜色的晶石各一枚；或连点同一种颜色取两枚，但该颜色拿取前须至少有四枚。点“拿取”确认；有库存的颜色不足三种时，取所有可用颜色各一枚。','点市场卡片查看费用；买下后获得牌面颜色的永久折扣，之后买牌时少付一枚该色晶石。','想先留住一张牌就预留，通常还会得到一枚万能黄金。','有人达到 15 分后完成这一轮；分数最高者获胜。'],[
['准备与目标','每人从零开始。五种普通晶石在 2/3/4 人时各有 4/5/7 枚，黄金固定 5 枚。三个等级各公开 4 张发展牌，贵族数量为玩家数加一。发展牌与贵族的分数计入总分。'],
['一回合四选一','取三种不同颜色各一枚；若不足三种有库存，拿取可用的不同颜色。或取同色两枚，但拿取前该颜色必须至少有四枚。黄金不能直接拿。','也可购买一张公开牌或自己的预留牌；另一种行动是预留公开牌，或某一等级牌堆顶部的盲牌。'],
['购买与永久折扣','费用先减去已购买牌提供的同色折扣，再支付普通晶石；黄金可代替任意缺少的颜色。确认支付后晶石回到供应区，发展牌永久留在你的商会。零费用牌仍消耗本回合行动。市场空位即时补牌。'],
['预留与信息','最多持有三张预留牌。预留时若还有黄金，获得一枚；没有黄金仍可预留。预留不是购买，不能直接提供折扣或分数。','公开市场预留对其他玩家保持可见，盲抽牌只给自己看。点击玩家库存可查看其公开晶石、折扣、已购牌和公开预留。'],
['容量与贵族','行动后晶石与黄金总数不得超过十枚，超出时选择归还。满足贵族所需的永久折扣即可获得贵族，不支付晶石；同回合最多获得一位，有多位符合条件时自行选择。每位贵族三分。'],
['结束与平分','有人达到十五分时继续到起始玩家前一位完成回合，确保行动次数相同。总分最高者胜，同分时已购买的发展牌更少者胜；仍相同则并列。']]),
en:guide('Crystal Guild · 2–4 players · 90 development cards, 10 patrons, final round at 15 points.',[
'Look for an inexpensive level-one card and collect its colors.','Take one token from each of three different colors, or tap one color twice to take two if at least four are in its supply. Confirm with Take. Only take fewer distinct colors when fewer than three remain available.','Buy a card to gain a permanent discount on future purchases.','Reserve a useful card to keep it for later and usually collect a wild gold token.','Finish the round after someone reaches 15 points. Highest score wins.'],[
['Setup and goal','Each ordinary color has 4/5/7 tokens with 2/3/4 players; gold always has five. Reveal four cards per level and one more patron than the player count. Your cards and patrons provide points.'],['Choose one action','Take one token from three different available colors, taking fewer only when fewer colors remain. Alternatively take two of one color, provided at least four were available before taking. Gold cannot be taken directly.','Instead, buy a visible or personally reserved card, or reserve a visible card or the top card from a level’s deck.'],['Buying and discounts','Subtract permanent card bonuses from each color’s cost. Pay the remainder with matching tokens or gold. Payment returns to the supply. The purchased card stays with you and a market vacancy is refilled. A free purchase still uses your action.'],['Reservations and information','Hold at most three reserved cards. Receive one gold if available when reserving; reserving is still allowed without gold. Reserved cards provide no points or discounts until bought. Public reservations remain public; blind reservations are private. Player inventories show public resources and cards.'],['Limit and patrons','After an action, return tokens until you hold at most ten, including gold. A patron visits when permanent bonuses meet every requirement, without spending tokens. Gain at most one patron per turn; choose if several qualify. Each is worth three points.'],['End and ties','Reaching fifteen triggers the final round, ending after the player immediately before the starting player. Highest points wins. Ties go to fewer purchased development cards; a remaining tie is shared.']])},
bombs:{zh:guide('喵喵危机 · 2–5 人 · 2025 基础规则，含对子和三张组合；所有存活玩家确认后结算。',[
'每人八张起手牌，其中一张“拆弹”。你的目标是成为最后一位留桌玩家。','轮到你可先出任意数量的可用功能牌；选中手牌后点出牌确认，重复点牌可取消选择。不想出就抽一张结束回合。','抽到“爆炸牌”要用拆弹，然后秘密放回；没有拆弹就出局。','其他人出牌时，可直接打出“否决”或点继续；自己刚出牌无需再确认。','用“预知三张”观察危险，用“跳过”或“攻击”躲开抽牌。'],[
['起手与回合','每人七张普通牌加一张拆弹，牌堆混入玩家数减一张爆炸牌。额外放入两张拆弹；五人局只有一张。攻击、跳过、索取、洗牌各四张；预知三张和否决各五张；五种猫咪各四张。回合中可以不出牌或连续出牌，最后抽一张普通牌结束一个回合。若承担多回合，需分别完成。'],['爆炸牌与拆弹','没有拆弹时立即出局，手牌不再参与游戏。有拆弹时可使用并弃掉，也可以放弃救援。之后秘密选择爆炸牌放回位置，最上面代表下一次会抽到，最底下代表最后抽到；拆弹不允许被否决阻止。'],['功能牌','跳过：不抽牌结束一个回合。攻击：把回合交给下一位，普通状态使其做两个回合；已受攻击影响时，剩余回合再加二。','索取：目标选择交出一张手牌。洗牌：重新打乱抽牌堆。预知三张：只给使用者看顶上三张，顺序不会改变。'],['否决与响应窗口','功能牌或同名组合打出后，其他存活玩家可直接打出否决，或点继续。出牌者已经确认，无需再点。每张否决都会切换效果是否生效；打出否决者已经确认，其余存活玩家重新响应。所有人响应后结算，已出局者不参与。窗口结束前仍可打出否决，包括反制否决；想否决自己刚出的牌，可从手牌选中否决。','否决不能取消抽牌、抽到爆炸牌或拆弹。'],['同名组合','任意两张同名牌可以从目标随机取得一张手牌；三张同名牌可以指定一个牌名，目标有则获得一张，没有则落空。普通猫咪牌主要用于组合，拆弹等牌也可组成同名组合。此版本没有旧版的五张不同牌回收弃牌组合，也不启用快速删牌变体。'],['结束与隐私','只剩一名玩家时立刻获胜。自己的手牌、偷瞄内容和放回位置只向本人显示；其他人只看到手牌数量。点弃牌堆可查看最近 12 张公开弃牌，最新在前。不要在多人秘密游戏中使用共享屏幕座位切换。']]),
en:guide('Kitten Chaos · 2–5 players · 2025 base rules, including pairs and triples. Effects resolve after every survivor confirms.',[
'Start with eight cards, including one Defuse card. Be the last player remaining.','Play any number of usable cards on your turn. Select cards, then confirm with Play; tap a selected card again to deselect it. Draw to end one turn.','A Bomb card eliminates you unless you Defuse it and secretly put it back.','When someone else plays, use Play Nope or Continue. Your own play needs no extra confirmation.','Peek 3, Skip and Attack help you avoid a dangerous draw.'],[
['Setup and turns','Each player receives seven ordinary cards and one Defuse card. The deck contains one fewer Bomb card than players, plus two extra Defuses (one with five players). Attack, Skip, Favor and Shuffle have four copies each; Peek 3 and Nope have five; each of the five cat types has four. Play zero or more cards, then draw an ordinary card to finish one turn. If you owe several turns, complete them separately.'],['Bomb and Defuse','Without Defuse, drawing Bomb eliminates you. With Defuse, discard it or choose to give up. Secretly choose where Bomb returns: the top is the next draw and the bottom the last. Defuse cannot be cancelled by Nope.'],['Card effects','Skip ends one turn without drawing. Attack passes play to the next player, assigning two turns normally, or adding two to the remaining turns when already under Attack.','Favor lets the target choose a card to hand over. Shuffle randomizes the draw pile. Peek 3 shows only you its top three cards without rearranging them.'],['Responses','After an effect or matching combination, other surviving players choose Play Nope or Continue. The player who just played has already acknowledged. Each Nope toggles whether the effect resolves; its player has acknowledged, while everyone else responds again. Resolve after all responses. A Nope remains legal until the window closes, including countering another Nope; select a Nope in your hand to block your own latest play. Eliminated players do not respond. Draws, Bomb and Defuse are outside this window.'],['Matching combinations','Two matching cards take one random card from a target. Three matching cards request a named type and obtain one only if the target holds it. Ordinary cat cards mainly serve combinations; other matching types may also be combined. This edition does not use the older five-different-card discard recovery or the faster reduced-deck variant.'],['Ending and privacy','The final survivor wins immediately. Hands, peeks and reinsertion positions remain private; opponents see hand counts. Open the discard pile for up to 12 recent public discards, newest first. Pass-and-play seat switching is for practice, not private multiplayer.']])},
werewolf:{zh:guide('月夜议会 · 6–18 位玩家；法官模式额外一名法官。可选人数牌型、屠边或人数胜利；含警长与技能交互。',[
'先选择玩家操作、法官主持或只发身份模式，所有人私下查看身份。','夜间按自己看到的指示使用技能，其他人等待。','天亮后面对面讨论，寻找叙述矛盾；不要把自己的屏幕给别人看。','按提示竞选警长并投票，白天投票放逐可疑玩家。','好人清除全部狼人获胜；狼人按本桌设置，以清除全部平民或全部神职（屠边），或存活人数达到好人人数（人数）获胜。'],[
['三种模式','玩家操作：各自手机提交技能、发言结束和投票。法官主持：房主不参与身份发牌，由法官按现场决定录入结果；其他人只看身份。只发身份：所有人都拿角色，之后在线下完成流程，房主可确认重发，旧身份立即作废。'],['角色配置与目标','常用板型有九人预女猎，以及十二人预女猎白、预女猎守、狼王守卫。九人局为三狼、三民、三神；十二人局为四狼、四民、四神，狼王替换一名普通狼人。选牌型时可查看完整配比，法官不占身份位。灵活人数板型支持八至十八人；自动配置支持六至十八人，八人起加入猎人、十二人起加入守卫。好人消灭全部狼人获胜；屠边模式中狼人消灭所有平民或所有神职中的任一类获胜；人数模式中狼人存活人数达到或超过好人时获胜。待结算的猎人开枪先于胜负判断。'],['夜晚技能','狼人共同选择击杀目标；预言家查验一人阵营，结果只给本人。守卫保护一人，不能连续两夜守同一个人。','女巫各有一次解药和毒药，不能自救，同夜不能同时使用两瓶。守卫保护与解药同时作用于同一人时该人仍死亡。毒杀绕过普通保护。'],['警长与白天','首夜行动后先进行警长竞选，再公布死讯。玩家选择上警、可退水，候选发言后投票选警长。警长在白天放逐时的票按 1.5 票计算；警长出局时可移交警徽或撕毁。','白天按界面顺序发言并确认结束，然后存活玩家秘密投票，可以弃票。平票进入候选 PK 发言与复投；进一步平票按界面结算，不私自选择获胜者。'],['白痴与狼王','白痴被放逐时公开身份并存活，此后不能投票或再次被放逐；若持有警徽则撕毁。夜间被刀、被毒或被枪击仍会死亡，并按神职计算屠边。','狼王与狼队共同行动，出局可开枪；被毒或自爆不能开枪，最后一狼出局立即判好人胜利。狼王和猎人的开枪阶段使用相同公开标题，不暴露开枪者具体身份。'],['出局与特殊情况','猎人被普通方式淘汰后可以开枪带走一人或放弃；被女巫毒死不能开枪。狼人可以在允许阶段自爆，跳过后续流程进入对应夜晚。界面会处理警徽交接及技能导致的连续死亡。','死亡后不能继续参加普通投票或夜间行动。公开日志与个人查验分开，不应从其他玩家视图获得秘密身份。'],['主持与掉线','法官模式必须根据现场讨论和实际技能录入，而不是让其他手机自动猜测。所有人应提前同意该桌规则。联机掉线会保留身份并暂停；永久缺席时房主可结束本局重新准备。']]),
en:guide('Moonlit Council · 6–18 players, plus a moderator in moderator-led mode. Choose role presets and class-elimination or parity victory. Includes an elected leader.',[
'Choose player actions, moderator-led, or role-dealing mode, then privately inspect your role.','At night, follow your private ability prompts and wait for other roles.','Discuss in person after dawn. Look for inconsistent stories and protect your screen.','Elect a leader when prompted, then vote to exile a suspect during the day.','Good wins by removing every Werewolf. Depending on the selected victory rule, Werewolves win by eliminating all ordinary Villagers or all special roles, or by reaching parity with good.'],[
['Modes','Player actions uses each player’s device for abilities, speech confirmation and votes. Moderator-led reserves the host as a non-playing moderator who records in-person decisions. Deal-only distributes roles for an offline game; confirmed redealing replaces every old role.'],['Roles and victory','Fixed setups include the nine-player classic trio and twelve-player Fool, Guard, and Wolf King–Guard boards. Nine-player games have three wolves, three citizens and three special roles; twelve-player games have four of each, with Wolf King replacing one ordinary wolf. The setup screen shows the complete lineup. The moderator occupies an extra seat. Flexible boards allow eight to eighteen players; adaptive mode allows six to eighteen, adding Hunter at eight and Guard at twelve. Good wins when no Werewolf survives. Class elimination lets Werewolves win by eliminating all ordinary Villagers or all special roles. Parity instead requires at least as many living Werewolves as good players. Resolve a pending Hunter shot before checking victory.'],['Night abilities','Werewolves choose a victim. Seer privately checks a player’s team. Guard protects someone but cannot repeat the previous night’s target. Witch has one antidote and one poison, cannot self-save, and cannot use both in one night. Simultaneous protection and antidote fail together; poison bypasses ordinary protection.'],['Leader and daytime','After the first night, elect the leader before announcing casualties. Candidates may withdraw, speak and receive votes. The leader’s exile vote counts as 1.5. On elimination, the leader transfers or destroys the badge.','Follow the speaking order and confirm when finished. Living players vote privately and may abstain. A tie creates a runoff discussion and vote among tied candidates; the table resolves a further tie.'],['Fool and Wolf King','Exile reveals the Fool without eliminating them. They lose their vote, cannot be exiled again, and must destroy any leader badge. A night attack, poison or shot still eliminates them; they count as a special role for class elimination.','Wolf King acts with the wolves and may shoot when eliminated, except by poison or self-explosion. Eliminating the last wolf ends the game immediately. Hunter and Wolf King share the public shooting-phase title so the exact role stays private.'],['Elimination and special cases','An eliminated Hunter may shoot one player or decline, except when poisoned. A Werewolf can self-reveal in supported phases, advancing the flow. The table handles chained deaths and badge transfers. Eliminated players cannot take ordinary night actions or vote. Private checks are separate from the public log.'],['Moderating and interruptions','The moderator must enter the group’s actual in-person choices. Agree on this ruleset beforehand. A lost connection preserves roles and pauses online play. If someone cannot return, the host can end the game and start a new one.']])},
avalon:{zh:guide('迷雾远征 · 5–10 人 · 基础任务规则，加入守望者与伪先知身份；三次成功后刺杀先知。',[
'私下看清自己的身份和已知人物，不要直接展示屏幕。','队长点选本轮需要的人数组成远征队。','所有人投赞成或反对，过半赞成才能出发。','入队者秘密交成功或失败牌；正义只能交成功。','正义完成三次任务后，仍需躲过邪恶刺客的最终刺杀。'],[
['配置与身份','五六人有两名邪恶，七至九人有三名，十人有四名。先知是好人，知道所有坏人但必须隐藏身份；守望者是好人，看到先知和伪先知两人，但分不清真假。伪先知是坏人，用假身份迷惑守望者；刺客是坏人，在三次任务成功后指认先知。邪恶互相知道队友，其余角色分别为远征队员或暗影同伴。个人身份页列出本角色确切已知信息。'],['任务人数','五人局五轮人数为 2/3/2/3/3；六人为 2/3/4/3/4；七人为 2/3/3/4/4；八至十人为 3/4/4/5/5。队长可以把自己列入队伍。'],['组队与表决','队长提名后所有玩家同时秘密表决。赞成必须超过总人数一半，平票也算否决。未通过则换下一位队长，重新组队。连续五次队伍被否决时邪恶立即获胜；任务成功出发后否决计数重置。'],['秘密任务牌','只有入队者提交任务牌。正义必须成功，邪恶可成功或失败。一般至少一张失败就导致任务失败；七人以上的第四次任务需要至少两张失败。只公开结果和失败数量，不公开谁交了哪张。'],['胜负与最后刺杀','三次任务失败时邪恶获胜。三次任务成功并不直接结束：邪恶刺客指认先知，命中则邪恶翻盘，否则正义获胜。','本桌不含额外身份扩展或额外信息道具。发言在现场进行；身份页显示的线索不能通过截图向别人证明。']]),
en:guide('Mistbound Quest · 5–10 players · Base quests with Watcher and False Seer roles; a final assassination after three successes.',[
'Privately inspect your role and known information.','The leader selects the required expedition team.','Everyone approves or rejects. More than half must approve.','Selected members secretly submit Success or Fail; the good team can only submit Success.','After three successful missions, the good team must still survive the Assassin’s final guess.'],[
['Teams and roles','There are two evil players with five or six, three with seven to nine, and four with ten. The good Seer knows all evil players and must stay hidden. The good Watcher sees both the Seer and False Seer, without knowing which is which. The evil False Seer deceives the Watcher; the evil Assassin makes the final guess. Evil players know one another. Your private role screen states exactly what you know.'],['Team sizes','Across five missions: 2/3/2/3/3 for five players; 2/3/4/3/4 for six; 2/3/3/4/4 for seven; 3/4/4/5/5 for eight to ten. Leaders may include themselves.'],['Proposals and votes','All players vote secretly. Approval needs a strict majority, so a tie rejects. Rejection passes leadership to the next seat. Five consecutive rejected proposals immediately give evil the win. Launching a mission resets the rejection count.'],['Mission cards','Only selected players submit. Good players must choose Success; evil may choose either. One Fail normally defeats a mission, but mission four with at least seven players requires two. Reveal the result and fail count, not individual submissions.'],['Victory and final guess','Three failed missions give evil the win. After three successes, the Assassin identifies the Seer. A correct guess gives evil victory; otherwise good wins. Extra expansion roles and information items are not included. Discuss aloud without using screenshots as proof of secret knowledge.']])},
sushi:sushiGuides,
century:{zh:guide('香料商旅 · 2–5 人 · 商人手牌构筑、香料交易与订单竞赛。',[
'每人有“获得两枚黄色”和“升级两次”两张起始牌。','先收香料，再用升级或交易换成订单需要的颜色。','点商人市场招募更好的牌；越靠右需要付出的路费越多。','用完的牌在休整时全部收回，休整也是一个回合。','二至三人局完成六张订单、四至五人局完成五张订单触发最后一轮；本轮所有人行动次数相同后比较总分。'],[
['准备','市场公开六张商人、五张订单，金银币各为人数两倍。起始玩家三黄，第二三位四黄，第四五位三黄一红。每人商队容量十枚。颜色由低到高是黄、红、绿、棕。'],['每回合一项行动','打出一张商人、招募一位商人、完成一个订单，或休整收回全部已打出的商人。获得新牌立即进入手牌，但本回合不能再使用。'],['收获、升级、交易','收获牌取得所示香料。升级把一枚香料提升一级，可以把同一枚连续升多级，也可分给多枚，允许提前结束。最高级不能再升级。','交易按牌面支付与获得比例进行，可在这次打牌中重复任意次数，只要每次付得起。交易可以暂时超过十枚容量，结束本回合才归还。'],['招募与订单','招募时在目标左侧每张牌各放一枚任意香料，最左免费；取得目标牌上积累的全部香料。空位向左补齐，最右补新牌。','订单按所示颜色精确支付，并保留订单分数。第一位订单奖励金币，第二位奖励银币；金币用完后银币移到第一位，奖励用完就不再发。'],['容量、末轮与计分','回合末只留十枚香料，超出部分自行归还。二三人有人完成第六张订单、四五人第五张时触发末轮，继续到起始玩家前一位。','总分为订单分、每金币三分、每银币一分，以及每枚非黄色香料一分。平分时座次更靠后者胜。市场和订单耗尽时不再补牌。']]),
en:guide('Spice Caravan · 2–5 players · Build a merchant hand, trade spices and race for orders.',[
'Start with Gain Two Yellow and Upgrade Twice.','Collect spices, then upgrade or trade into an order’s colors.','Recruit better merchants. Cards further right require more toll payments.','Rest to return every used merchant to your hand. Rest uses a turn.','Complete six orders with two or three players, or five with four or five, to trigger the final round. Finish with equal turns, then compare total scores.'],[
['Setup','Reveal six merchants and five orders. Gold and silver supplies each equal twice the player count. The first seat starts with three yellow, seats two and three with four yellow, and seats four and five with three yellow plus one red. Capacity is ten. Spice order is yellow, red, green, brown.'],['One action per turn','Play a merchant, recruit one, complete one order, or rest to retrieve every used merchant. Newly recruited cards join your hand but cannot be used as an extra action that turn.'],['Gain, upgrade and trade','Gain cards provide their displayed spices. Each upgrade improves one cube by one level; improve the same cube repeatedly or different cubes, and stop early if desired. Brown cannot upgrade.','A trade may repeat any number of times during that card’s action while you can pay its cost. Temporary holdings may exceed ten; check capacity at turn end.'],['Recruiting and orders','Pay one chosen cube onto each merchant left of your target; the leftmost is free. Collect the recruited card and all cubes on it. Slide the row left and refill at the right.','Pay an order’s exact colors and keep its points. The first order awards gold and the second silver. When gold is exhausted, silver moves to the first slot. Exhausted coin piles award nothing.'],['Capacity and ending','Return cubes down to ten at turn end. A sixth order with two or three players, or a fifth with four or five, triggers the final round. Finish through the seat before the starting player.','Add order points, three per gold, one per silver and one per non-yellow cube. Ties favor the later starting seat. Exhausted card decks no longer refill vacancies.']])},
uno:{zh:guide('七彩接龙 · 2–10 人 · 基础四色牌组，按牌面数字和功能匹配。',[
'点选同色、同数字或同符号牌，再点“出牌”；也可双击或双触直接出牌，万能牌仍需选色。','万能牌可以指定新颜色；+2 与 +4 不允许叠加逃避罚牌。','抽一张后只能打出刚抽到的那张，或保留结束。','只剩一张时点“喊最后一张”；跳过声明后，对手有一次确认或抓漏喊的机会。','出完手牌获得其他人剩余牌的分数；默认累计到 500 分获胜，也可选择只玩一轮。'],[
['准备与普通出牌','每人七张，翻出一张起始牌。顺序从起始玩家开始；起始跳过、反转、+2 会先产生对应效果，起始+4重翻。起始万能牌由先手选色。','出一张同色、同数或同功能的牌，也可打普通万能牌。可以主动抽牌，即使手中有可出的牌。抽后不能改出其他旧手牌。'],['功能牌','跳过让下一人失去回合。反转改变顺序，两人局效果等同跳过。+2 等下一人确认后抽两张并失去回合。普通万能牌选择继续使用的颜色。','+4 选择颜色并让下一人承担罚牌；合法条件是出牌前没有当前颜色的牌，数字或功能相同不妨碍。罚牌不叠加，不能用另一张+2或+4转嫁。'],['质疑 +4','建桌或大厅可切换 +4 质疑规则，默认开启。关闭时系统不允许持有当前颜色的玩家出 +4，下家手动确认后抽四张并跳过，没有质疑环节。','开启时可以诈出 +4，但下一位被罚玩家可接受抽四张或提出质疑。质疑成功时出牌者抽四张，质疑者继续正常回合；质疑失败时质疑者抽六张并失去回合。','质疑时仅质疑者能看到出牌前的手牌证据及原颜色，确认后继续；其他人只看结论。'],['最后一张声明','打到只剩一张时本人选择喊牌或跳过。跳过后，其他人可抓漏喊使其补两张，或确认继续。所有人确认后窗口关闭；采用明确确认而非网速计时，断线不会自动错失机会。'],['抽牌与牌堆','抽到的牌可以立即打出，若可用也可以保留并结束。不合条件时直接结束。抽牌堆用完保留当前弃牌，洗匀其余弃牌重新抽。'],['结束与分数','有人出完手牌后本轮结束；末张+2或+4的罚牌先结算再计分。数字牌按面值，跳过/反转/+2各二十分，万能/+4各五十分。','默认累计比赛至一人达到 500 分。每轮结算后，由房主或本轮赢家开始下一轮并保留累计分数。建桌可改为单轮；完整比赛结束才记录一条个人战绩。']]),
en:guide('Color Dash · 2–10 players · Base four-color deck with number and action matching.',[
'Select a matching card, then press Play card. Double-click or double-tap to play directly; wild cards still ask for a color.','Wild cards choose a color. Draw Two and Draw Four cannot be stacked.','After drawing, play only the newly drawn card or keep it and end your turn.','Declare your last card when prompted. Skipping opens a chance for opponents to catch you.','Empty your hand to score the cards remaining in other hands. First to 500 wins by default; a single round is optional.'],[
['Setup and ordinary play','Deal seven each and reveal a starting card. Initial Skip, Reverse and Draw Two apply their effects; replace an initial Draw Four. An initial Wild asks the starting player to choose a color.','Play one matching color, number or action, or a Wild. You may choose to draw despite holding a playable card. After drawing, you cannot play an older card from your hand.'],['Actions','Skip removes the next player’s turn. Reverse changes direction and acts as Skip with two players. Draw Two waits for the next player to confirm, then draws two and skips their turn. Wild selects the continuing color.','Wild Draw Four changes color and applies a penalty. It is legal only without a card matching the previous color; matching number or action alone does not prohibit it. Draw penalties never stack.'],['Draw Four challenges','Toggle challenges during setup or in the lobby; they are on by default. With challenges off, Draw Four is blocked if you hold the current color, and the next player confirms, draws four and skips their turn.','With challenges on, the next affected player may accept four cards or challenge a Draw Four bluff. A successful challenge makes the offender draw four and preserves the challenger’s normal turn. A failed challenge makes the challenger draw six and lose the turn.','Only the challenger sees the offender’s pre-play hand and previous color, then confirms to continue. Other players see only the outcome.'],['Last-card declaration','After playing down to one card, declare it or skip. If skipped, opponents can catch the missed call for a two-card penalty or confirm Continue. The window closes after all confirmations. Explicit responses replace a network-speed timer, so a disconnect cannot silently consume the opportunity.'],['Drawing and recycling','You may immediately play the drawn card if legal or keep it and end. An unusable draw ends your turn. When needed, keep the top discard and shuffle the remaining discards into a new draw pile.'],['Ending and score','An empty hand ends the round, after any final draw-card penalty. Numbers score face value, Skip/Reverse/Draw Two twenty, and Wild/Draw Four fifty.','The default match ends when a player reaches 500 points. After each round, the host or round winner starts the next deal while cumulative scores persist. Choose Single round during setup for a shorter game. A personal result is recorded only when the selected match ends.']])},
codenames:{zh:guide('密语行动 · 4–12 人 · 红蓝两队，队长给线索，队员猜出己方词语。',[
'按座位交替分红蓝，每队第一位是队长；队长独自查看秘密地图。','队长输入一个词语线索和一个数量，数量表示它能关联几个己方词。','队员讨论后点选想猜的词，确认揭晓；个人标记可循环记为候选、排除或清除，只有自己可见。','猜中己方可以继续，猜到中立或对方会结束回合，猜到刺客立即输。','先找齐全部己方词语的队伍获胜。'],[
['准备与身份','桌面二十五个词，先手队九个目标，后手八个，中立七个，刺客一个。每队有一位队长，其余是猜词队员。只有队长能看到未揭晓词的归属；队员仅看到已揭晓颜色。'],['合法线索','队长给一个词和数量，用含义关联目标，不能直接用仍在桌面的词、其明显词形，或借拼写位置、颜色、手势暗示。系统检查长度和直接重复，语义公平性需要双方共同遵守。队长承认线索违规后结束本队回合，对方队长可揭晓一个己方目标作为补偿。','词库语言在开局时确定，切换界面语言不会替换这一局的秘密词。所有队员应在开局前确认使用相同语言。'],['猜测次数','至少猜一次；每次猜中己方后可继续或结束，普通上限是线索数量加一，额外一次可用于之前没猜完的旧线索。每次只能确认一个未揭晓词。线索数量选零或不限时可无限猜，但仍须至少猜一次，猜错仍结束回合。'],['揭晓与换队','己方目标保持回合；中立词结束回合；对方目标帮助对手并结束回合；刺客使当前队伍立刻失败。队长不能替队员点词，也不能在队员讨论时补充提示。'],['终局与主持约定','任一队全部目标揭晓即获胜，即使最后一个目标是被对方误猜出来。多人队员应先口头达成一致，再由一位提交。本桌无单人、合作或双人变体。']]),
en:guide('Secret Signals · 4–12 players · Two teams, private clue maps and shared word guesses.',[
'Seats alternate red and blue; each team’s first seat is its clue giver.','The clue giver submits a word and a number connecting their team’s targets.','Operatives discuss and confirm one word to reveal it. Personal notes cycle through possible, ruled out and clear; only you see them.','Your own target lets you continue; neutral or enemy words end the turn, and danger loses immediately.','The first team to uncover all its targets wins.'],[
['Setup and roles','Twenty-five words contain nine starting-team targets, eight opposing targets, seven neutral words and one danger. Each team has a clue giver and operatives. Only clue givers see unrevealed ownership; operatives see colors after revealing.'],['Fair clues','Give one meaning-based clue and a number. Do not use an unrevealed board word or obvious form of it, spelling, positions, colors or gestures. Length and direct repetition can be checked automatically; semantic fairness requires agreement. A clue giver may concede an invalid clue, ending the turn and allowing the opposing clue giver to reveal one of their own targets as compensation.','Word language is selected at game creation. Changing interface language does not replace this game’s secret words. Agree on the word language before starting.'],['Guess allowance','Make at least one guess. After a correct own-team target, continue or stop. The ordinary maximum is clue number plus one; the extra guess can address an earlier clue. Confirm only one unrevealed word at a time. Zero and Unlimited allow any number of guesses, with at least one required; a wrong guess still ends the turn.'],['Reveals and turns','Own targets keep your turn alive. Neutral ends it. Enemy targets help the other team and end it. Assassin loses immediately. Clue givers cannot click guesses or add hints during discussion.'],['Ending and table conventions','A team wins as soon as all its targets are revealed, even if the opponent uncovered the last one. Discuss before one operative submits. Solo, cooperative and two-player variants are not included.']])},
drawguess:{zh:guide('你画我猜 · 3–12 人 · 轮流画图，最快猜中者得分。',[
'画手从仅自己可见的三个词中选择一个，然后在倒计时内画图。','其他玩家输入猜词；第一位猜中者得 2 分，画手得 1 分。','每位玩家轮流作画，完成设定轮数后比较总分。','答案和候选词只发送给画手，观战者只看公共画板和猜词。'],[
['回合与得分','画手从三个秘密词中选一个，其他玩家在倒计时内猜词。第一位猜中的玩家得两分，画手得一分。每个普通猜词都会公开；猜中时只显示有人猜对，答案在揭晓时才公开。','本桌默认每位玩家画一轮，房主可在开局前设定一至六轮，以及四十五、六十、七十五或九十秒的作画时长。最高分获胜，平分并列。'],['画板','画板最多保留 180 笔。画笔工具提供颜色、五档粗细和橡皮擦，可撤销上一笔或确认清空。'],['隐私与断线','候选词和答案只在画手视图中存在，其他玩家与观战者只收到公开画板、分数和未猜中的文字。答案在本轮揭晓后才公开。','联机时有玩家断线会暂停当前回合并保留座位；重连后从相同画面继续。']]),en:guide('Mocha Sketch · 3–12 players · Take turns drawing and race to guess.',[
'The drawer picks one of three private prompts, then draws before the timer ends.','The first correct guess earns 2 points and the drawer earns 1 point.','Players rotate through drawing turns; compare total points after the selected rounds.','Only the drawer receives prompts and answers. Spectators see the public canvas and guesses.'],[
['Turns and scoring','The drawer chooses one private prompt while everyone else guesses during the timer. The first correct player receives two points and the drawer receives one. Ordinary guesses are public; a correct entry only says someone guessed it until the reveal.','The default is one drawing turn per player. The host can select 1–6 cycles per player and 45, 60, 75, or 90 seconds per drawing turn. Highest score wins and ties remain ties.'],['Canvas','The canvas holds up to 180 strokes. Drawing tools offer colors, five widths and an eraser, plus undo and confirmed clearing.'],['Privacy and reconnecting','Only the drawer view contains prompt choices and the answer. Other players and spectators receive public strokes, scores, and non-correct guess text. The answer appears only at the reveal.','A player disconnect pauses the current online turn while preserving seats. Reconnect to continue from the same canvas.']])},
undercover:{zh:guide('异词同伴 · 3–12 人 · 秘密发词工具。',[
'每人私下查看自己的词，记住后收起。','多数人拿相同的词，少数人拿相近的另一个词。','描述、讨论、投票与胜负由大家在线下组织。','从菜单重新开局可再次发词。'],[
['发词','三至六人有一位异词玩家，七至十人两位，十一至十二人三位。不含白板。每人只收到自己的词，不显示自己属于哪一方。'],['隐私与重开','换座或重新开局后词卡自动隐藏；切换界面语言不改变本局词语。旁观者看不到词或身份。重新开局随机选择词对并分配。','本工具不记录发言顺序、票数、淘汰或胜负，也不公开完整词对。']]),
en:guide('Odd Word Out · 3–12 players · Private word dealer.',[
'Privately check your word, then hide it once remembered.','Most players share one word; a minority receives a related word.','Organize descriptions, discussion, voting and victory in person.','Restart from the menu to deal again.'],[
['Dealing','There is 1 odd-word player with 3–6 players, 2 with 7–10 and 3 with 11–12. No blank roles. Each player receives only their word, without knowing their group.'],['Privacy and new deals','Words hide when changing seats or restarting. Interface language changes preserve the dealt words. Spectators receive no words or identities. Restart to choose and distribute a new pair.','The tool does not track turns, votes, eliminations or winners, and never reveals the full word pair.']])}
};
