import type {Guide} from '../ui/RuleGuide';
const make=(edition:string,quick:string[],rows:[string,...string[]][]):Guide=>({edition,quick,sections:rows.map(([title,...text])=>({title,text}))});
export const sushiGuides={zh:make('寿司小宴 · 基础版 2–5 人；派对版 2–8 人。',[
'选牌后确认，全部锁定后同时揭晓，再把余牌传给左边。','开局可选 108 张基础版，或派对版自选菜单；两种版本计分有差异。','盘面卡片可点开查看功能；本桌菜单列出所选牌种。','进行三轮，最后结算甜点；总分同分时甜点更多者胜。'],[
['基础版','每轮 2/3/4/5 人发 10/9/8/7 张；最后一张自动打出。已有筷子可换成同时选两张，按选择顺序打出，再把筷子传出去。','卷数第一平分 6 分并向下取整；第一并列时无第二名，否则第二平分 3 分。零卷无分。布丁最多平分 +6、最少平分 −6；两人不扣分，全员相同时零分。'],
['派对版菜单与发牌','固定握寿司，另选 1 种卷、3 种不同前菜、2 种不同特殊牌、1 种甜点。毛豆与勺子限 3–8 人；菜单与特别点单限 2–6 人。包含基础盒全部牌种，不含促销与扩展牌。','2–3/4–5/6–7/8 人每轮发 10/9/8/7 张。2–5 人三轮分别加入 5/3/2 张甜点，6–8 人加入 7/5/3 张。已打出甜点跨轮保留，其余牌与余牌堆洗混再发。'],
['共同计分','每两张天妇罗 5 分，每三张刺身 10 分；零散余牌 0 分。饺子 1–5 张得 1/3/6/10/15 分，更多仍为 15。玉子、三文鱼、鱿鱼握寿司得 1/2/3 分。先打出的空芥末使下一张握寿司变成三倍，每张芥末限一次。'],
['派对版卷与前菜','寿司卷按卷数排名，2–5 人前两名 6/3 分，6–8 人前三名 6/4/2 分；并列各得全分，后续不同卷数仍获下一档。手卷最多 +4、最少 −4，并列各算，两人不扣分。','反卷累计到 10 立即得 8/5/2 分并弃掉这些反卷。同手达到时按卷数比较，再并列则同获该名次并跳过后续名次。轮末最多剩余反卷者得下一个未颁名次，可重复获奖。','鳗鱼一张 −3，两张以上共 7。豆腐一张 2、两张 6、三张以上 0。饭团不同形状凑一组得 1/4/9/16，可组多套。毛豆每张按其他有毛豆的玩家数计分，上限 4。味噌汤每张 3，但同一手出现两张以上时，这一手的所有汤都弃掉，包括特殊牌追加的。'],
['派对版特殊牌','锁定前声明本手要用的一张旧筷子或旧勺子，揭牌后按右下角号码从小到大处理，菜单与打包盒也参加排序。筷子揭牌后从剩余手牌再选一张，筷子放回传出的手牌。勺子索取指定种类或具体变体，左侧首位持有者交一张并收下勺子；无人持有则弃勺。','菜单从余牌堆抽四张，选一张非菜单立即打出，剩余洗回，菜单弃掉。打包盒可翻转此前轮次打出的任意牌，翻面牌失去原功能，每张 2 分。','特别点单在揭牌前选定自己本轮已打出的牌，复制其种类、图标或翻面状态。首手无目标则弃掉。复制甜点跨轮保留；复制已用芥末仍得到空芥末；复制已在芥末上的握寿司不获得原加成；复制未加成握寿司时可选择是否使用空芥末。通过其他特殊牌获得点单时立即选择复制对象。','酱油：本轮牌面颜色种类最多或并列最多者每张 4 分。茶：每张按自己最大同色组张数计分。握寿司与芥末同色，变体同色，翻面牌同色；只计本轮甜点。'],
['派对版甜点','布丁最多 +6、最少 −6，并列各得全分，两人不扣分。抹茶冰淇淋每四张 12 分，余数 0。水果分西瓜、橙子、菠萝分别计图标：0/1/2/3/4/5+ 个得 −2/0/1/3/6/10 分。总分再同分时比较甜点张数，仍相同则并列。']]),
en:make('Sushi Social · Classic: 2–5 players. Party: 2–8 players.',[
'Choose and confirm a card. Reveal together once everyone locks in, then pass remaining hands left.','Choose the 108-card Classic edition or a custom Party menu. Their scoring differs.','Tap played cards for details; Table menu lists the selected card families.','Play three rounds, then score desserts. Most dessert cards break a score tie.'],[
['Classic','Deal 10/9/8/7 cards with 2/3/4/5 players. The final card plays automatically. Previously played Chopsticks allow two picks in selection order; return Chopsticks to the passing hand.','Most Maki icons share 6 points, rounded down. Tied first leaves no second-place award; otherwise second shares 3. Zero earns nothing. Most Pudding shares +6 and fewest shares −6; no penalty for two players, and equal counts for everyone score zero.'],
['Party menu and dealing','Always use Nigiri, plus 1 roll, 3 different appetizers, 2 different specials and 1 dessert. Edamame and Spoon require 3–8 players; Menu and Special order require 2–6. All base-box families are included; promos and expansions are excluded.','Deal 10/9/8/7 with 2–3/4–5/6–7/8 players. Add 5/3/2 desserts over the rounds with 2–5 players, or 7/5/3 with 6–8. Keep played desserts aside between rounds; shuffle other cards back into the unused deck.'],
['Shared scores','Each Tempura pair scores 5; each Sashimi triple 10; unmatched extras score 0. One to five Dumplings score 1/3/6/10/15, capped at 15. Egg/Salmon/Squid Nigiri score 1/2/3. An empty Wasabi triples the next Nigiri you play; each Wasabi is used once.'],
['Party rolls and appetizers','Maki awards 6/3 for the top two totals at 2–5 players, or 6/4/2 for the top three at 6–8. Ties receive full points; the next distinct total still earns the next award. Temaki awards +4 for most and −4 for fewest, including ties; no penalty with two players.','Reaching 10 Uramaki icons scores 8/5/2 immediately; discard those cards. Same-turn arrivals compare icon totals; remaining ties receive the same award and skip subsequent places. At round end, most remaining icons earn the next unclaimed award. One player can earn multiple awards.','Eel: one −3, two or more 7. Tofu: one 2, two 6, three or more 0. Onigiri sets with different shapes score 1/4/9/16; multiple sets count. Each Edamame scores the number of opponents with any Edamame, up to 4. Miso scores 3, but discard every Miso played on a turn with more than one, including bonus plays.'],
['Party specials','Declare at most one old Chopsticks or Spoon before locking. Resolve after reveal in printed-number order; Menu and Takeout also join that order. Chopsticks select an extra card from the remaining hand after reveal, then return to that hand. Spoon requests a type or exact variant; its first holder to your left gives one and receives the Spoon. If nobody has it, discard Spoon.','Menu privately draws four unused cards. Play one other than Menu, shuffle the rest back, then discard Menu. Takeout flips any cards from previous turns this round. Flipped cards lose their former function and score 2 each.','Special order chooses a previously played card before reveal, copying its type, icons or flipped state. With no target on the first turn, discard it. Copied desserts persist between rounds. Copying used Wasabi creates empty Wasabi; copying boosted Nigiri does not copy its boost. When copying unboosted Nigiri, choose whether to use an empty Wasabi. When obtained through a bonus action, choose the copy immediately.','Each Soy sauce scores 4 if you have the most different card colors, including ties. Each Tea scores the size of your largest color group. Nigiri and Wasabi share a color; variants share a color, as do flipped cards. Only this round’s desserts count.'],
['Party desserts','Pudding: most +6, fewest −6; ties receive full points and two-player games have no penalty. Green tea ice cream: each set of four scores 12, extras 0. Score each fruit type separately: 0/1/2/3/4/5+ watermelon, orange or pineapple icons score −2/0/1/3/6/10. Break score ties by dessert-card count; any remaining tie is shared.']])};
