export const wordGameText:Record<string,string>={
 '等待红队队长选择补偿揭晓，或放弃补偿':'Waiting for the Red team captain to reveal a compensation word or skip compensation',
 '等待蓝队队长选择补偿揭晓，或放弃补偿':'Waiting for the Blue team captain to reveal a compensation word or skip compensation',
 '按座位交替分红蓝队，每队首位玩家担任队长。':'Teams alternate by seat. The first member of each team is captain.',
 '队长承认无效线索，对方获得补偿':'Captain conceded an invalid clue. The other team receives compensation.',
 '补偿揭晓：':'Compensation reveal: ','私下查看并记住自己的词':'Privately read and remember your word','已投票，等待其他人':'Vote saved. Waiting for others.','讨论结束后，投出最可疑的一人':'After discussion, vote for the most suspicious player','复投仍平票，本轮无人淘汰':'Runoff tied again. Nobody is eliminated.','平票：':'Tie: ','不限次数':'Unlimited guesses','不相关 · 不限猜测次数':'Unrelated · unlimited guesses','不限猜测次数':'Unlimited guesses',
 '一个词加一个数字；线索必须关联含义，不能使用牌面词。':'One word and one number. Link meanings; do not use a board word.',

 '承认线索无效，交出回合':'Concede invalid clue and end turn','补偿揭晓一个己方词':'Reveal one team word as compensation','放弃补偿，开始线索':'Skip compensation and give a clue','双方讨论确认后使用；对方队长可免费揭晓一个己方词。':'Use after both sides agree. The opposing captain may reveal one of their team’s words.',
 '密语行动':'Secret Signals','异词同伴':'Odd Word Out','红队':'Red team','蓝队':'Blue team','队长':'Captain','队员':'Operative','你':'You','未揭晓':'Unrevealed','已揭晓':'Revealed','路人':'Bystander','危险目标':'Assassin','剩余':'Remaining','查看密钥':'Reveal key','收起密钥':'Hide key','密钥仅队长可见':'Only captains can see the key','你的身份':'Your role','当前线索':'Current clue','等待队长线索':'Waiting for a captain’s clue','等待对方回合':'Waiting for the other team','给队友一个词和一个数字':'Give your team one word and one number','线索词':'Clue word','线索数量':'Clue number','例如：天空':'Example: Sky','不限':'Unlimited','发送线索':'Send clue','结束猜测':'End guesses','确认猜词':'Confirm guess','至少猜一个词后才能结束':'Guess at least one word before ending','同队讨论后，由一位队员点选并确认':'Discuss as a team, then one operative selects and confirms','红方先手':'Red starts','蓝方先手':'Blue starts','回合':'Turn','还可猜':'Guesses left','查看本桌规则':'Table rules','词库语言':'Word language','中文':'Chinese','英文':'English',
 '两队交替行动，队长只能用一个词和一个数字给线索。先手找出 9 个词，后手找出 8 个词。队长不可参与点选。':'Teams alternate turns. Captains give one word and one number. The starting team has 9 words; the other has 8. Captains cannot guess.',
 '猜中己方词可以继续，最多猜线索数量加一次；猜到路人或对方词立即结束回合。猜中危险目标立即失败。先找齐己方词的一队获胜，也可能在对方回合获胜。':'A correct guess allows another, up to the clue number plus one. A bystander or opponent’s word ends the turn. Guessing the danger target loses the game immediately. The first team to reveal all its words wins, even on the other team’s turn.',
 '0 和不限线索均不限制猜测次数，但仍须至少猜一次。线索不可是未揭晓的牌面词或其变形，也不可暗示位置、拼写或发音；含义是否合法由在场玩家共同判断。':'Zero and unlimited clues allow any number of guesses, but at least one is required. Do not use an unrevealed board word or its inflection, or hint at position, spelling or sound. Players judge whether the meaning of a clue is valid.',
 '队长密钥属于私密信息。同屏试玩时，切换座位前请先收起密钥。':'The captain’s key is secret. In pass-and-play, hide it before changing seats.',
 '公开牌桌':'Public word grid','所有词与密钥均已揭晓':'All words and identities are revealed','查看我的词':'Reveal my word','收起我的词':'Hide my word','你的秘密词':'Your secret word','只展示给自己，别念出这个词':'For your eyes only. Do not say the word aloud.','看词后再准备':'Read your word, then get ready','记住了，准备描述':'I remember it · ready','已准备':'Ready','等待看词':'Reading word','描述结束':'Finish description','辩护结束':'Finish defense','确认投票':'Confirm vote','修改我的投票':'Change my vote','已投票':'Voted','等待投票':'Awaiting vote','仍在局中':'Still in play','已淘汰':'Eliminated','当前发言':'Speaking now','轮流描述':'Descriptions','秘密投票':'Secret vote','平票辩护':'Tie defense','秘密发词':'Secret words','本局结束':'Match complete','发言顺序':'Speaking order','复投候选':'Runoff candidates','多数词阵营':'Common-word team','异词阵营':'Odd-word team','上一轮投票':'Previous votes','完整揭晓':'Full reveal','你的投票已锁定':'Your vote is locked','正在等待其他玩家准备':'Waiting for everyone to get ready','其他玩家发言时请倾听':'Listen while another player speaks','线下或语音通话中描述，完成后点击按钮':'Describe aloud in person or on a voice call, then tap the button','讨论后选择最可疑的人，不能投自己':'Discuss, then choose the most suspicious player. You cannot vote for yourself.','淘汰后可以旁观，本局仍可随阵营获胜':'Eliminated players can watch and still win with their team.',
 '每人收到一个秘密词。多数人拿到相同词，少数人拿到相近的另一词；你只知道自己的词，不知道阵营。请用一句话轮流描述，不直接说出词本身。':'Everyone receives a secret word. Most share one word; a minority gets a similar word. You know your word, but not your team. Take turns describing it in one sentence without saying the word itself.',
 '描述后秘密投票，所有存活玩家投完再同时公布。最高票者淘汰并公开阵营。平票者依次辩护后，仅对平票候选复投；再次平票则本轮无人淘汰。':'After descriptions, living players vote secretly; votes reveal together. The highest vote is eliminated and their team is revealed. Tied players defend, then a runoff targets only those candidates. Another tie eliminates nobody.',
 '多数词阵营淘汰全部异词玩家即获胜；异词玩家人数达到或超过多数词玩家时获胜。3–6 人有 1 位异词玩家，7–10 人有 2 位，11–12 人有 3 位。本桌不含白板角色。':'The common-word team wins by eliminating every odd-word player. The odd-word team wins at equal or greater living numbers. There is 1 odd-word player with 3–6 players, 2 with 7–10, and 3 with 11–12. This table has no blank-word role.',
 '规则存在不同地区版本，本桌固定使用上述平票与阵营胜负规则。':'Regional rules vary. This table consistently uses the tie and victory rules described above.',
 '输入线索后发送':'Enter a clue to send','记住词后请收起，避免他人看到':'Hide your word after reading so others cannot see it.','胜方':'Winners','旁观':'Spectating'
};
export const wordGamePatterns:[RegExp,string][]=[[/^等待红队队长给出线索$/,'Waiting for the Red team captain’s clue'],[/^等待蓝队队长给出线索$/,'Waiting for the Blue team captain’s clue'],[/^红队猜词 · 还可猜 (\d+) 次$/,'Red team guesses · $1 remaining'],[/^蓝队猜词 · 还可猜 (\d+) 次$/,'Blue team guesses · $1 remaining'],[/^红队猜词 · 不限次数$/,'Red team guesses · unlimited'],[/^蓝队猜词 · 不限次数$/,'Blue team guesses · unlimited'],[/^已秘密发词，(\d+) 位异词玩家；淘汰前不公开阵营。$/,'Secret words dealt. $1 odd-word player(s); roles remain hidden until elimination.'],[/^第 (\d+) 轮 · 秘密投票$/,'Round $1 · Secret vote'],[/^第 (\d+) 轮 · 平票辩护$/,'Round $1 · Tie defense'],[/^第 (\d+) 轮 · 轮流描述$/,'Round $1 · Descriptions'],[/^请 (.+) 描述$/,'$1: describe your word'],[/^请 (.+) 辩护$/,'$1: defend your word'],[/^(.+) 淘汰 · 多数词阵营$/,'$1 eliminated · Common-word team'],[/^(.+) 淘汰 · 异词阵营$/,'$1 eliminated · Odd-word team'],[/^第 (\d+) 回合$/,'Turn $1'],[/^红队获胜$/,'Red team wins'],[/^蓝队获胜$/,'Blue team wins'],[/^多数词阵营获胜$/,'Common-word team wins'],[/^异词阵营获胜$/,'Odd-word team wins'],[/^请输入一个线索词$/,'Enter one clue word'],[/^线索需为 1–32 字的单个词，不含空格或数字$/,'Use one word of 1–32 letters, without spaces or numbers'],[/^线索不能使用尚未揭晓的牌面词或其直接变形$/,'A clue cannot be an unrevealed board word or its direct inflection']];
