import { action, assertPlayers, seeded, shuffle, validateCommand, type Action, type GameModule, type Player } from '../types';
import { ODD_WORD_PAIRS, localWord, type WordLanguage } from './wordBank';
export type OddRole='common'|'odd';
export interface UndercoverState {players:Player[];roles:OddRole[];words:[string,string];alive:boolean[];ready:boolean[];phase:'deal'|'describe'|'vote'|'defend';order:number[];speaker:number;votes:Record<string,string>;lastVotes:Record<string,string>;tied:string[];runoff:boolean;round:number;finished:boolean;winners:string[];winnerRole:OddRole|null;history:string[];language:WordLanguage}
const say=(s:UndercoverState,zh:string,en:string)=>zh;
const roleName=(s:UndercoverState,role:OddRole)=>say(s,role==='common'?'多数词阵营':'异词阵营',role==='common'?'Common-word team':'Odd-word team');
function checkEnd(s:UndercoverState){const odd=s.roles.filter((r,i)=>r==='odd'&&s.alive[i]).length,common=s.roles.filter((r,i)=>r==='common'&&s.alive[i]).length;if(!odd||odd>=common){s.finished=true;s.winnerRole=odd?'odd':'common';s.winners=s.players.filter((_,i)=>s.roles[i]===s.winnerRole).map(p=>p.id);s.history.push(say(s,`${roleName(s,s.winnerRole)}获胜`,`${roleName(s,s.winnerRole)} wins`));}}
function beginRound(s:UndercoverState){s.round++;s.phase='describe';s.order=s.players.flatMap((_,i)=>s.alive[i]?[i]:[]);const offset=(s.round-1)%s.order.length;s.order=[...s.order.slice(offset),...s.order.slice(0,offset)];s.speaker=0;s.votes={};s.tied=[];s.runoff=false;}
function tally(s:UndercoverState){s.lastVotes={...s.votes};const counts:Record<string,number>=Object.create(null);Object.values(s.votes).forEach(id=>counts[id]=(counts[id]||0)+1);const high=Math.max(...Object.values(counts)),tied=Object.keys(counts).filter(id=>counts[id]===high);s.votes={};
 if(tied.length>1){s.history.push(say(s,`平票：${tied.map(id=>s.players.find(p=>p.id===id)!.name).join('、')}`,`Tie: ${tied.map(id=>s.players.find(p=>p.id===id)!.name).join(', ')}`));if(s.runoff){s.history.push(say(s,'复投仍平票，本轮无人淘汰','Runoff tied again. Nobody is eliminated.'));beginRound(s);}else{s.tied=tied;s.runoff=true;s.phase='defend';s.order=s.players.flatMap((p,i)=>tied.includes(p.id)?[i]:[]);s.speaker=0;}return;}
 const eliminated=s.players.findIndex(p=>p.id===tied[0]);s.alive[eliminated]=false;s.history.push(say(s,`${s.players[eliminated].name} 淘汰 · ${roleName(s,s.roles[eliminated])}`,`${s.players[eliminated].name} eliminated · ${roleName(s,s.roles[eliminated])}`));checkEnd(s);if(!s.finished)beginRound(s);
}
export const undercover:GameModule<UndercoverState>={
 create(players,seed,options){assertPlayers(players,3,12);const rng=seeded(seed),language=options?.language==='en'?'en':'zh',pair=ODD_WORD_PAIRS[Math.floor(rng()*ODD_WORD_PAIRS.length)],oddCount=players.length<=6?1:players.length<=10?2:3;const words=shuffle(pair,rng).map(p=>localWord(p,language)) as [string,string],roles=shuffle<OddRole>([...Array(oddCount).fill('odd'),...Array(players.length-oddCount).fill('common')],rng);return{players:structuredClone(players),roles,words,alive:players.map(()=>true),ready:players.map(()=>false),phase:'deal',order:[],speaker:0,votes:{},lastVotes:{},tied:[],runoff:false,round:0,finished:false,winners:[],winnerRole:null,history:[`已秘密发词，${oddCount} 位异词玩家；淘汰前不公开阵营。`],language};},
 view(s,id){const me=s.players.findIndex(p=>p.id===id);if(me<0)return{kind:'undercover',phase:say(s,'不在本局','Not in this match'),instruction:say(s,'仅本局玩家可查看','Only match participants can view'),finished:s.finished,actions:[],sections:[],log:[],board:{}};
 const acting=(s.phase==='describe'||s.phase==='defend')&&s.order[s.speaker]===me,targets=s.players.filter((p,i)=>s.alive[i]&&p.id!==id&&(!s.runoff||s.tied.includes(p.id)));let actions:Action[]=[];
 if(!s.finished&&s.alive[me]){if(s.phase==='deal'&&!s.ready[me])actions=[action('ready',say(s,'记住了，准备描述','I remember it · ready'))];else if(acting)actions=[action('described',say(s,s.phase==='defend'?'辩护结束':'描述结束',s.phase==='defend'?'Finish defense':'Finish description'))];else if(s.phase==='vote')actions=Object.hasOwn(s.votes,id)?[action('cancel_vote',say(s,'修改我的投票','Change my vote'))]:[action('vote',say(s,'确认投票','Confirm vote'),targets.map(p=>({id:p.id,title:`${p.avatar} ${p.name}`,translateTitle:false})),1,1)];}
 const phase=s.finished?say(s,'本局结束','Match complete'):s.phase==='deal'?say(s,'秘密发词','Secret words'):say(s,`第 ${s.round} 轮 · ${s.phase==='vote'?'秘密投票':s.phase==='defend'?'平票辩护':'轮流描述'}`,`Round ${s.round} · ${s.phase==='vote'?'Secret vote':s.phase==='defend'?'Tie defense':'Descriptions'}`);
 const instruction=s.finished?say(s,`${roleName(s,s.winnerRole!)}获胜`,`${roleName(s,s.winnerRole!)} wins`):s.phase==='deal'?say(s,'私下查看并记住自己的词','Privately read and remember your word'):s.phase==='vote'?Object.hasOwn(s.votes,id)?say(s,'已投票，等待其他人','Vote saved. Waiting for others.'):say(s,'讨论结束后，投出最可疑的一人','After discussion, vote for the most suspicious player'):say(s,`请 ${s.players[s.order[s.speaker]].name} ${s.phase==='defend'?'辩护':'描述'}`,`${s.players[s.order[s.speaker]].name}: ${s.phase==='defend'?'defend your word':'describe your word'}`);
 return structuredClone({kind:'undercover',phase,instruction,finished:s.finished,actions,sections:[],log:s.history,board:{language:s.language,phase:s.phase,round:s.round,word:s.words[s.roles[me]==='common'?0:1],alive:s.alive[me],ready:s.ready[me],ownVote:Object.hasOwn(s.votes,id)?s.votes[id]:null,current:(s.phase==='describe'||s.phase==='defend')?s.players[s.order[s.speaker]].id:null,order:s.order.map(i=>s.players[i].id),tied:s.tied,runoff:s.runoff,lastVotes:s.lastVotes,winners:s.winners,winnerRole:s.winnerRole,...(s.finished?{words:s.words}:{}),players:s.players.map((p,i)=>({...p,alive:s.alive[i],ready:s.ready[i],voted:Object.hasOwn(s.votes,p.id),...(s.finished||!s.alive[i]?{role:s.roles[i]}:{}),...(s.finished?{word:s.words[s.roles[i]==='common'?0:1]}:{}),score:s.finished&&s.winners.includes(p.id)?1:0}))}});},
 apply(state,id,command){validateCommand(undercover.view(state,id),command);const s=structuredClone(state),me=s.players.findIndex(p=>p.id===id);
 if(command.action==='ready'){s.ready[me]=true;if(s.ready.every(Boolean))beginRound(s);}
 else if(command.action==='described'){s.speaker++;if(s.speaker>=s.order.length){s.phase='vote';s.votes={};}}
 else if(command.action==='cancel_vote'){delete s.votes[id];}
 else if(command.action==='vote'){s.votes={...s.votes,[id]:command.values[0]};if(s.players.every((p,i)=>!s.alive[i]||Object.hasOwn(s.votes,p.id)))tally(s);}
 s.history=s.history.slice(-60);return s;}
};
