/** Original, bilingual everyday vocabulary. A match fixes its language at creation. */
export type WordLanguage='zh'|'en';
export const SIGNAL_WORDS:[string,string][]=[
 ['月亮','Moon'],['太阳','Sun'],['星星','Star'],['银河','Galaxy'],['火箭','Rocket'],['卫星','Satellite'],['宇航员','Astronaut'],['彗星','Comet'],['地球','Earth'],['轨道','Orbit'],
 ['森林','Forest'],['沙漠','Desert'],['海洋','Ocean'],['河流','River'],['冰川','Glacier'],['火山','Volcano'],['山峰','Mountain'],['洞穴','Cave'],['岛屿','Island'],['瀑布','Waterfall'],
 ['老虎','Tiger'],['熊猫','Panda'],['海豚','Dolphin'],['企鹅','Penguin'],['蝴蝶','Butterfly'],['蜘蛛','Spider'],['蜜蜂','Bee'],['鲸鱼','Whale'],['狐狸','Fox'],['乌龟','Turtle'],
 ['苹果','Apple'],['柠檬','Lemon'],['樱桃','Cherry'],['面包','Bread'],['奶酪','Cheese'],['咖啡','Coffee'],['茶叶','Tea'],['巧克力','Chocolate'],['蜂蜜','Honey'],['蘑菇','Mushroom'],
 ['钢琴','Piano'],['吉他','Guitar'],['鼓','Drum'],['歌手','Singer'],['舞台','Stage'],['电影','Movie'],['画笔','Brush'],['相机','Camera'],['雕像','Statue'],['诗歌','Poem'],
 ['医生','Doctor'],['厨师','Chef'],['老师','Teacher'],['船长','Captain'],['侦探','Detective'],['农夫','Farmer'],['律师','Lawyer'],['园丁','Gardener'],['木匠','Carpenter'],['飞行员','Pilot'],
 ['城堡','Castle'],['桥梁','Bridge'],['灯塔','Lighthouse'],['港口','Harbor'],['机场','Airport'],['车站','Station'],['图书馆','Library'],['博物馆','Museum'],['医院','Hospital'],['剧院','Theater'],
 ['钥匙','Key'],['镜子','Mirror'],['时钟','Clock'],['雨伞','Umbrella'],['蜡烛','Candle'],['信封','Envelope'],['地图','Map'],['望远镜','Telescope'],['指南针','Compass'],['剪刀','Scissors'],
 ['王冠','Crown'],['宝石','Gem'],['黄金','Gold'],['白银','Silver'],['钻石','Diamond'],['珍珠','Pearl'],['盔甲','Armor'],['盾牌','Shield'],['长剑','Sword'],['旗帜','Flag'],
 ['足球','Football'],['篮球','Basketball'],['网球','Tennis'],['游泳','Swimming'],['滑雪','Skiing'],['象棋','Chess'],['赛车','Racing'],['跳舞','Dancing'],['拳击','Boxing'],['骑行','Cycling'],
 ['春天','Spring'],['夏天','Summer'],['秋天','Autumn'],['冬天','Winter'],['暴风','Storm'],['彩虹','Rainbow'],['雪花','Snowflake'],['闪电','Lightning'],['雾气','Fog'],['微风','Breeze'],
 ['电池','Battery'],['机器人','Robot'],['电脑','Computer'],['网络','Network'],['电话','Phone'],['激光','Laser'],['磁铁','Magnet'],['齿轮','Gear'],['引擎','Engine'],['电线','Wire'],
 ['火车','Train'],['飞机','Airplane'],['轮船','Ship'],['自行车','Bicycle'],['马车','Carriage'],['潜艇','Submarine'],['帆船','Sailboat'],['气球','Balloon'],['卡车','Truck'],['摩托车','Motorcycle'],
 ['梦境','Dream'],['记忆','Memory'],['秘密','Secret'],['运气','Luck'],['时间','Time'],['影子','Shadow'],['声音','Sound'],['光线','Light'],['温度','Temperature'],['速度','Speed'],
 ['羽毛','Feather'],['翅膀','Wing'],['树根','Root'],['花瓣','Petal'],['种子','Seed'],['贝壳','Shell'],['珊瑚','Coral'],['竹子','Bamboo'],['松树','Pine'],['橡树','Oak'],
 // Additional everyday subjects, independently selected and translated.
 ["猫","Cat"],
 ["狗","Dog"],
 ["兔子","Rabbit"],
 ["仓鼠","Hamster"],
 ["狮子","Lion"],
 ["大象","Elephant"],
 ["长颈鹿","Giraffe"],
 ["斑马","Zebra"],
 ["袋鼠","Kangaroo"],
 ["考拉","Koala"],
 ["骆驼","Camel"],
 ["河马","Hippopotamus"],
 ["犀牛","Rhinoceros"],
 ["鹿","Deer"],
 ["松鼠","Squirrel"],
 ["刺猬","Hedgehog"],
 ["水獭","Otter"],
 ["海豹","Seal"],
 ["鲨鱼","Shark"],
 ["章鱼","Octopus"],
 ["水母","Jellyfish"],
 ["海星","Starfish"],
 ["螃蟹","Crab"],
 ["龙虾","Lobster"],
 ["蜗牛","Snail"],
 ["蚂蚁","Ant"],
 ["蜻蜓","Dragonfly"],
 ["萤火虫","Firefly"],
 ["瓢虫","Ladybird"],
 ["青蛙","Frog"],
 ["鳄鱼","Crocodile"],
 ["蛇","Snake"],
 ["蜥蜴","Lizard"],
 ["猫头鹰","Owl"],
 ["鹦鹉","Parrot"],
 ["鸽子","Pigeon"],
 ["天鹅","Swan"],
 ["孔雀","Peacock"],
 ["鹰","Eagle"],
 ["鸭子","Duck"],
 ["公鸡","Rooster"],
 ["绵羊","Sheep"],
 ["山羊","Goat"],
 ["奶牛","Cow"],
 ["马","Horse"],
 ["猪","Pig"],
 ["蝙蝠","Bat"],
 ["狼","Wolf"],
 ["熊","Bear"],
 ["梨","Pear"],
 ["橙子","Orange"],
 ["草莓","Strawberry"],
 ["西瓜","Watermelon"],
 ["葡萄","Grape"],
 ["香蕉","Banana"],
 ["桃子","Peach"],
 ["菠萝","Pineapple"],
 ["芒果","Mango"],
 ["椰子","Coconut"],
 ["牛油果","Avocado"],
 ["蓝莓","Blueberry"],
 ["石榴","Pomegranate"],
 ["荔枝","Lychee"],
 ["柚子","Pomelo"],
 ["南瓜","Pumpkin"],
 ["黄瓜","Cucumber"],
 ["胡萝卜","Carrot"],
 ["土豆","Potato"],
 ["番茄","Tomato"],
 ["洋葱","Onion"],
 ["大蒜","Garlic"],
 ["辣椒","Chili"],
 ["茄子","Eggplant"],
 ["玉米","Corn"],
 ["菠菜","Spinach"],
 ["白菜","Cabbage"],
 ["豌豆","Pea"],
 ["花生","Peanut"],
 ["核桃","Walnut"],
 ["米饭","Rice"],
 ["面条","Noodles"],
 ["饺子","Dumpling"],
 ["寿司","Sushi"],
 ["披萨","Pizza"],
 ["汉堡","Burger"],
 ["三明治","Sandwich"],
 ["饼干","Biscuit"],
 ["蛋糕","Cake"],
 ["布丁","Pudding"],
 ["酸奶","Yogurt"],
 ["牛奶","Milk"],
 ["黄油","Butter"],
 ["鸡蛋","Egg"],
 ["盐","Salt"],
 ["糖","Sugar"],
 ["醋","Vinegar"],
 ["学校","School"],
 ["银行","Bank"],
 ["市场","Market"],
 ["面包店","Bakery"],
 ["书店","Bookstore"],
 ["餐厅","Restaurant"],
 ["旅馆","Hotel"],
 ["工厂","Factory"],
 ["农场","Farm"],
 ["花园","Garden"],
 ["公园","Park"],
 ["操场","Playground"],
 ["体育馆","Stadium"],
 ["水族馆","Aquarium"],
 ["动物园","Zoo"],
 ["天文台","Observatory"],
 ["隧道","Tunnel"],
 ["码头","Pier"],
 ["广场","Square"],
 ["教堂","Church"],
 ["寺庙","Temple"],
 ["宫殿","Palace"],
 ["金字塔","Pyramid"],
 ["摩天楼","Skyscraper"],
 ["小屋","Cabin"],
 ["帐篷","Tent"],
 ["车库","Garage"],
 ["厨房","Kitchen"],
 ["阳台","Balcony"],
 ["屋顶","Roof"],
 ["楼梯","Staircase"],
 ["电梯","Elevator"],
 ["窗户","Window"],
 ["门铃","Doorbell"],
 ["烟囱","Chimney"],
 ["围栏","Fence"],
 ["喷泉","Fountain"],
 ["沙发","Sofa"],
 ["椅子","Chair"],
 ["桌子","Table"],
 ["书架","Bookshelf"],
 ["衣柜","Wardrobe"],
 ["床","Bed"],
 ["枕头","Pillow"],
 ["毯子","Blanket"],
 ["地毯","Carpet"],
 ["窗帘","Curtain"],
 ["牙刷","Toothbrush"],
 ["梳子","Comb"],
 ["肥皂","Soap"],
 ["毛巾","Towel"],
 ["浴缸","Bathtub"],
 ["水桶","Bucket"],
 ["扫帚","Broom"],
 ["拖把","Mop"],
 ["海绵","Sponge"],
 ["盘子","Plate"],
 ["碗","Bowl"],
 ["杯子","Cup"],
 ["筷子","Chopsticks"],
 ["叉子","Fork"],
 ["勺子","Spoon"],
 ["茶壶","Teapot"],
 ["烤箱","Oven"],
 ["冰箱","Refrigerator"],
 ["手表","Watch"],
 ["戒指","Ring"],
 ["项链","Necklace"],
 ["手套","Gloves"],
 ["围巾","Scarf"],
 ["帽子","Hat"],
 ["头盔","Helmet"],
 ["靴子","Boots"],
 ["凉鞋","Sandals"],
 ["袜子","Socks"],
 ["拉链","Zipper"],
 ["纽扣","Button"],
 ["口袋","Pocket"],
 ["钱包","Wallet"],
 ["背包","Backpack"],
 ["行李箱","Suitcase"],
 ["绳子","Rope"],
 ["梯子","Ladder"],
 ["锤子","Hammer"],
 ["钉子","Nail"],
 ["螺丝","Screw"],
 ["扳手","Wrench"],
 ["锯子","Saw"],
 ["针","Needle"],
 ["线轴","Spool"],
 ["铅笔","Pencil"],
 ["钢笔","Pen"],
 ["橡皮","Eraser"],
 ["尺子","Ruler"],
 ["笔记本","Notebook"],
 ["报纸","Newspaper"],
 ["日历","Calendar"],
 ["邮票","Stamp"],
 ["明信片","Postcard"],
 ["书签","Bookmark"],
 ["胶水","Glue"],
 ["胶带","Tape"],
 ["订书机","Stapler"],
 ["回形针","Paperclip"],
 ["黑板","Blackboard"],
 ["小提琴","Violin"],
 ["长笛","Flute"],
 ["小号","Trumpet"],
 ["口琴","Harmonica"],
 ["竖琴","Harp"],
 ["麦克风","Microphone"],
 ["耳机","Headphones"],
 ["音箱","Speaker"],
 ["唱片","Record"],
 ["面具","Mask"],
 ["木偶","Puppet"],
 ["魔术","Magic"],
 ["马戏团","Circus"],
 ["杂技","Acrobatics"],
 ["拼图","Jigsaw"],
 ["风筝","Kite"],
 ["秋千","Swing"],
 ["滑梯","Slide"],
 ["蹦床","Trampoline"],
 ["溜冰鞋","Skates"],
 ["滑板","Skateboard"],
 ["冲浪","Surfing"],
 ["攀岩","Climbing"],
 ["射箭","Archery"],
 ["羽毛球","Badminton"],
 ["排球","Volleyball"],
 ["保龄球","Bowling"],
 ["高尔夫","Golf"],
 ["奖杯","Trophy"],
 ["奖牌","Medal"],
 ["裁判","Referee"],
 ["护士","Nurse"],
 ["消防员","Firefighter"],
 ["理发师","Hairdresser"],
 ["记者","Reporter"],
 ["画家","Painter"],
 ["演员","Actor"],
 ["科学家","Scientist"],
 ["工程师","Engineer"],
 ["矿工","Miner"],
 ["水手","Sailor"],
 ["宇宙","Universe"],
 ["流星","Meteor"],
 ["日出","Sunrise"],
 ["日落","Sunset"],
 ["极光","Aurora"],
 ["潮汐","Tide"],
 ["海浪","Wave"],
 ["泥土","Soil"],
 ["石头","Stone"],
 ["沙子","Sand"],
 ["琥珀","Amber"],
 ["化石","Fossil"],
 ["水晶","Crystal"],
 ["露珠","Dew"],
 ["冰雹","Hail"],
 ["雪人","Snowman"],
 ["冰山","Iceberg"],
 ["绿洲","Oasis"],
 ["峡谷","Canyon"],
 ["草原","Grassland"],
 ["沼泽","Swamp"],
 ["玫瑰","Rose"],
 ["向日葵","Sunflower"],
 ["荷花","Lotus"],
 ["蒲公英","Dandelion"],
 ["仙人掌","Cactus"],
 ["棕榈","Palm"],
 ["枫树","Maple"],
 ["柳树","Willow"],
 ["苔藓","Moss"],
 ["蕨类","Fern"],
 ["树皮","Bark"],
 ["树桩","Stump"],
 ["花粉","Pollen"],
 ["花蜜","Nectar"],
 ["树脂","Resin"],
 ["氧气","Oxygen"],
 ["蒸汽","Steam"],
 ["烟雾","Smoke"],
 ["灰烬","Ash"],
 ["火焰","Flame"],
 ["气泡","Bubble"],
 ["回声","Echo"],
 ["节奏","Rhythm"],
 ["距离","Distance"],
 ["重量","Weight"],
 ["平衡","Balance"],
 ["方向","Direction"],
 ["力量","Strength"],
 ["能量","Energy"],
 ["勇气","Courage"],
 ["友谊","Friendship"],
 ["愿望","Wish"],
 ["谜语","Riddle"],
 ["笑话","Joke"],
 ["承诺","Promise"],
 ["礼物","Gift"],
 ["生日","Birthday"],
 ["婚礼","Wedding"],
 ["节日","Festival"],
 ["旅程","Journey"],
 ["冒险","Adventure"]
];
export const ODD_WORD_PAIRS:[[string,string],[string,string]][]=[
 [['咖啡','Coffee'],['茶','Tea']],[['猫','Cat'],['狗','Dog']],[['太阳','Sun'],['月亮','Moon']],[['苹果','Apple'],['梨','Pear']],[['火车','Train'],['地铁','Subway']],
 [['电影','Movie'],['电视剧','Television series']],[['雨伞','Umbrella'],['雨衣','Raincoat']],[['面包','Bread'],['蛋糕','Cake']],[['足球','Football'],['篮球','Basketball']],[['钢琴','Piano'],['吉他','Guitar']],
 [['海洋','Ocean'],['湖泊','Lake']],[['蜜蜂','Bee'],['蝴蝶','Butterfly']],[['冰箱','Refrigerator'],['空调','Air conditioner']],[['手机','Phone'],['平板电脑','Tablet']],[['医生','Doctor'],['护士','Nurse']],
 [['老师','Teacher'],['教练','Coach']],[['饺子','Dumpling'],['包子','Steamed bun']],[['牛奶','Milk'],['酸奶','Yogurt']],[['盐','Salt'],['糖','Sugar']],[['铅笔','Pencil'],['钢笔','Pen']],
 [['手套','Gloves'],['袜子','Socks']],[['狮子','Lion'],['老虎','Tiger']],[['海豚','Dolphin'],['鲸鱼','Whale']],[['兔子','Rabbit'],['仓鼠','Hamster']],[['森林','Forest'],['公园','Park']],
 [['沙漠','Desert'],['沙滩','Beach']],[['瀑布','Waterfall'],['喷泉','Fountain']],[['雪花','Snowflake'],['冰雹','Hail']],[['风筝','Kite'],['气球','Balloon']],[['蜡烛','Candle'],['手电筒','Flashlight']],
 [['镜子','Mirror'],['照片','Photograph']],[['书店','Bookstore'],['图书馆','Library']],[['宾馆','Hotel'],['民宿','Guesthouse']],[['机场','Airport'],['车站','Station']],[['桥梁','Bridge'],['隧道','Tunnel']],
 [['电梯','Elevator'],['楼梯','Staircase']],[['钥匙','Key'],['密码','Password']],[['时钟','Clock'],['手表','Watch']],[['钱包','Wallet'],['背包','Backpack']],[['帽子','Hat'],['头盔','Helmet']],
 [['泳池','Swimming pool'],['浴缸','Bathtub']],[['滑雪','Skiing'],['滑冰','Skating']],[['跑步','Running'],['散步','Walking']],[['唱歌','Singing'],['跳舞','Dancing']],[['画画','Drawing'],['摄影','Photography']],
 [['巧克力','Chocolate'],['糖果','Candy']],[['橙子','Orange'],['柠檬','Lemon']],[['西瓜','Watermelon'],['哈密瓜','Melon']],[['草莓','Strawberry'],['樱桃','Cherry']],[['土豆','Potato'],['红薯','Sweet potato']],
 [['洋葱','Onion'],['大蒜','Garlic']],[['黄瓜','Cucumber'],['西葫芦','Zucchini']],[['寿司','Sushi'],['饭团','Rice ball']],[['汉堡','Burger'],['三明治','Sandwich']],[['披萨','Pizza'],['馅饼','Pie']],
 [['公交车','Bus'],['出租车','Taxi']],[['自行车','Bicycle'],['摩托车','Motorcycle']],[['轮船','Ship'],['帆船','Sailboat']],[['火箭','Rocket'],['飞机','Airplane']],[['卫星','Satellite'],['空间站','Space station']],
 [['国王','King'],['王子','Prince']],[['王冠','Crown'],['奖杯','Trophy']],[['宝石','Gem'],['珍珠','Pearl']],[['黄金','Gold'],['白银','Silver']],[['长剑','Sword'],['弓箭','Bow']],
 [['帐篷','Tent'],['小屋','Cabin']],[['地图','Map'],['指南针','Compass']],[['望远镜','Telescope'],['显微镜','Microscope']],[['相机','Camera'],['摄像机','Video camera']],[['耳机','Headphones'],['音箱','Speaker']],
 [['春天','Spring'],['秋天','Autumn']],[['夏天','Summer'],['冬天','Winter']],[['日出','Sunrise'],['日落','Sunset']],[['雷声','Thunder'],['闪电','Lightning']],[['彩虹','Rainbow'],['极光','Aurora']],
 [['围巾','Scarf'],['领带','Tie']],[['西装','Suit'],['礼服','Gown']],[['凉鞋','Sandals'],['拖鞋','Slippers']],[['筷子','Chopsticks'],['叉子','Fork']],[['盘子','Plate'],['碗','Bowl']],
 [["大象","Elephant"],["犀牛","Rhinoceros"]],
 [["长颈鹿","Giraffe"],["骆驼","Camel"]],
 [["斑马","Zebra"],["马","Horse"]],
 [["山羊","Goat"],["绵羊","Sheep"]],
 [["鸭子","Duck"],["鹅","Goose"]],
 [["公鸡","Rooster"],["孔雀","Peacock"]],
 [["鹦鹉","Parrot"],["鸽子","Pigeon"]],
 [["猫头鹰","Owl"],["鹰","Eagle"]],
 [["企鹅","Penguin"],["海豹","Seal"]],
 [["鲨鱼","Shark"],["鳄鱼","Crocodile"]],
 [["章鱼","Octopus"],["鱿鱼","Squid"]],
 [["螃蟹","Crab"],["龙虾","Lobster"]],
 [["海星","Starfish"],["水母","Jellyfish"]],
 [["蜗牛","Snail"],["乌龟","Turtle"]],
 [["蚂蚁","Ant"],["蜜蜂","Bee"]],
 [["蜻蜓","Dragonfly"],["蚊子","Mosquito"]],
 [["萤火虫","Firefly"],["瓢虫","Ladybird"]],
 [["青蛙","Frog"],["蟾蜍","Toad"]],
 [["蛇","Snake"],["蜥蜴","Lizard"]],
 [["狐狸","Fox"],["狼","Wolf"]],
 [["松鼠","Squirrel"],["仓鼠","Hamster"]],
 [["刺猬","Hedgehog"],["豪猪","Porcupine"]],
 [["熊猫","Panda"],["北极熊","Polar bear"]],
 [["袋鼠","Kangaroo"],["兔子","Rabbit"]],
 [["水獭","Otter"],["海狸","Beaver"]],
 [["桃子","Peach"],["杏子","Apricot"]],
 [["葡萄","Grape"],["蓝莓","Blueberry"]],
 [["菠萝","Pineapple"],["芒果","Mango"]],
 [["椰子","Coconut"],["核桃","Walnut"]],
 [["荔枝","Lychee"],["龙眼","Longan"]],
 [["柚子","Pomelo"],["橙子","Orange"]],
 [["香蕉","Banana"],["芭蕉","Plantain"]],
 [["南瓜","Pumpkin"],["冬瓜","Winter melon"]],
 [["白菜","Cabbage"],["生菜","Lettuce"]],
 [["菠菜","Spinach"],["芹菜","Celery"]],
 [["胡萝卜","Carrot"],["白萝卜","Daikon"]],
 [["番茄","Tomato"],["彩椒","Bell pepper"]],
 [["花生","Peanut"],["瓜子","Sunflower seeds"]],
 [["豌豆","Pea"],["毛豆","Edamame"]],
 [["玉米","Corn"],["小麦","Wheat"]],
 [["米饭","Rice"],["粥","Rice porridge"]],
 [["面条","Noodles"],["粉丝","Glass noodles"]],
 [["馄饨","Wonton"],["饺子","Dumpling"]],
 [["馒头","Steamed bread"],["包子","Steamed bun"]],
 [["春卷","Spring roll"],["蛋卷","Egg roll"]],
 [["豆腐","Tofu"],["奶酪","Cheese"]],
 [["煎蛋","Fried egg"],["煮蛋","Boiled egg"]],
 [["培根","Bacon"],["火腿","Ham"]],
 [["牛排","Steak"],["猪排","Pork chop"]],
 [["烤鸡","Roast chicken"],["炸鸡","Fried chicken"]],
 [["果汁","Fruit juice"],["汽水","Soda"]],
 [["奶茶","Milk tea"],["可可","Cocoa"]],
 [["冰淇淋","Ice cream"],["冰棒","Ice pop"]],
 [["布丁","Pudding"],["果冻","Jelly"]],
 [["饼干","Biscuit"],["威化饼","Wafer"]],
 [["蜂蜜","Honey"],["糖浆","Syrup"]],
 [["黄油","Butter"],["奶油","Cream"]],
 [["醋","Vinegar"],["酱油","Soy sauce"]],
 [["芥末","Mustard"],["辣椒酱","Chili sauce"]],
 [["葡萄干","Raisin"],["红枣","Jujube"]],
 [["沙发","Sofa"],["椅子","Chair"]],
 [["书架","Bookshelf"],["衣柜","Wardrobe"]],
 [["枕头","Pillow"],["靠垫","Cushion"]],
 [["被子","Quilt"],["毯子","Blanket"]],
 [["地毯","Carpet"],["地垫","Doormat"]],
 [["窗帘","Curtain"],["百叶窗","Blinds"]],
 [["台灯","Desk lamp"],["吊灯","Pendant light"]],
 [["扫帚","Broom"],["拖把","Mop"]],
 [["吸尘器","Vacuum cleaner"],["扫地机器人","Robot vacuum"]],
 [["肥皂","Soap"],["沐浴露","Shower gel"]],
 [["洗发水","Shampoo"],["护发素","Conditioner"]],
 [["牙刷","Toothbrush"],["牙线","Dental floss"]],
 [["浴巾","Bath towel"],["浴袍","Bathrobe"]],
 [["梳子","Comb"],["发刷","Hairbrush"]],
 [["水桶","Bucket"],["脸盆","Washbasin"]],
 [["茶壶","Teapot"],["水壶","Kettle"]],
 [["杯子","Cup"],["马克杯","Mug"]],
 [["平底锅","Frying pan"],["炒锅","Wok"]],
 [["烤箱","Oven"],["微波炉","Microwave"]],
 [["冰柜","Freezer"],["冰箱","Refrigerator"]],
 [["电风扇","Electric fan"],["空调","Air conditioner"]],
 [["洗衣机","Washing machine"],["烘干机","Tumble dryer"]],
 [["洗碗机","Dishwasher"],["消毒柜","Sterilizing cabinet"]],
 [["保温杯","Vacuum flask"],["热水袋","Hot water bottle"]],
 [["围裙","Apron"],["厨师服","Chef jacket"]],
 [["锤子","Hammer"],["扳手","Wrench"]],
 [["钉子","Nail"],["螺丝","Screw"]],
 [["绳子","Rope"],["链条","Chain"]],
 [["针","Needle"],["别针","Safety pin"]],
 [["胶水","Glue"],["胶带","Tape"]],
 [["订书机","Stapler"],["回形针","Paperclip"]],
 [["橡皮","Eraser"],["修正带","Correction tape"]],
 [["尺子","Ruler"],["卷尺","Tape measure"]],
 [["黑板","Blackboard"],["白板","Whiteboard"]],
 [["粉笔","Chalk"],["蜡笔","Crayon"]],
 [["报纸","Newspaper"],["杂志","Magazine"]],
 [["小说","Novel"],["漫画","Comic book"]],
 [["日记","Diary"],["笔记","Notes"]],
 [["明信片","Postcard"],["信件","Letter"]],
 [["邮票","Stamp"],["贴纸","Sticker"]],
 [["日历","Calendar"],["课程表","Timetable"]],
 [["书签","Bookmark"],["便签","Sticky note"]],
 [["奖杯","Trophy"],["奖牌","Medal"]],
 [["戒指","Ring"],["手镯","Bracelet"]],
 [["项链","Necklace"],["耳环","Earrings"]],
 [["靴子","Boots"],["运动鞋","Sneakers"]],
 [["雨鞋","Rain boots"],["登山鞋","Hiking boots"]],
 [["衬衫","Shirt"],["T恤","T-shirt"]],
 [["毛衣","Sweater"],["卫衣","Hoodie"]],
 [["外套","Coat"],["夹克","Jacket"]],
 [["牛仔裤","Jeans"],["运动裤","Track pants"]],
 [["皮带","Belt"],["背带","Suspenders"]],
 [["拉链","Zipper"],["纽扣","Button"]],
 [["眼镜","Glasses"],["墨镜","Sunglasses"]],
 [["口罩","Face mask"],["面具","Mask"]],
 [["行李箱","Suitcase"],["旅行包","Travel bag"]],
 [["学校","School"],["大学","University"]],
 [["餐厅","Restaurant"],["食堂","Cafeteria"]],
 [["超市","Supermarket"],["菜市场","Food market"]],
 [["面包店","Bakery"],["甜品店","Dessert shop"]],
 [["动物园","Zoo"],["水族馆","Aquarium"]],
 [["游乐园","Amusement park"],["马戏团","Circus"]],
 [["体育馆","Stadium"],["健身房","Gym"]],
 [["银行","Bank"],["邮局","Post office"]],
 [["城堡","Castle"],["宫殿","Palace"]],
 [["教堂","Church"],["寺庙","Temple"]],
 [["花园","Garden"],["果园","Orchard"]],
 [["农场","Farm"],["牧场","Ranch"]],
 [["阳台","Balcony"],["露台","Terrace"]],
 [["屋顶","Roof"],["天花板","Ceiling"]],
 [["门铃","Doorbell"],["电话铃","Phone ring"]],
 [["围栏","Fence"],["城墙","City wall"]],
 [["高速公路","Highway"],["铁路","Railway"]],
 [["十字路口","Intersection"],["环岛","Roundabout"]],
 [["红绿灯","Traffic lights"],["路灯","Streetlight"]],
 [["消防车","Fire engine"],["救护车","Ambulance"]],
 [["挖掘机","Excavator"],["推土机","Bulldozer"]],
 [["缆车","Cable car"],["摩天轮","Ferris wheel"]],
 [["直升机","Helicopter"],["无人机","Drone"]],
 [["航空母舰","Aircraft carrier"],["战列舰","Battleship"]],
 [["独木舟","Canoe"],["皮划艇","Kayak"]],
 [["轮滑","Roller skating"],["滑板运动","Skateboarding"]],
 [["冲浪","Surfing"],["帆板","Windsurfing"]],
 [["跳绳","Skipping rope"],["跳高","High jump"]],
 [["乒乓球","Table tennis"],["羽毛球","Badminton"]],
 [["排球","Volleyball"],["沙滩排球","Beach volleyball"]],
 [["保龄球","Bowling"],["台球","Billiards"]],
 [["高尔夫","Golf"],["曲棍球","Hockey"]],
 [["举重","Weightlifting"],["健美","Bodybuilding"]],
 [["射箭","Archery"],["飞镖","Darts"]],
 [["攀岩","Climbing"],["登山","Mountaineering"]],
 [["小提琴","Violin"],["大提琴","Cello"]],
 [["长笛","Flute"],["竖笛","Recorder"]],
 [["小号","Trumpet"],["长号","Trombone"]],
 [["口琴","Harmonica"],["手风琴","Accordion"]],
 [["歌剧","Opera"],["音乐剧","Musical"]],
 [["木偶","Puppet"],["玩偶","Doll"]],
 [["魔术","Magic"],["杂技","Acrobatics"]],
 [["拼图","Jigsaw"],["积木","Building blocks"]],
 [["秋千","Swing"],["摇椅","Rocking chair"]],
 [["陀螺","Spinning top"],["悠悠球","Yo-yo"]],
 [["象棋","Chess"],["跳棋","Checkers"]],
 [["扑克","Playing cards"],["麻将","Mahjong"]],
 [["医生","Doctor"],["兽医","Veterinarian"]],
 [["消防员","Firefighter"],["警察","Police officer"]],
 [["记者","Reporter"],["主播","News anchor"]],
 [["画家","Painter"],["雕塑家","Sculptor"]],
 [["演员","Actor"],["导演","Director"]],
 [["理发师","Hairdresser"],["化妆师","Makeup artist"]],
 [["厨师","Chef"],["烘焙师","Baker"]],
 [["农夫","Farmer"],["渔夫","Fisher"]],
 [["木匠","Carpenter"],["铁匠","Blacksmith"]],
 [["科学家","Scientist"],["工程师","Engineer"]],
 [["沙丘","Sand dune"],["雪堆","Snowdrift"]],
 [["火山","Volcano"],["温泉","Hot spring"]],
 [["冰山","Iceberg"],["冰川","Glacier"]],
 [["峡谷","Canyon"],["山谷","Valley"]],
 [["沼泽","Swamp"],["湿地","Wetland"]],
 [["海浪","Wave"],["潮汐","Tide"]],
 [["露珠","Dew"],["霜","Frost"]],
 [["云","Cloud"],["雾","Fog"]],
 [["台风","Typhoon"],["龙卷风","Tornado"]],
 [["流星","Meteor"],["彗星","Comet"]],
 [["月食","Lunar eclipse"],["日食","Solar eclipse"]],
 [["玫瑰","Rose"],["牡丹","Peony"]],
 [["向日葵","Sunflower"],["菊花","Chrysanthemum"]],
 [["荷花","Lotus"],["睡莲","Water lily"]],
 [["仙人掌","Cactus"],["芦荟","Aloe"]],
 [["枫树","Maple"],["银杏","Ginkgo"]],
 [["柳树","Willow"],["白杨","Poplar"]],
 [["苔藓","Moss"],["蕨类","Fern"]],
 [["树枝","Branch"],["树根","Root"]],
 [["花粉","Pollen"],["花蜜","Nectar"]],
 [["石头","Stone"],["砖头","Brick"]],
 [["水晶","Crystal"],["玻璃","Glass"]],
 [["琥珀","Amber"],["化石","Fossil"]],
 [["烟雾","Smoke"],["蒸汽","Steam"]],
 [["回声","Echo"],["录音","Recording"]],
 [["梦境","Dream"],["幻想","Fantasy"]],
 [["记忆","Memory"],["想象","Imagination"]],
 [["秘密","Secret"],["谜语","Riddle"]],
 [["礼物","Gift"],["奖品","Prize"]],
 [["生日","Birthday"],["纪念日","Anniversary"]],
 [["婚礼","Wedding"],["生日会","Birthday party"]],
 [["旅行","Travel"],["露营","Camping"]],
 [["地图","Map"],["地球仪","Globe"]],
 [["指南针","Compass"],["导航仪","Navigator"]]
];
export const localWord=(pair:[string,string],language:WordLanguage)=>pair[language==='en'?1:0];
