import { useEffect, useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowLeft, Check, ChevronRight, Cloud, Copy, Crown, Gamepad2, HelpCircle, History, LogOut, Maximize2, Plus, Radio, RefreshCw, RotateCcw, Settings2, Share2, Smartphone, Users, Wifi, X } from 'lucide-react';
import { AVATARS, GAMES, type Action, type Command, type GameKind, type GameOptions, type Player } from '../core/types';
import { modules } from '../core/registry';
import { roomLimits, RoomClient, type ClientState, type RoomCandidate, type RoomMode } from '../net/client';
import { ActionDock, ActionSheet } from './Boards';
import { GemsTable } from './GemsTable';
import { BombsTable } from './BombsTable';
import { SocialTable } from './SocialTable';
import { InstallButton } from './InstallButton';

const client=new RoomClient();
const kinds=Object.keys(GAMES) as GameKind[];
function readProfile():Player|null {try{const p=JSON.parse(localStorage.getItem('mocha-profile')||'null');return p&&typeof p.id==='string'&&p.name&&AVATARS.includes(p.avatar)?p:null;}catch{return null;}}
type Practice={id:string;kind:GameKind;players:Player[];game:any;viewer:string;options?:GameOptions};
type Sheet='profile'|'join'|'nearby'|'help'|'log'|'menu'|null;
const RULES:Record<GameKind,string[]>={
  gems:['每回合选择一项：拿 3 种不同宝石、拿 2 枚同色宝石（供应至少 4 枚）、购买或预留一张牌。','购买的牌提供永久同色折扣。黄金可替代任意颜色。预留上限 3 张，预留时若有黄金可拿 1 枚。','筹码总数不能超过 10；满足贵族条件时获得 3 分。有人达到 15 分后完成本轮，总分最高者胜；同分时购牌更少者胜。'],
  bombs:['每回合可以出牌，最后抽一张牌结束回合。抽到炸弹且没有拆弹牌就出局，最后一位存活者获胜。','点选一张功能牌出牌；两张同名牌可随机偷牌，三张同名牌可指定牌名。否决在效果响应阶段使用，所有人点“继续”后结算。','拆弹后秘密选择放回位置。攻击把回合交给下家；处于攻击中时再次攻击会叠加回合。跳过只结束一个回合。'],
  werewolf:['法官主持：房主为法官，不参与发牌；玩家只看身份，法官记录现场操作。只发身份：6–18 人发牌后线下进行，房主可确认重新发牌。','玩家操作模式支持 6–18 人。狼人约占三分之一；含预言家、女巫，8 人起加入猎人，12 人起加入守卫，其余为村民。','第一夜行动后进行警长竞选，再公布死讯。大家面对面发言，轮到自己的手机操作时再选择。秘密角色信息只发送给本人。','狼人击杀、预言家查验；女巫不可自救，同夜不能用两瓶药；守卫不能连续守同一人。同守同救会死亡，被毒死的猎人不能开枪。','好人消灭全部狼人获胜；狼人消灭所有村民或所有神职获胜。支持退水、平票 PK、警长 1.5 票、警徽流转与自爆。'],
  avalon:['支持 5–10 人。队长提名远征队，所有玩家同时表决，过半赞成才能出发。连续 5 次组队被拒，邪恶获胜。','队员秘密提交任务牌；好人只能成功，邪恶可选失败。通常一张失败牌使任务失败，7 人以上第 4 次远征需要两张失败牌。','邪恶赢得 3 次任务即获胜。好人赢得 3 次后，刺客仍有一次刺杀梅林的机会。身份卡可查看你知道的其他玩家信息。']
};
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}) {return <div className="modal-shade" onClick={onClose}><section className={`panel ${wide?'wide':''}`} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button className="icon" aria-label="关闭" onClick={onClose}><X/></button></header>{children}</section></div>;}
export function App(){
  const [profile,setProfile]=useState<Player|null>(readProfile),[state,setState]=useState<ClientState>(client.state),[selectedGame,setSelectedGame]=useState<GameKind|null>(null),[sheet,setSheet]=useState<Sheet>(null),[mode,setMode]=useState<RoomMode>('lan'),[practice,setPractice]=useState<Practice|null>(null),[action,setAction]=useState<{a:Action;values:string[]}|null>(null),[message,setMessage]=useState(''),[rooms,setRooms]=useState<RoomCandidate[]>([]),[finding,setFinding]=useState(false),[code,setCode]=useState(''),[name,setName]=useState(profile?.name||''),[avatar,setAvatar]=useState(profile?.avatar||AVATARS[0]),[portraitOK,setPortraitOK]=useState(false),[wolfMode,setWolfMode]=useState<NonNullable<GameOptions['werewolfMode']>>('judge');
  const room=state.room,kind=practice?.kind||room?.kind||selectedGame;
  const view=practice?modules[practice.kind].view(practice.game,practice.viewer):state.view;
  const selfID=practice?.viewer||state.selfID||profile?.id||'';
  const host=room?.hostID===selfID;
  const limits=room?roomLimits(room.kind,room.options):null;
  const wolfLabels={standard:'玩家操作',judge:'法官主持',deal:'只发身份'};
  const gameOptions=(k:GameKind,hostID?:string):GameOptions|undefined=>k==='werewolf'?{werewolfMode:wolfMode,...(hostID&&wolfMode!=='standard'?{moderatorID:hostID}:{})}:undefined;
  useEffect(()=>client.subscribe(setState),[]);
  useEffect(()=>{const u=new URL(location.href);const roomCode=u.searchParams.get('room');if(roomCode){setCode(roomCode);setSheet('join');}else void client.connect();},[]);
  useEffect(()=>{setAction(null);},[view?.kind,view?.phase,selfID]);
  useEffect(()=>{if(message){const timer=setTimeout(()=>setMessage(''),4000);return()=>clearTimeout(timer);}},[message]);
  const notify=(s:string)=>setMessage(s);
  const saveProfile=()=>{if(!name.trim()){notify('取个名字，再入座');return;}const p={id:profile?.id||crypto.randomUUID(),name:name.trim().slice(0,16),avatar};try{localStorage.setItem('mocha-profile',JSON.stringify(p));setProfile(p);setSheet(null);}catch{notify('无法保存身份，请允许浏览器存储');}};
  const run=(cmd:Command)=>{if(practice){try{setPractice({...practice,game:modules[practice.kind].apply(practice.game,practice.viewer,cmd)});}catch(e){notify((e as Error).message);throw e;}}else client.action(cmd);};
  const openAction=(a:Action,values:string[]=[])=>setAction({a,values});
  const startPractice=(k:GameKind)=>{const count=k==='werewolf'?(wolfMode==='judge'?10:9):k==='avalon'?5:k==='bombs'?3:2;const players=Array.from({length:count},(_,i)=>({id:`practice-${i}`,name:i===0?profile!.name:['','阿岚','小雨','阿七','橘子','小白','阿木','南风','夏天'][i]||`玩家${i+1}`,avatar:i===0?profile!.avatar:AVATARS[i]}));setPractice({id:crypto.randomUUID(),kind:k,players,game:modules[k].create(players,crypto.getRandomValues(new Uint32Array(1))[0],gameOptions(k,players[0].id)),viewer:players[0].id,options:gameOptions(k,players[0].id)});setSelectedGame(null);};
  const findRooms=async()=>{setSheet('nearby');setFinding(true);setRooms(await client.discover());setFinding(false);};
  const join=(c=code)=>{if(!profile)return;const invite=new URLSearchParams(location.hash.slice(1)).get('invite')||undefined;void client.join(profile,c,invite);setSheet(null);setSelectedGame(null);};
  const share=async()=>{const url=state.inviteURL||`${location.origin}/?room=${room?.code}`;try{if(navigator.share)await navigator.share({title:'Mocha 桌游',text:`来玩${GAMES[room!.kind].name}`,url});else{await navigator.clipboard.writeText(url);notify('邀请链接已复制');}}catch(e){if((e as Error).name!=='AbortError')notify('请分享房间码：'+room?.code);}};
  const fullscreen=()=>{const el=document.documentElement as HTMLElement&{webkitRequestFullscreen?:()=>Promise<void>};void(el.requestFullscreen?.()||el.webkitRequestFullscreen?.())?.catch(()=>{});};
  const leave=()=>{if(practice){setPractice(null);setSheet(null);return;}client.leave();setSheet(null);};
  const usableRoom=room&&state.status!=='idle';
  return <main className={`app ${view?'in-game':''} game-${kind||'home'}`} style={{'--accent':kind?GAMES[kind].color:'#d8c291'} as CSSProperties}>
    <header className="topbar"><div className="brand">{view||usableRoom||selectedGame?<button className="icon" aria-label="牌桌菜单" onClick={()=>view||usableRoom?setSheet('menu'):setSelectedGame(null)}><ArrowLeft size={19}/></button>:<img className="brand-mark brand-image" src="/mocha-icon-180.png" alt=""/>}<div><b>{kind?GAMES[kind].name:'Mocha 桌游'}</b><small>{view?view.phase:usableRoom?`房间 ${room.code}`:''}</small></div></div><div className="top-tools">{practice?<label className="practice-switch"><span>同屏试玩</span><select aria-label="切换试玩座位" value={practice.viewer} onChange={e=>setPractice({...practice,viewer:e.target.value})}>{practice.players.map(p=><option value={p.id} key={p.id}>{p.avatar} {p.name}{modules[practice.kind].view(practice.game,p.id).actions.length?' · 待操作':''}</option>)}</select></label>:usableRoom?<span className={`connection ${state.paused?'bad':''}`}>{state.transport==='lan'?<Wifi size={14}/>:<Cloud size={14}/>}<span>{state.mode==='lan'?(state.transport==='lan'?'Wi-Fi 直连':'直连建立中'):'云端联机'}</span></span>:<button className="compact glass" onClick={()=>setSheet('join')}><Users size={15}/>加入牌桌</button>}<button className="icon" aria-label="玩法和安装帮助" onClick={()=>setSheet('help')}><HelpCircle size={18}/></button>{view&&<button className="icon" aria-label="对局记录" onClick={()=>setSheet('log')}><History size={18}/></button>}<button className="profile-chip" aria-label="修改昵称头像" onClick={()=>{setName(profile?.name||'');setAvatar(profile?.avatar||AVATARS[0]);setSheet('profile');}}>{profile?.avatar||'＋'}<span>{profile?.name||'入座'}</span></button></div></header>
    {!view&&!usableRoom&&<><section className="game-library">{kinds.map((k,i)=><button key={k} className={`game-cover cover-${k} ${selectedGame===k?'chosen':''}`} aria-label={`选择${GAMES[k].name}`} onClick={()=>setSelectedGame(k)} style={{'--accent':GAMES[k].color} as CSSProperties}><img src={`/art/${k}.jpg`} alt=""/><span className="cover-index">0{i+1}</span><span className="cover-caption"><small>{k==='gems'?'策略 · 收集':k==='bombs'?'欢乐 · 生存':k==='werewolf'?'推理 · 伪装':'阵营 · 博弈'}</small><strong>{GAMES[k].name}</strong><span>{GAMES[k].min}–{GAMES[k].max} 人 <ChevronRight size={17}/></span></span></button>)}</section><footer className="home-footer"><InstallButton/><button className="text-button" onClick={()=>void findRooms()}><Radio size={15}/>发现附近牌桌</button></footer></>}
    {usableRoom&&!view&&<section className="lobby"><div className="lobby-art"><img src={`/art/${room.kind}.jpg`} alt=""/><div><h1>{GAMES[room.kind].name}</h1><span>{limits!.min}–{limits!.max} 人{room.kind==='werewolf'?` · ${wolfLabels[room.options?.werewolfMode||'standard']}`:''} · {room.mode==='lan'?'同 Wi-Fi 直连':'云端联机'}</span></div></div><div className="lobby-content"><div className="lobby-heading"><div><small>邀请朋友入座</small><button className="room-code" aria-label="复制房间码" onClick={()=>void navigator.clipboard?.writeText(room.code).then(()=>notify('房间码已复制')).catch(()=>notify(room.code))}>{room.code}<Copy size={14}/></button></div><button className="compact glass" onClick={()=>void share()}><Share2 size={15}/>邀请</button></div><div className="lobby-seats">{room.players.map(p=><div className={`lobby-seat ${p.ready?'ready':''}`} key={p.id}><span>{p.avatar}</span><b>{p.name}{p.id===room.hostID&&<Crown size={13}/>}</b><small>{!p.connected?'离线':p.id===room.hostID?(room.options?.werewolfMode==='judge'?'法官 · 房主':'房主'):p.ready?'已准备':'等待准备'}</small></div>)}{room.players.length<limits!.max&&<button className="lobby-seat vacant" onClick={()=>void share()}><Plus size={24}/><small>等你入座</small></button>}</div>{room.pending.length>0&&host&&<div className="join-requests">{room.pending.map(p=><div key={p.id}><span>{p.avatar} {p.name} 想入座</span><button className="icon" aria-label={`拒绝${p.name}`} onClick={()=>client.approve(p.id,false)}><X size={16}/></button><button className="icon approve" aria-label={`同意${p.name}`} onClick={()=>client.approve(p.id,true)}><Check size={16}/></button></div>)}</div>}<footer className="lobby-controls">{host?<><select aria-label="更换游戏" value={room.kind} onChange={e=>client.selectGame(e.target.value as GameKind,gameOptions(e.target.value as GameKind))}>{kinds.map(k=><option key={k} value={k}>{GAMES[k].name}</option>)}</select>{room.kind==='werewolf'&&<select className="lobby-mode" aria-label="狼人杀模式" value={room.options?.werewolfMode||'standard'} onChange={e=>client.selectGame('werewolf',{werewolfMode:e.target.value as GameOptions['werewolfMode']})}>{Object.entries(wolfLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>}<button className="compact primary" disabled={room.players.length<limits!.min||room.players.some(p=>p.id!==room.hostID&&!p.ready)||state.mode==='lan'&&state.transport!=='lan'} onClick={()=>client.start()}>开局<ChevronRight size={16}/></button></>:<button className="compact primary" onClick={()=>client.ready(!room.players.find(p=>p.id===selfID)?.ready)}>{room.players.find(p=>p.id===selfID)?.ready?'取消准备':'准备好了'}<Check size={16}/></button>}{host&&room.mode==='lan'&&<button className="text-button" onClick={()=>client.switchToCloud()}><Cloud size={14}/>改用云端</button>}</footer></div></section>}
    {view&&<><div className="game-surface">{view.kind==='gems'?<GemsTable view={view} selfID={selfID} command={run} open={openAction}/>:view.kind==='bombs'?<BombsTable view={view} selfID={selfID} command={run} open={openAction}/>:<SocialTable key={practice?.id||room?.code} view={view} selfID={selfID} command={run} open={openAction}/>}</div>{view.kind!=='bombs'&&<ActionDock view={view} command={run} open={openAction}/>}{view.finished&&<div className="end-banner"><Crown size={23}/><b>{view.instruction==='本局结束'?view.board.winner:view.instruction}</b>{practice?<button className="compact primary" onClick={()=>startPractice(practice.kind)}>再来一局</button>:host?<button className="compact primary" onClick={()=>client.replay()}>返回准备</button>:<small>等待房主再开一局</small>}</div>}</>}
    {state.status==='connecting'&&!room&&!practice&&<div className="connecting-overlay"><div className="spinner"/><h2>{state.waitingApproval?'等待房主同意':'正在寻找牌桌'}</h2><button className="text-button" onClick={()=>client.leave()}>取消</button></div>}
    {state.paused&&view&&!practice&&<div className="pause-overlay"><Cloud size={28}/><b>连接恢复后，继续这一局</b><div className="inline-actions"><button className="compact primary" onClick={()=>void client.connect()}><RefreshCw size={15}/>重连</button>{host&&state.mode==='lan'&&<button className="compact" onClick={()=>client.switchToCloud()}>切换云端</button>}<button className="compact" onClick={()=>setSheet('menu')}>牌桌菜单</button></div></div>}
    {selectedGame&&!room&&!practice&&<Modal title={GAMES[selectedGame].name} onClose={()=>setSelectedGame(null)}><div className="create-body">{selectedGame==='werewolf'&&<><div className="wolf-mode-picker">{Object.entries(wolfLabels).map(([v,label])=><button key={v} className={wolfMode===v?'selected':''} onClick={()=>setWolfMode(v as NonNullable<GameOptions['werewolfMode']>)}><b>{label}</b><small>{v==='judge'?'1 法官 + 6–18 玩家':v==='deal'?'6–18 玩家':'6–18 玩家'}</small></button>)}</div><p className="wolf-mode-description">{wolfMode==='judge'?'房主担任法官，统一记录技能、死讯和现场投票；玩家只看身份。':wolfMode==='deal'?'随机发身份牌，之后完全线下主持；房主也参与游戏。':'每位玩家在自己的手机上执行技能和投票。'}</p></>}<div className="mode-picker"><button className={mode==='lan'?'selected':''} onClick={()=>setMode('lan')}><Wifi size={23}/><b>同 Wi-Fi</b><small>云端配对 · 手机直连</small></button><button className={mode==='cloud'?'selected':''} onClick={()=>setMode('cloud')}><Cloud size={23}/><b>云端联机</b><small>不同网络，也能同桌</small></button></div><footer><button className="text-button" onClick={()=>startPractice(selectedGame)}><Gamepad2 size={15}/>同屏试玩</button><button className="compact primary" onClick={()=>{void client.create(profile!,selectedGame,mode,gameOptions(selectedGame));setSelectedGame(null);}}>创建牌桌<ChevronRight size={16}/></button></footer></div></Modal>}
    {(!profile||sheet==='profile')&&<Modal title="先认识一下" onClose={()=>{if(profile)setSheet(null);}}><div className="profile-editor"><div className="avatar-preview">{avatar}</div><label>朋友怎么称呼你<input autoComplete="nickname" maxLength={16} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&saveProfile()} placeholder="你的昵称" autoFocus/></label><div className="avatar-grid">{AVATARS.map(a=><button key={a} aria-label={`选择头像${a}`} className={a===avatar?'selected':''} onClick={()=>setAvatar(a)}>{a}</button>)}</div><footer><small>保存在这台手机，无需登录</small><button className="compact primary" disabled={!name.trim()} onClick={saveProfile}>入座<ChevronRight size={16}/></button></footer></div></Modal>}
    {sheet==='join'&&profile&&<Modal title="加入朋友的牌桌" onClose={()=>setSheet(null)}><form className="join-form" onSubmit={e=>{e.preventDefault();join();}}><label>六位房间码<input aria-label="房间码" className="code-input" autoCapitalize="characters" autoComplete="off" maxLength={6} placeholder="ABC234" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/></label><footer><button type="button" className="text-button" onClick={()=>void findRooms()}><Radio size={15}/>发现附近</button><button className="compact primary" disabled={code.length!==6}>入桌<ChevronRight size={16}/></button></footer></form></Modal>}
    {sheet==='nearby'&&<Modal title="附近的牌桌" onClose={()=>setSheet(null)}><p className="panel-note">按网络出口寻找候选牌桌；入桌需房主同意。</p><div className="nearby-list">{finding?<div className="empty-state"><div className="spinner"/>寻找中</div>:rooms.length?rooms.map(r=><button key={r.code} onClick={()=>join(r.code)}><img src={`/art/${r.kind}.jpg`} alt=""/><span><b>{r.hostName} 的牌桌</b><small>{GAMES[r.kind].name} · {r.count}/{r.max} 人 · {r.mode==='lan'?'Wi-Fi':'云端'}</small></span><ChevronRight size={18}/></button>):<div className="empty-state"><Radio size={28}/><p>附近还没有开桌</p><small>也可以让朋友分享六位房间码</small></div>}</div><footer><button className="text-button" onClick={()=>setSheet('join')}>输入房间码</button><button className="compact" disabled={finding} onClick={()=>void findRooms()}><RefreshCw size={14}/>刷新</button></footer></Modal>}
    {sheet==='help'&&<Modal title={kind?`${GAMES[kind].name} · 玩法`:'使用帮助'} onClose={()=>setSheet(null)} wide><div className="help-content">{kind?<ol>{RULES[kind].map(line=><li key={line}>{line}</li>)}</ol>:<><h3>装进 iPhone 主屏幕</h3><p>用 Safari 打开，点“分享”→“添加到主屏幕”，再从桌面图标进入。</p><h3>和朋友联机</h3><p>创建牌桌后分享邀请链接，或让朋友输入房间码。同 Wi-Fi 模式先联网配对，再直接传输游戏操作；直连失败时房主可改用云端。</p><h3>附近牌桌与离线</h3><p>附近列表依据网络出口，不能保证确实处于同一 Wi-Fi。页面资源缓存完成后，同屏试玩可离线使用；联机建房仍需联网。</p></>}<button className="text-button" onClick={fullscreen}><Maximize2 size={15}/>尝试全屏</button></div></Modal>}
    {sheet==='log'&&view&&<Modal title="对局记录" onClose={()=>setSheet(null)}><ol className="game-log">{view.log.slice().reverse().map((line,i)=><li key={i}>{line}</li>)}</ol></Modal>}
    {sheet==='menu'&&<Modal title="牌桌菜单" onClose={()=>setSheet(null)}><div className="menu-list">{!practice&&<button onClick={()=>void share()}><Share2 size={18}/>分享邀请<ChevronRight size={16}/></button>}{host&&state.mode==='lan'&&<button onClick={()=>{client.switchToCloud();setSheet(null);}}><Cloud size={18}/>切换云端联机<ChevronRight size={16}/></button>}{host&&room?.started&&<button onClick={()=>{if(window.confirm('结束当前对局，所有玩家返回准备？')){client.endGame();setSheet(null);}}}><RotateCcw size={18}/>结束本局，返回准备</button>}<button onClick={()=>{if(!view||window.confirm(practice?'结束这局同屏试玩？':host?'离开将关闭这张牌桌，确定？':'请房主结束本局后再离开。'))leave();}}><LogOut size={18}/>{practice?'结束试玩':'离开牌桌'}</button></div></Modal>}
    {action&&view&&<ActionSheet key={`${selfID}:${action.a.id}`} action={action.a} selected={action.values} view={view} onClose={()=>setAction(null)} onSubmit={run}/>}
    {(message||state.error)&&<div className="toast" role="status"><span>{message||state.error}</span><button className="icon" aria-label="关闭提示" onClick={()=>{setMessage('');client.clearError();}}><X size={14}/></button></div>}
    {!portraitOK&&<div className="rotate-screen"><img src="/mocha-icon-180.png" alt="桌游图标"/><small>Mocha 桌游</small><Smartphone size={42}/><h2>请横屏使用</h2><InstallButton/></div>}
  </main>;
}
