import {describe,it,expect} from 'vitest';
import {doudizhu,guandan,pokerDeck,classifyPoker,beats,pokerHint,type PokerCard,type PokerState} from '../src/core/games/poker';
import {mahjong,winningHand,mahjongTiles,type MahjongMode,type MahjongState,type Tile} from '../src/core/games/mahjong';
import {normalizeGameOptions,createMatch,applyMatch,viewMatch,validateMatchForRoom} from '../src/core/room';
import {GAMES,type Player,type Command} from '../src/core/types';
const players:Player[]=Array.from({length:4},(_,i)=>({id:`classic-player-${i}`,name:`Player ${i}`,avatar:'🐶'}));
const cards=(ranks:number[],suits?:number[]):PokerCard[]=>ranks.map((rank,i)=>({id:`c${i}`,rank,suit:suits?.[i]??i%4}));
const tiles=(values:number[],prefix='t'):Tile[]=>values.map((value,i)=>({id:`${prefix}${i}`,value}));
const play=(s:PokerState,cmd:Command)=> (s.kind==='guandan'?guandan:doudizhu).apply(s,players[s.current].id,cmd);
const mj=(s:MahjongState,i:number,cmd:Command)=>mahjong.apply(s,players[i].id,cmd);
function passResponses(s:MahjongState){for(let i=0;i<4;i++)if(mahjong.view(s,players[i].id).actions.some(a=>a.id==='pass'))s=mj(s,i,{action:'pass',values:[]});return s;}
function setupMj(mode:MahjongMode='guangdong'){const s=mahjong.create(players,42,{mahjongMode:mode});s.phase='discard';s.missing={0:2,1:2,2:2,3:2};s.current=0;return s;}
const waiting=[0,1,2,3,4,5,9,10,11,12,13,14,6];
function assertPokerCards(s:PokerState){const all=[...s.hands.flat(),...s.played,...(s.landlord<0?s.bottom:[])];expect(all.length).toBe(s.kind==='guandan'?108:54);expect(new Set(all.map(c=>c.id)).size).toBe(all.length);}
function assertTiles(s:MahjongState){const all=[...s.hands.flat(),...s.wall,...s.melds.flat().flatMap(m=>m.tiles),...s.discards.flat()];expect(all.length).toBe(mahjongTiles(s.mode).length);expect(new Set(all.map(t=>t.id)).size).toBe(all.length);expect(s.scores.reduce((a,b)=>a+b,0)).toBe(0);}
describe('Classic poker classification',()=>{
 it.each([
 [[3],'单张'],[[3,3],'对子'],[[3,3,3],'三张'],[[3,3,3,4],'三带一'],[[3,3,3,4,4],'三带二'],[[3,4,5,6,7],'顺子'],[[3,3,4,4,5,5],'连对'],[[3,3,3,4,4,4],'飞机'],[[3,3,3,4,4,4,5,6],'飞机带单'],[[3,3,3,4,4,4,5,5,6,6],'飞机带对'],[[3,3,3,3,4,5],'四带二'],[[3,3,3,3,4,4,5,5],'四带两对'],[[3,3,3,3],'炸弹'],[[16,17],'王炸']
 ] as [number[],string][])('recognizes DDZ %s as %s',(ranks,type)=>expect(classifyPoker(cards(ranks),'doudizhu').some(c=>c.type===type)).toBe(true));
 it.each([[11,12,13,14,15],[3,3,3,3,4,4,4,5],[3,3,3,4,4,4,16,17],[3,3,3,3,16,17],[3,3,3,3,4,4,4,4]].map(r=>[r]))('rejects illegal runs/wings %s',r=>expect(classifyPoker(cards(r),'doudizhu')).toEqual([]));
 it('compares same shape and length, bombs and rocket',()=>{const c=(r:number[])=>classifyPoker(cards(r),'doudizhu')[0];expect(beats(c([4,4]),c([3,3]))).toBe(true);expect(beats(c([14]),c([3,3]))).toBe(false);expect(beats(c([3,3,3,3]),c([17]))).toBe(true);expect(beats(c([16,17]),c([14,14,14,14]))).toBe(true);expect(beats(c([3,4,5,6,7,8]),c([3,4,5,6,7]))).toBe(false);});
 it('handles Guan Dan wilds, level ranks, straight flushes and bombs',()=>{const kinds=classifyPoker(cards([5,6,7,8,15],[0,0,0,0,1]),'guandan',2);expect(kinds.some(c=>c.type==='同花顺')).toBe(true);expect(classifyPoker(cards([16,15],[4,1]),'guandan',2)).toEqual([]);expect(classifyPoker(cards([15],[1]),'guandan',2)[0].power).toBe(17);expect(classifyPoker(cards([14,15,3,4,5],[0,2,0,2,0]),'guandan',2).some(c=>c.type==='顺子'&&c.power===5)).toBe(true);const flush=kinds.find(c=>c.type==='同花顺')!;expect(beats(flush,classifyPoker(cards([3,3,3,3,3]),'guandan',2)[0])).toBe(true);expect(beats(classifyPoker(cards([3,3,3,3,3,3]),'guandan',2)[0],flush)).toBe(true);expect(classifyPoker(cards([16,16,17,17]),'guandan',2).some(c=>c.type==='四大天王')).toBe(true);});
 it('does not accept duplicate card identities',()=>{const card=pokerDeck()[0];expect(classifyPoker([card,card],'guandan')).toEqual([]);});
});
describe('Poker lifecycle, trust boundaries and progression',()=>{
 it('rejects wrong seat counts and hides all hands/bottom cards during bidding',()=>{expect(()=>doudizhu.create(players,1)).toThrow();expect(()=>guandan.create(players.slice(0,3),1)).toThrow();const s=doudizhu.create(players.slice(0,3),1),v=doudizhu.view(s,players[0].id);expect(v.board.bottom).toEqual([]);expect(v.board.players.every((p:any)=>p.hand===undefined)).toBe(true);expect(JSON.stringify(v)).not.toContain(s.hands[1][0].id);expect(doudizhu.view(s,'intruder').board).toEqual({});});
 it('all-pass redeals; higher bid requirement; 3 ends bidding',()=>{let s=doudizhu.create(players.slice(0,3),1);const initial=structuredClone(s);for(let i=0;i<3;i++)s=play(s,{action:'bid',values:['0']});expect(s.hands).not.toEqual(initial.hands);s=play(s,{action:'bid',values:['2']});expect(()=>play(s,{action:'bid',values:['1']})).toThrow();s=play(s,{action:'bid',values:['3']});expect(s.hands[s.landlord]).toHaveLength(20);expect(s.phase).toBe('play');assertPokerCards(s);});
 it('rejects illegal, duplicate, out-of-turn and out-of-hand plays atomically',()=>{let s=doudizhu.create(players.slice(0,3),2);s=play(s,{action:'bid',values:['3']});const before=structuredClone(s);expect(()=>play(s,{action:'pass',values:[]})).toThrow();expect(()=>play(s,{action:'play',values:['invalid']})).toThrow();expect(()=>play(s,{action:'play',values:[s.hands[0][0].id,s.hands[0][0].id]})).toThrow();expect(()=>doudizhu.apply(s,players[1].id,{action:'play',values:[s.hands[1][0].id]})).toThrow();const ranks=s.hands[0].filter((c,i,a)=>a.findIndex(x=>x.rank===c.rank)===i).slice(0,2);expect(()=>play(s,{action:'play',values:ranks.map(c=>c.id)})).toThrow();expect(s).toEqual(before);});
 it('scores landlord spring and farmer counter-spring zero-sum',()=>{let s=doudizhu.create(players.slice(0,3),1);s=play(s,{action:'bid',values:['3']});s.hands[0]=cards([3]);s=play(s,{action:'play',values:['c0']});expect(s.scores).toEqual([12,-6,-6]);expect(s.winners).toEqual([players[0].id]);s=doudizhu.create(players.slice(0,3),1);s=play(s,{action:'bid',values:['2']});s=play(s,{action:'bid',values:['0']});s=play(s,{action:'bid',values:['0']});s.current=1;s.plays[0]=1;s.hands[1]=cards([4]);s=play(s,{action:'play',values:['c0']});expect(s.scores).toEqual([-8,4,4]);expect(s.winners).toEqual([players[1].id,players[2].id]);});
 it('partner receives the lead after an empty-hand winner and all passes',()=>{let s=guandan.create(players,1);s.hands[0]=cards([3]);s=play(s,{action:'play',values:['c0']});for(let i=0;i<3;i++)s=play(s,{action:'pass',values:[]});expect(s.current).toBe(2);expect(s.last).toBeNull();});
 it('advances 3/2/1, caps at A and only finishes on a successful actual A deal',()=>{for(const [order,me,gain]of [[[0],2,3],[[0,1],2,2],[[0,1],3,1]] as [number[],number,number][]){let s=guandan.create(players,4);s.order=order;s.current=me;order.forEach(i=>s.hands[i]=[]);s.hands[me]=cards([4]);s=play(s,{action:'play',values:['c0']});expect(s.levels[0]).toBe(2+gain);expect(s.phase).toBe('roundEnd');}let s=guandan.create(players,4);s.levels=[13,2];s.level=13;s.order=[0];s.hands[0]=[];s.current=2;s.hands[2]=cards([4]);s=play(s,{action:'play',values:['c0']});expect(s.finished).toBe(false);expect(s.level).toBe(14);s.levels[0]=14;s.order=[0];s.current=2;s.hands[2]=cards([4]);s.phase='play';s.last=null;s=play(s,{action:'play',values:['c0']});expect(s.finished).toBe(true);expect(s.winners).toEqual([players[0].id,players[2].id]);});
 it('deals next round, resolves tribute and preserves all 108 cards',()=>{for(let seed=1;seed<=12;seed++){let s=guandan.create(players,seed);s.previousOrder=seed%2?[0,2,1,3]:[0,1,2,3];s.phase='roundEnd';s=play(s,{action:'nextRound',values:[]});assertPokerCards(s);while(s.phase==='tribute'){const a=guandan.view(s,players[s.current].id).actions[0];s=play(s,{action:a.id,values:[a.choices[0].id]});assertPokerCards(s);}expect(s.hands.map(h=>h.length)).toEqual([27,27,27,27]);expect(s.phase).toBe('play');}});
 it.each(['doudizhu','guandan'] as const)('finishes seeded %s deals with legal hints and conserved cards',kind=>{for(let seed=1;seed<=8;seed++){const mod=kind==='guandan'?guandan:doudizhu;let s=mod.create(players.slice(0,kind==='guandan'?4:3),seed);if(kind==='doudizhu')s=play(s,{action:'bid',values:['3']});let steps=0;while(!s.finished&&s.phase!=='roundEnd'&&steps++<1500){assertPokerCards(s);const hint=pokerHint(s);s=play(s,hint.length?{action:'play',values:hint}:{action:'pass',values:[]});if(steps%25===0)s=JSON.parse(JSON.stringify(s));}expect(steps).toBeLessThan(1500);assertPokerCards(s);expect(s.finished||s.phase==='roundEnd').toBe(true);}},30000);
});
describe('Mahjong hand solver',()=>{
 it.each([
 [waiting.concat(6),0,-1,true],[[0,0,1,1,2,2,3,3,4,4,5,5,6,6],0,-1,true],[[0,0,0,0,1,1,2,2,3,3,4,4,5,5],0,-1,true],[[0,8,9,17,18,26,27,28,29,30,31,32,33,33],0,-1,true],[[0,1,2,9,10,11,18,19,20,27,27],1,-1,true],[[0,1,2,3,4,5,9,10,11,12,13,33,6,33],0,33,true],[[2,33,33,5,6,7,9,10,11,27,27,27,28,28],0,33,true],[[7,8,9,3,4,5,9,10,11,12,13,14,6,6],0,-1,false],[waiting,0,-1,false]
 ] as [number[],number,number,boolean][])('solves %s',(values,meld,wild,expected)=>expect(winningHand(tiles(values),meld,wild)).toBe(expected));
 it('does not count seven pairs with open melds',()=>expect(winningHand(tiles([0,0,1,1,2,2,3,3,4,4,5]),1)).toBe(false));
});
describe('Mahjong actions and settlement',()=>{
 it('deals deterministically, filters private data and blocks spectators',()=>{const s=mahjong.create(players,3);expect(s).toEqual(mahjong.create(players,3));expect(s.hands.map(h=>h.length)).toEqual([14,13,13,13]);assertTiles(s);const v=mahjong.view(s,players[0].id);expect(JSON.stringify(v)).not.toContain(s.wall[0].id);expect(JSON.stringify(v)).not.toContain(s.hands[1][0].id);expect(mahjong.view(s,'intruder').board).toEqual({});});
 it('exchanges only same-suit triples privately, then requires all four missing-suit choices',()=>{let s=mahjong.create(players,8,{mahjongMode:'sichuan'});const old=structuredClone(s),mixed=[s.hands[0][0],s.hands[0].find(t=>Math.floor(t.value/9)!==Math.floor(s.hands[0][0].value/9))!,s.hands[0].at(-1)!];expect(()=>mj(s,0,{action:'exchange',values:mixed.map(t=>t.id)})).toThrow();expect(s).toEqual(old);for(let i=0;i<4;i++){const group=[0,1,2].map(suit=>s.hands[i].filter(t=>Math.floor(t.value/9)===suit)).find(g=>g.length>=3)!;s=mj(s,i,{action:'exchange',values:group.slice(0,3).map(t=>t.id)});assertTiles(s);if(i===0)expect(JSON.stringify(mahjong.view(s,players[1].id).board)).not.toContain(group[0].id);}expect(s.phase).toBe('que');for(let i=0;i<4;i++){s=mj(s,i,{action:'que',values:['2']});if(i<3)expect(s.phase).toBe('que');}expect(s.phase).toBe('discard');expect(s.hands[0].some(t=>t.id===s.drawn)).toBe(true);});
 it('forces missing-suit discards and validates commands without mutation',()=>{const s=setupMj('sichuan');s.hands[0]=tiles([0,1,2,3,4,5,9,10,11,12,13,14,18,18]);const old=structuredClone(s);expect(mahjong.view(s,players[0].id).actions.find(a=>a.id==='discard')!.choices).toHaveLength(2);expect(()=>mj(s,0,{action:'discard',values:['t0']})).toThrow();expect(()=>mj(s,1,{action:'discard',values:['t0']})).toThrow();expect(s).toEqual(old);});
 it('collects all responses privately; simultaneous wins outrank an earlier pung',()=>{let s=setupMj();s.hands[0]=tiles([6],'a');s.hands[1]=tiles(waiting,'b');s.hands[2]=tiles(waiting,'c');s.hands[3]=tiles([6,6,0,1,2,3,4,5,9,10,11,12,13],'d');s=mj(s,0,{action:'discard',values:['a0']});s=mj(s,3,{action:'pong',values:[]});expect(s.phase).toBe('respond');expect(mahjong.view(s,players[1].id).board.pending.responses).toBeUndefined();s=mj(s,1,{action:'hu',values:[]});s=mj(s,2,{action:'hu',values:[]});expect(s.finished).toBe(true);expect(s.wins.map(w=>w.player)).toEqual([1,2]);expect(s.melds[3]).toEqual([]);expect(s.scores.reduce((a,b)=>a+b,0)).toBe(0);});
 it('resolves pong without drawing and refuses invented response claims',()=>{let s=setupMj();s.hands[0]=tiles([6],'a');s.hands[1]=tiles([6,6,0,1,2,3,4,5,9,10,11,12,13],'b');s=mj(s,0,{action:'discard',values:['a0']});expect(()=>mj(s,2,{action:'concealed:6',values:['6']})).toThrow();s=mj(s,1,{action:'pong',values:[]});const wall=s.wall.length;s=passResponses(s);expect(s.current).toBe(1);expect(s.wall.length).toBe(wall);expect(s.melds[1][0].tiles).toHaveLength(3);expect(s.discards[0]).toEqual([]);expect(mahjong.view(s,players[1].id).actions.some(a=>a.id==='hu')).toBe(false);});
 it('hides concealed kongs and scores them, with one replacement draw',()=>{let s=setupMj();s.hands[0]=tiles([6,6,6,6,0,1,2,3,4,5,9,10,11,12]);const wall=s.wall.length;s=mj(s,0,{action:'concealed:6',values:['6']});expect(s.wall.length).toBe(wall-1);expect(s.scores).toEqual([6,-2,-2,-2]);expect(mahjong.view(s,players[1].id).board.players[0].melds[0].tiles).toEqual([]);expect(mahjong.view(s,players[0].id).board.players[0].melds[0].tiles).toHaveLength(4);});
 it('robs an added kong before collecting kong payments',()=>{let s=setupMj();s.hands[0]=tiles([6,0,1,2,3,4,5,9,10,11,12],'a');s.melds[0]=[{type:'pong',tiles:tiles([6,6,6],'meld'),from:1}];s.hands[1]=tiles(waiting,'b');s=mj(s,0,{action:'added:6',values:['6']});s=mj(s,1,{action:'hu',values:[]});s=passResponses(s);expect(s.finished).toBe(true);expect(s.melds[0][0].type).toBe('pong');expect(s.kongPayments).toEqual([]);expect(s.discards[0].map(t=>t.id)).toContain('a0');expect(s.wins[0].points).toBe(2);});
 it('completes an unrobbed added kong and scores after all responses',()=>{let s=setupMj();s.hands[0]=tiles([6,0,1,2,3,4,5,9,10,11,12],'a');s.melds[0]=[{type:'pong',tiles:tiles([6,6,6],'meld'),from:1}];s=mj(s,0,{action:'added:6',values:['6']});s=passResponses(s);expect(s.melds[0][0].type).toBe('kong');expect(s.scores).toEqual([3,-1,-1,-1]);expect(s.current).toBe(0);expect(s.afterKong).toBe(true);});
 it('blood battle removes winners, blood flow permits later repeat wins but prevents repeat self-draw now',()=>{for(const mode of ['sichuan','bloodflow'] as const){let s=setupMj(mode);s.hands[0]=tiles([...waiting,6]);s.drawn='t13';s=mj(s,0,{action:'hu',values:[]});expect(s.finished).toBe(false);expect(s.wins).toHaveLength(1);if(mode==='sichuan'){expect(s.current).toBe(1);expect(mahjong.view(s,players[0].id).actions).toEqual([]);}else{expect(s.current).toBe(0);expect(mahjong.view(s,players[0].id).actions.map(a=>a.id)).toEqual(['discard']);s=mj(s,0,{action:'discard',values:['t13']});s=passResponses(s);expect(s.current).toBe(1);}}});
 it('red dragons complete a hand but cannot be claimed or melded',()=>{let s=setupMj('laizi');s.hands[0]=tiles([0,1,2,3,4,5,9,10,11,12,13,33,6,33]);expect(mahjong.view(s,players[0].id).actions.some(a=>a.id==='hu')).toBe(true);s=mj(s,0,{action:'discard',values:['t11']});s.hands[1]=tiles([33,33,33,0,1,2,3,4,5,6,7,8,9],'other');expect(s.phase).toBe('discard');expect(s.current).toBe(1);expect(s.pending).toBeNull();expect(mahjong.view(s,players[1].id).actions.some(a=>a.id==='pass')).toBe(false);});
 it('does not expose kongs when no replacement remains',()=>{const s=setupMj();s.wall=[];s.hands[0]=tiles([6,6,6,6,0,1,2,3,4,5,9,10,11,12]);expect(mahjong.view(s,players[0].id).actions.some(a=>a.id.startsWith('concealed'))).toBe(false);});
 it('exhaustion settles missing suits, readiness and kong refunds zero-sum',()=>{let s=setupMj('sichuan');s.wall=[];s.hands[0]=tiles([0,1,2,3,4,5,9,10,11,12,13,14,18,19],'a');s.hands[1]=tiles(waiting,'b');s.hands[2]=tiles([0,0,1,2,3,4,6,7,9,10,12,13,16],'c');s.hands[3]=tiles(waiting,'d');s.kongPayments=[{from:1,to:0,points:2}];s.scores=[2,-2,0,0];s=mj(s,0,{action:'discard',values:['a13']});s=passResponses(s);expect(s.finished).toBe(true);expect(s.scores[0]).toBe(-48);expect(s.scores[1]).toBeGreaterThan(0);expect(s.scores[2]).toBe(14);expect(s.scores.reduce((a,b)=>a+b,0)).toBe(0);});
 it.each(['guangdong','sichuan','bloodflow','laizi'] as const)('completes seeded %s matches without leaks or tile duplication',mode=>{for(let seed=1;seed<=6;seed++){let s=mahjong.create(players,seed,{mahjongMode:mode}),steps=0;while(!s.finished&&steps++<600){assertTiles(s);const i=players.findIndex(p=>mahjong.view(s,p.id).actions.length);expect(i).toBeGreaterThanOrEqual(0);const actions=mahjong.view(s,players[i].id).actions;let a=actions.find(a=>a.id==='hu')||actions.find(a=>a.id.startsWith('concealed:'))||actions.find(a=>a.id==='kong')||actions.find(a=>a.id==='pong')||actions[0],values=a.choices.slice(0,a.min).map(c=>c.id);if(a.id==='exchange'){const group=[0,1,2].map(suit=>s.hands[i].filter(t=>Math.floor(t.value/9)===suit)).find(g=>g.length>=3)!;values=group.slice(0,3).map(t=>t.id);}s=mj(s,i,{action:a.id,values});if(steps%25===0)s=JSON.parse(JSON.stringify(s));}expect(s.finished).toBe(true);assertTiles(s);}},30000);
});
describe('Room integration',()=>{
 it('accepts only supported Mahjong options on the right game',()=>{expect(normalizeGameOptions('mahjong',{mahjongMode:'bloodflow'},players[0].id)).toEqual({mahjongMode:'bloodflow'});for(const input of ['unknown',null,1,{},true])expect(()=>normalizeGameOptions('mahjong',{mahjongMode:input},players[0].id)).toThrow();expect(()=>normalizeGameOptions('uno',{mahjongMode:'laizi'},players[0].id)).toThrow();});
 it.each(['doudizhu','guandan','mahjong'] as const)('supports %s revisions, persistence and replay protection',kind=>{const roster=players.slice(0,GAMES[kind].min);let match=createMatch(kind,roster);const actor=roster.find(p=>viewMatch(match,kind,p.id).view.actions.length)!;const a=viewMatch(match,kind,actor.id).view.actions[0];let values=a.choices.slice(0,a.min).map(c=>c.id);if(kind==='guandan')values=[match.game.hands[0][0].id];const command={action:a.id,values};const next=applyMatch(match,kind,roster,actor.id,command,'classic-request',match.actorRevisions[actor.id]);expect(next.revision).toBe(match.revision+1);expect(applyMatch(next,kind,roster,actor.id,command,'classic-request',match.actorRevisions[actor.id])).toEqual(next);const room:any={code:'ABCDEF',kind,mode:'cloud',hostID:roster[0].id,players:roster,options:undefined};expect(validateMatchForRoom(JSON.parse(JSON.stringify(next)),room).game).toEqual(next.game);});
});
describe('Declared Guan Dan combinations and complete matches',()=>{
 it('defaults a suited straight to straight flush and accepts an explicitly declared weaker straight',()=>{let s=guandan.create(players,3);s.hands[0]=cards([5,6,7,8,9],[0,0,0,0,0]);s.hands[0].push({id:'spare',rank:3,suit:2});const ids=s.hands[0].slice(0,5).map(c=>c.id);const result=play(s,{action:'play',values:ids});expect(result.last!.combo.type).toBe('同花顺');const declared=play(s,{action:'play',values:ids,text:'顺子:9:5:0'});expect(declared.last!.combo.type).toBe('顺子');expect(()=>play(s,{action:'play',values:ids,text:'四大天王:100:4:100'})).toThrow();expect(s.hands[0]).toHaveLength(6);});
 it('offers a four-with-wings hint rather than falsely saying no higher play',()=>{const s=doudizhu.create(players.slice(0,3),5);s.phase='play';s.hands[0]=cards([5,5,5,5,6,6,7,7]);s.last={player:1,cards:cards([3,3,3,3,4,4,8,8]),combo:{type:'四带两对',power:3,size:8,bomb:0}};const hint=pokerHint(s);expect(hint.length).toBeGreaterThan(0);expect(classifyPoker(hint.map(id=>s.hands[0].find(c=>c.id===id)!),'doudizhu').some(c=>beats(c,s.last!.combo))).toBe(true);});
 it('plays a full upgrade match including repeated tribute, persistence and a real A finish',()=>{let s=guandan.create(players,18),steps=0;while(!s.finished&&steps++<12000){if(s.phase==='roundEnd'){assertPokerCards(s);s=JSON.parse(JSON.stringify(s));s=play(s,{action:'nextRound',values:[]});}else if(s.phase==='tribute'){const a=guandan.view(s,players[s.current].id).actions[0];s=play(s,{action:'return',values:[a.choices[0].id]});}else{const hint=pokerHint(s);s=play(s,{action:hint.length?'play':'pass',values:hint});}}expect(s.finished).toBe(true);expect(s.level).toBe(14);expect(s.round).toBeGreaterThan(1);expect(s.winners).toHaveLength(2);expect(s.order.indexOf((s.order[0]+2)%4)).toBeLessThan(3);assertPokerCards(s);},30000);
});
describe('Blood Flow locked-hand boundary',()=>{
 it('locks the first winning hand and rejects changing it after winning',()=>{let s=setupMj('bloodflow');s.hands[0]=tiles([...waiting,6]);s.drawn='t13';s=mj(s,0,{action:'hu',values:[]});expect(mahjong.view(s,players[0].id).actions.find(a=>a.id==='discard')!.choices.map(c=>c.id)).toEqual(['t13']);const original=structuredClone(s);expect(()=>mj(s,0,{action:'discard',values:['t0']})).toThrow();expect(s).toEqual(original);s=mj(s,0,{action:'discard',values:['t13']});s=passResponses(s);s.current=0;s.phase='discard';s.hands[0].push({id:'new-draw',value:6});s.drawn='new-draw';s.selfWon=false;s=mj(s,0,{action:'hu',values:[]});expect(s.wins).toHaveLength(2);expect(mahjong.view(s,players[0].id).actions.find(a=>a.id==='discard')!.choices[0].id).toBe('new-draw');});
});
