import {describe,it,expect} from 'vitest';
import {drawrelay,advanceRelayClock,pauseRelayClock,resumeRelayClock,encodeRelayStroke,decodeRelayStroke,RELAY_MAX_STROKES,type DrawRelayState} from '../src/core/games/drawrelay';
import {applyMatch,createMatch} from '../src/core/room';
const players=(n=3)=>Array.from({length:n},(_,i)=>({id:`player_${i}`,name:`人${i}`,avatar:'🦊'}));
const stroke=encodeRelayStroke([[0,0],[1023,767]],2,1);
const edit=(s:DrawRelayState,id:string)=>s.step%2?drawrelay.apply(s,id,{action:'stroke',values:[String(s.step),stroke]}):drawrelay.apply(s,id,{action:'draft',values:[String(s.step)],text:`secret-${s.step}-${id}`});
function completeStep(state:DrawRelayState){let s=state;for(const p of s.players){s=edit(s,p.id);s=drawrelay.apply(s,p.id,{action:'submit',values:[String(s.step)]});}return s;}
describe('Mocha drawing relay',()=>{
 it.each([3,4,7,12])('rotates each of %i albums through every player exactly once',n=>{let s=drawrelay.create(players(n),7);for(let step=0;step<n;step++){expect(s.step).toBe(step);s=completeStep(s);}expect(s.finished).toBe(true);s.books.forEach((book,owner)=>{expect(book).toHaveLength(n);expect(book.map(e=>e.author)).toEqual(Array.from({length:n},(_,step)=>`player_${(owner+step)%n}`));expect(book.map(e=>e.kind)).toEqual(Array.from({length:n},(_,step)=>step%2?'drawing':'text'));});});
 it('projects only the assigned preceding page and own draft, then one album page',()=>{let s=drawrelay.create(players(),1);s=completeStep(s);const views=s.players.map(p=>drawrelay.view(s,p.id));expect(views[0].board.previous.text).toBe('secret-0-player_2');expect(views[1].board.previous.text).toBe('secret-0-player_0');for(const [i,v]of views.entries()){expect(JSON.stringify(v)).not.toContain(`secret-0-player_${i}`);expect(v.board.books).toBeUndefined();expect(v.board.drafts).toBeUndefined();}expect(JSON.stringify(drawrelay.view(s,'',true))).not.toContain('secret-');s=edit(s,'player_0');expect(drawrelay.view(s,'player_1').board.draft.strokes).toEqual([]);expect(JSON.stringify(drawrelay.view(s,'',true))).not.toContain(stroke);while(!s.finished)s=completeStep(s);expect(drawrelay.view(s,'player_1').board.gallery.entry.text).toBe('secret-0-player_0');s=drawrelay.apply(s,'player_1',{action:'album',values:['2']});s=drawrelay.apply(s,'player_1',{action:'page',values:['2']});expect(drawrelay.view(s,'player_1').board.gallery).toMatchObject({book:2,page:2});expect(drawrelay.view(s,'player_0').board.gallery).toMatchObject({book:0,page:0});expect(drawrelay.view(s,'',true).board.gallery).toMatchObject({book:0,page:0});});
 it('keeps actions atomic, submissions final, page nonces fresh and outsiders rejected',()=>{let s=drawrelay.create(players(),1);const before=JSON.stringify(s);for(const c of [{action:'submit',values:['0']},{action:'stroke',values:['0',stroke]},{action:'draft',values:['1'],text:'old'},{action:'draft',values:['0'],text:'a'.repeat(121)},{action:'tick',values:['0']}])expect(()=>drawrelay.apply(s,'player_0',c)).toThrow();expect(()=>drawrelay.apply(s,'intruder',{action:'draft',values:['0'],text:'hello'})).toThrow();expect(JSON.stringify(s)).toBe(before);s=edit(s,'player_0');s=drawrelay.apply(s,'player_0',{action:'submit',values:['0']});expect(()=>edit(s,'player_0')).toThrow('已经提交');const v=drawrelay.view(s,'player_0');v.board.draft.text='tamper';expect(s.drafts[0].text).not.toBe('tamper');});
 it('accepts simultaneous drafts, deduplicates retries, and rejects pre-transition commands',()=>{const ps=players();let m=createMatch('drawrelay',ps);const old=m.actorRevisions[ps[1].id];m=applyMatch(m,'drawrelay',ps,ps[0].id,{action:'draft',values:['0'],text:'first'},'a',m.actorRevisions[ps[0].id]);expect(m.actorRevisions[ps[1].id]).toBe(old);m=applyMatch(m,'drawrelay',ps,ps[1].id,{action:'draft',values:['0'],text:'second'},'b',old);expect(applyMatch(m,'drawrelay',ps,ps[1].id,{action:'draft',values:['0'],text:'retry'},'b',old)).toBe(m);m.game=completeStep(drawrelay.create(ps,1));expect(()=>applyMatch(m,'drawrelay',ps,ps[0].id,{action:'draft',values:['0'],text:'wrong-page'},'new',m.actorRevisions[ps[0].id])).toThrow();});
 it('uses trusted deadlines, saves partial drafts, and freezes the remaining time',()=>{let s=drawrelay.create(players(),1,{relaySeconds:60});s=advanceRelayClock(s,1000);expect(s.deadlineAt).toBe(61000);s=edit(s,'player_0');s=pauseRelayClock(s,21000);expect(s.pausedRemaining).toBe(40000);expect(s.deadlineAt).toBe(0);expect(advanceRelayClock(s,90000)).toBe(s);s=resumeRelayClock(s,100000);expect(s.deadlineAt).toBe(140000);expect(advanceRelayClock(s,139999)).toBe(s);s=advanceRelayClock(s,140000);expect(s.step).toBe(1);expect(s.books[0][0]).toMatchObject({text:'secret-0-player_0',timedOut:true});expect(s.books[1][0]).toMatchObject({skipped:true,timedOut:true});expect(s.deadlineAt).toBe(200000);s=advanceRelayClock(s,999999999);expect(s.step).toBe(2);expect(s.deadlineAt).toBe(1000059999);s=advanceRelayClock(s,s.deadlineAt);expect(s.finished).toBe(true);expect(s.deadlineAt).toBe(0);});
 it('has unlimited mode and supports undo and clear without changing preceding pages',()=>{let s=drawrelay.create(players(),1,{relaySeconds:0});expect(advanceRelayClock(s,100)).toBe(s);s=completeStep(s);s=edit(s,'player_0');s=edit(s,'player_0');s=drawrelay.apply(s,'player_0',{action:'undo',values:['1']});expect(s.drafts[0].strokes).toHaveLength(1);s=drawrelay.apply(s,'player_0',{action:'clear',values:['1']});expect(s.drafts[0].strokes).toEqual([]);expect(s.books[2][0].text).toBe('secret-0-player_2');});
 it('validates compact stroke coordinates and bounds',()=>{expect(decodeRelayStroke(stroke)).toEqual({color:2,width:1,points:[[0,0],[1023,767]]});for(const bad of ['', 'AAAAA','__AAAA','AA____', 'AA'+ 'AA'.repeat(99),encodeRelayStroke([[0,768]],0,0)])expect(()=>decodeRelayStroke(bad)).toThrow();let s=completeStep(drawrelay.create(players(),1));for(let i=0;i<RELAY_MAX_STROKES;i++)s=edit(s,'player_0');const before=JSON.stringify(s);expect(()=>edit(s,'player_0')).toThrow('画布已满');expect(JSON.stringify(s)).toBe(before);});
 it('bounds worst-case persisted state below SQLite 2MB and every network projection below 64KiB',()=>{let s=drawrelay.create(players(12),1);const long=encodeRelayStroke(Array.from({length:48},(_,i)=>[i*21,i*16]),6,2);for(let step=0;step<12;step++){s.drafts.forEach((draft,i)=>{if(step%2)draft.strokes=Array(96).fill(long);else draft.text='🦊'.repeat(120);s.submitted[i]=i<11;});s=drawrelay.apply(s,'player_11',{action:'submit',values:[String(step)]});}expect(new TextEncoder().encode(JSON.stringify(s)).length).toBeLessThan(1500000);for(const p of s.players){const v=drawrelay.view(s,p.id);expect(new TextEncoder().encode(JSON.stringify(v)).length).toBeLessThan(64000);}s.finished=false;s.step=11;s.drafts=s.players.map(p=>({author:p.id,kind:'drawing',strokes:Array(96).fill(long)}));s.submitted=s.players.map(()=>false);expect(new TextEncoder().encode(JSON.stringify(drawrelay.view(s,'player_0'))).length).toBeLessThan(64000);});
});
