import { describe, expect, it } from 'vitest';
import { sushi, sushiPlateScore, type SushiCard, type SushiKind } from '../src/core/games/sushi';
import { uno, unoWild4Legal, type UnoCard } from '../src/core/games/uno';
import { century, centuryScore } from '../src/core/games/century';
import { seeded, type GameModule, type Player } from '../src/core/types';
const players=(n:number):Player[]=>Array.from({length:n},(_,i)=>({id:`p${i}`,name:`玩家 ${i}`,avatar:'🐱'}));
const sushiCards=(...kinds:SushiKind[]):SushiCard[]=>kinds.map((kind,i)=>({id:`test-${i}`,kind}));
const uc=(id:string,color:UnoCard['color'],value:UnoCard['value']):UnoCard=>({id,color,value});

describe('Sushi Go',()=>{
 it('deals from the 108-card catalog and completes all 3 rounds for each player count',()=>{for(let n=2;n<=5;n++){let s=sushi.create(players(n),100+n);expect(s.deck.length+s.hands.flat().length).toBe(108);expect(s.hands[0]).toHaveLength(12-n);for(let steps=0;!s.finished&&steps<100;steps++){for(const p of s.players){const view=sushi.view(s,p.id);const a=view.actions.find(a=>a.id==='pick');if(a)s=sushi.apply(s,p.id,{action:'pick',values:[a.choices[0].id]});}}expect(s.finished).toBe(true);expect(s.roundScores).toHaveLength(3);expect(s.winners.length).toBeGreaterThan(0);expect(sushi.view(s,'p0').actions).toEqual([]);}});
 it('keeps other hands and locked selections private and rejects duplicate, foreign and late commands',()=>{const s=sushi.create(players(3),5),card=s.hands[0][0],before=JSON.stringify(s);const picked=sushi.apply(s,'p0',{action:'pick',values:[card.id]});expect(JSON.stringify(s)).toBe(before);expect(picked.picks[0]).toEqual([card.id]);const other=sushi.view(picked,'p1');expect(JSON.stringify(other)).not.toContain(card.id);expect(other.board.players[0].ready).toBe(true);expect(()=>sushi.apply(s,'p0',{action:'pick',values:[card.id,card.id]})).toThrow();expect(()=>sushi.apply(s,'outsider',{action:'pick',values:[card.id]})).toThrow();expect(()=>sushi.apply(picked,'p0',{action:'pick',values:[card.id]})).toThrow();expect(sushi.apply(picked,'p0',{action:'cancel',values:[]}).picks[0]).toBeNull();});
 it('scores sequences, complete sets and dumpling caps',()=>{expect(sushiPlateScore(sushiCards('wasabi','salmon','salmon'))).toBe(8);expect(sushiPlateScore(sushiCards('salmon','wasabi'))).toBe(2);expect(sushiPlateScore(sushiCards('sashimi','sashimi','sashimi','tempura','tempura','tempura'))).toBe(15);expect(sushiPlateScore(sushiCards(...Array(6).fill('dumpling')))).toBe(15);});
 it('returns chopsticks to the passed hand and observes the chosen order',()=>{let s=sushi.create(players(2),2);s.hands=[sushiCards('wasabi','squid','pudding','egg'),sushiCards('tempura','sashimi','pudding','egg').map(c=>({...c,id:'b-'+c.id}))];s.table=[sushiCards('chopsticks'),[]];s=sushi.apply(s,'p0',{action:'pick',values:[s.hands[0][0].id,s.hands[0][1].id]});s=sushi.apply(s,'p1',{action:'pick',values:[s.hands[1][0].id]});expect(s.table[0].map(c=>c.kind)).toEqual(['wasabi','squid']);expect(sushiPlateScore(s.table[0])).toBe(9);expect(s.hands[1].some(c=>c.kind==='chopsticks')).toBe(true);expect(s.hands[0]).toHaveLength(3);});
 it('splits maki first place without a second award and handles pudding tie break',()=>{let s=sushi.create(players(3),4);s.round=3;s.scores=[0,0,0];s.puddings=[0,1,0];s.table=[sushiCards('maki2'),sushiCards('maki2'),sushiCards('maki1')];s.hands=s.players.map((_,i)=>[{id:`end-${i}`,kind:'chopsticks'}]);for(const p of s.players)s=sushi.apply(s,p.id,{action:'pick',values:[s.hands[s.players.findIndex(x=>x.id===p.id)][0].id]});expect(s.roundScores[0]).toEqual([3,3,0]);expect(s.scores).toEqual([0,9,-3]);expect(s.winners).toEqual(['p1']);});
});

describe('UNO',()=>{
 it('uses 108 cards, deterministic dealing, seven-card hands plus starting effects',()=>{const a=uno.create(players(4),42),b=uno.create(players(4),42);expect(a).toEqual(b);expect(a.deck.length+a.hands.flat().length+a.discard.length).toBe(108);expect(a.discard[0].value).not.toBe('wild4');expect(a.hands.every(h=>h.length===7||h.length===9)).toBe(true);expect(JSON.stringify(uno.view(a,'p0'))).not.toContain(a.hands[1][0].id);});
 it('permits a +4 bluff while accurately recording matching-color legality',()=>{const s=uno.create(players(2),3);s.current=0;s.phase='play';s.color='red';s.hands[0]=[uc('r','red',2),uc('w','wild','wild4')];expect(uno.view(s,'p0').actions.some(a=>a.id==='wild:w')).toBe(true);expect(unoWild4Legal(s)).toBe(false);s.hands[0][0]=uc('r','blue',2);expect(unoWild4Legal(s)).toBe(true);expect(uno.view(s,'p0').actions.some(a=>a.id==='wild:w')).toBe(true);});
 it('draws only one card and only allows that newly drawn card to be played',()=>{let s=uno.create(players(2),3);s.current=0;s.phase='play';s.color='red';s.discard=[uc('top','red',3)];s.hands[0]=[uc('old','red',7)];s.deck=[uc('new','red',9)];s=uno.apply(s,'p0',{action:'draw',values:[]});expect(s.current).toBe(0);expect(s.drawn).toBe('new');expect(uno.view(s,'p0').actions.find(a=>a.id==='play')?.choices.map(c=>c.id)).toEqual(['new']);expect(()=>uno.apply(s,'p0',{action:'draw',values:[]})).toThrow();s=uno.apply(s,'p0',{action:'pass',values:[]});expect(s.current).toBe(1);});
 it('two-player reverse returns play to the same player and finishes penalties before scoring',()=>{let s=uno.create(players(2),7,{unoMode:'single'});s.phase='play';s.current=0;s.color='red';s.discard=[uc('top','red',1)];s.hands[0]=[uc('reverse','red','reverse'),uc('plus','red','draw2')];s.hands[1]=[uc('blue','blue',5)];s.deck=[uc('d1','blue',2),uc('d2','green',3)];s=uno.apply(s,'p0',{action:'play',values:['reverse']});expect(s.current).toBe(0);expect(s.phase).toBe('unoCall');s=uno.apply(s,'p0',{action:'callUno',values:[]});s=uno.apply(s,'p0',{action:'play',values:['plus']});expect(s.finished).toBe(true);expect(s.hands[1]).toHaveLength(3);expect(s.scores[0]).toBe(10);expect(s.winners).toEqual(['p0']);});
 it('recycles discards while preserving the top card and never exposes draw pile',()=>{let s=uno.create(players(2),6);s.current=0;s.phase='play';s.color='red';s.deck=[];s.discard=[uc('recycled','blue',8),uc('top','red',3)];s=uno.apply(s,'p0',{action:'draw',values:[]});expect(s.discard.map(c=>c.id)).toEqual(['top']);expect(s.hands[0].some(c=>c.id==='recycled')).toBe(true);expect(JSON.stringify(uno.view(s,'p1'))).not.toContain('recycled');});
 it('finishes legal random matches at 2, 4 and 10 players while conserving every card',()=>{for(const n of [2,4,10]){let s=uno.create(players(n),20+n,{unoMode:'single'});const rng=seeded(n);for(let step=0;!s.finished&&step<3000;step++){const actor=s.players.find(p=>uno.view(s,p.id).actions.length)!;const view=uno.view(s,actor.id),options=view.actions.filter(a=>a.id!=='draw'&&a.id!=='pass'),a=options.length?options[Math.floor(rng()*options.length)]:view.actions[0];s=uno.apply(s,actor.id,{action:a.id,values:a.min?[a.choices[Math.floor(rng()*a.choices.length)].id]:[]});expect(s.deck.length+s.hands.flat().length+s.discard.length).toBe(108);}expect(s.finished).toBe(true);expect(s.winners).toHaveLength(1);}});
});

describe('Century digital selection',()=>{
 it('matches starting caravans and hides other hands and point cards',()=>{const s=century.create(players(5),12);expect(s.caravans.map(c=>c.cubes)).toEqual([[3,0,0,0],[4,0,0,0],[4,0,0,0],[3,1,0,0],[3,1,0,0]]);expect(s.market).toHaveLength(6);expect(s.goals).toHaveLength(5);expect(s.gold).toBe(10);expect(JSON.stringify(century.view(s,'p0'))).not.toContain('start-gain-p1');});
 it('upgrades the same cube twice, permits early stop and restores cards on rest',()=>{let s=century.create(players(2),2);s=century.apply(s,'p0',{action:'play',values:['start-upgrade-p0']});s=century.apply(s,'p0',{action:'upgrade',values:['0']});s=century.apply(s,'p0',{action:'upgrade',values:['1']});expect(s.caravans[0].cubes).toEqual([2,0,1,0]);expect(s.current).toBe(1);s=century.apply(s,'p1',{action:'rest',values:[]});s=century.apply(s,'p0',{action:'rest',values:[]});expect(s.caravans[0].hand).toHaveLength(2);});
 it('pays each preceding merchant using chosen colors, collects bonuses and shifts the market',()=>{let s=century.create(players(2),3);s.caravans[0].cubes=[2,1,0,0];const target=s.market[2].card.id,first=s.market[0].card.id,second=s.market[1].card.id;s.market[2].bonus=[0,0,1,0];s=century.apply(s,'p0',{action:'acquire',values:[target]});s=century.apply(s,'p0',{action:'pay',values:['1']});s=century.apply(s,'p0',{action:'pay',values:['0']});expect(s.caravans[0].cubes).toEqual([1,0,1,0]);expect(s.market.find(m=>m.card.id===first)?.bonus).toEqual([0,1,0,0]);expect(s.market.find(m=>m.card.id===second)?.bonus).toEqual([1,0,0,0]);expect(s.caravans[0].hand.some(c=>c.id===target)).toBe(true);expect(s.market).toHaveLength(6);expect(s.current).toBe(1);});
 it('allows repeated trades then enforces exact caravan capacity',()=>{let s=century.create(players(2),3);s.caravans[0].hand=[{id:'trade-test',type:'trade',cost:[0,1,0,0],gain:[3,0,0,0],upgrades:0}];s.caravans[0].cubes=[4,3,0,0];s=century.apply(s,'p0',{action:'play',values:['trade-test']});s=century.apply(s,'p0',{action:'repeat',values:[]});s=century.apply(s,'p0',{action:'repeat',values:[]});expect(s.caravans[0].cubes).toEqual([13,0,0,0]);expect(century.view(s,'p0').actions.some(a=>a.id==='repeat')).toBe(false);s=century.apply(s,'p0',{action:'done',values:[]});expect(s.phase).toBe('discard');expect(()=>century.apply(s,'p0',{action:'discard',values:['0:0']})).toThrow();s=century.apply(s,'p0',{action:'discard',values:['0:0','0:1','0:2']});expect(s.caravans[0].cubes).toEqual([10,0,0,0]);expect(s.current).toBe(1);});
 it('moves silver rewards only after the final gold and completes the whole final round',()=>{let s=century.create(players(2),2);s.gold=1;s.goals=[{id:'a',cost:[1,0,0,0],points:6},{id:'b',cost:[1,0,0,0],points:6},{id:'c',cost:[1,0,0,0],points:6}];s.caravans[0].orders=Array.from({length:5},(_,i)=>({id:`old-${i}`,cost:[0,0,0,0],points:1}));s=century.apply(s,'p0',{action:'claim',values:['a']});expect(s.gold).toBe(0);expect(s.caravans[0].gold).toBe(1);expect(s.caravans[0].silver).toBe(0);expect(s.finalRound).toBe(true);expect(s.finished).toBe(false);s=century.apply(s,'p1',{action:'claim',values:['b']});expect(s.caravans[1].silver).toBe(1);expect(s.finished).toBe(true);expect(s.winners).toEqual(['p0']);expect(centuryScore(s.caravans[0])).toBe(14);});
 it('breaks score ties for the later seat and rejects outsider commands without changing state',()=>{let s=century.create(players(2),4);s.finalRound=true;s.current=1;const before=JSON.stringify(s);expect(()=>century.apply(s,'outsider',{action:'rest',values:[]})).toThrow();expect(JSON.stringify(s)).toBe(before);s=century.apply(s,'p1',{action:'rest',values:[]});expect(s.winners).toEqual(['p1']);});
});
