import {describe,it,expect} from 'vitest';
import {applyMatch,createMatch,viewMatch} from '../src/core/room';
import {modules} from '../src/core/registry';
import type {GameKind,Player} from '../src/core/types';
const players:Player[]=Array.from({length:3},(_,i)=>({id:`player0${i}`,name:`玩家 ${i}`,avatar:'🦊'}));
describe('independent multiplayer boundary review for new games',()=>{
 it('returns a large accumulated market bonus in bounded network commands without trapping the turn',()=>{let match=createMatch('century',players);match.game.market[0].bonus=[45,0,0,0];const target=match.game.market[0].card.id;match=applyMatch(match,'century',players,players[0].id,{action:'acquire',values:[target]},'acquire-bonus',match.actorRevisions[players[0].id]);expect(match.game.phase).toBe('discard');let batches=0;while(match.game.phase==='discard'&&batches<10){const view=viewMatch(match,'century',players[0].id),a=view.view.actions.find(a=>a.id==='discard')!;expect(a.min).toBeLessThanOrEqual(32);match=applyMatch(match,'century',players,players[0].id,{action:a.id,values:a.choices.slice(0,a.min).map(c=>c.id)},`return-batch-${batches++}`,view.actionRevision);}expect(batches).toBeGreaterThan(1);expect(match.game.phase).toBe('action');expect(match.game.current).toBe(1);expect(match.game.caravans[0].cubes.reduce((a:number,b:number)=>a+b,0)).toBe(10);});
 it.each(['sushi','century','uno'] as GameKind[])('%s rejects outsider, forged selection, and unknown action without mutating a match',kind=>{for(let run=0;run<8;run++){const match=createMatch(kind,players),before=JSON.stringify(match);const actor=players.find(p=>viewMatch(match,kind,p.id).view.actions.length)!;const view=viewMatch(match,kind,actor.id),a=view.view.actions[0];expect(()=>applyMatch(match,kind,players,'outsider',{action:a.id,values:[]},'outside',view.actionRevision)).toThrow();expect(()=>applyMatch(match,kind,players,actor.id,{action:'forged-action',values:[]},'unknown',view.actionRevision)).toThrow();expect(()=>applyMatch(match,kind,players,actor.id,{action:a.id,values:['foreign-card']},'invalid-card',view.actionRevision)).toThrow();expect(JSON.stringify(match)).toBe(before);const projection=modules[kind].view(match.game,actor.id);projection.board.hand?.push?.({id:'injected'});projection.board.players?.splice?.(0,1);expect(JSON.stringify(match)).toBe(before);}});
 it('keeps simultaneous Sushi choices valid for others, then invalidates all old-hand requests at reveal',()=>{let match=createMatch('sushi',players);const first=players.map(p=>({id:p.id,view:viewMatch(match,'sushi',p.id)}));for(const [i,p]of first.entries()){const a=p.view.view.actions.find(a=>a.id==='pick')!;match=applyMatch(match,'sushi',players,p.id,{action:a.id,values:[a.choices[0].id]},'pick-'+i,p.view.actionRevision);if(i<2)expect(match.actorRevisions[first[i+1].id]).toBe(first[i+1].view.actionRevision);}for(const p of first){expect(match.actorRevisions[p.id]).toBeGreaterThan(p.view.actionRevision);const a=p.view.view.actions.find(a=>a.id==='pick')!;expect(()=>applyMatch(match,'sushi',players,p.id,{action:a.id,values:[a.choices[0].id]},'stale-'+p.id,p.view.actionRevision)).toThrow('牌局已变化');}});
});
