import {describe,it,expect} from 'vitest';
import {uno,unoWild4Legal,type UnoCard,type UnoState} from '../src/core/games/uno';
import {createMatch,applyMatch,viewMatch,normalizeGameOptions,validateMatchForRoom,type RoomInfo} from '../src/core/room';
const players=Array.from({length:3},(_,i)=>({id:`player0${i}`,name:`Player ${i}`,avatar:'🦊'}));
const card=(id:string,color:UnoCard['color'],value:UnoCard['value']):UnoCard=>({id,color,value});
function setup(legal=false):UnoState{const s=uno.create(players,7);s.current=0;s.phase='play';s.color='red';s.direction=1;s.drawn=null;s.discard=[card('top','red',3)];s.hands=[[card('w4','wild','wild4'),card('private-card',legal?'blue':'red',7),card('other','yellow',1)],[card('target','green',4)],[card('third','blue',8)]];s.deck=Array.from({length:30},(_,i)=>card('draw-'+i,'blue',i%10));return s;}
const act=(s:UnoState,index:number,action:string,values:string[]=[])=>uno.apply(s,players[index].id,{action,values});
const play4=(s:UnoState)=>act(s,0,'wild:w4',['green']);
describe('Color Dash +4 challenge',()=>{
 it('allows a bluff but does not leak its legality or the hand to other players',()=>{const original=setup(),before=JSON.stringify(original);expect(unoWild4Legal(original)).toBe(false);expect(uno.view(original,players[0].id).actions.some(a=>a.id==='wild:w4')).toBe(true);const s=play4(original);expect(JSON.stringify(original)).toBe(before);expect(s.phase).toBe('wild4');expect(uno.view(s,players[1].id).actions.map(a=>a.id)).toEqual(['accept4','challenge4']);for(const i of [1,2]){const text=JSON.stringify(uno.view(s,players[i].id));expect(text).not.toContain('private-card');expect(text).not.toContain('illegal');expect(text).not.toContain('wasLegal');}expect(()=>act(s,2,'accept4')).toThrow();});
 it('successful challenge penalizes the offender, shows evidence only to the challenger, and preserves their turn',()=>{let s=play4(setup());s=act(s,1,'challenge4');expect(s.hands[0]).toHaveLength(6);expect(s.hands[1]).toHaveLength(1);expect(s.phase).toBe('challengeResult');const privateView=uno.view(s,players[1].id).board.privateChallenge;expect(privateView.wasLegal).toBe(false);expect(privateView.previousColor).toBe('red');expect(privateView.hand.map((c:UnoCard)=>c.id)).toEqual(['private-card','other']);expect(uno.view(s,players[0].id).board.privateChallenge).toBeUndefined();expect(JSON.stringify(uno.view(s,players[2].id))).not.toContain('private-card');expect(()=>act(s,0,'confirmChallenge')).toThrow();s=act(s,1,'confirmChallenge');expect(s.phase).toBe('play');expect(s.current).toBe(1);expect(s.pendingWild4).toBeUndefined();expect(uno.view(s,players[1].id).board.privateChallenge).toBeUndefined();});
 it('failed challenge draws six and skips the challenger only after private confirmation',()=>{let s=play4(setup(true));s=act(s,1,'challenge4');expect(s.hands[1]).toHaveLength(7);expect(s.hands[0]).toHaveLength(2);expect(uno.view(s,players[1].id).board.privateChallenge.wasLegal).toBe(true);expect(s.current).toBe(1);s=act(s,1,'confirmChallenge');expect(s.current).toBe(2);expect(s.phase).toBe('play');});
 it('accepting a bluff applies four to the target without revealing the hand',()=>{let s=play4(setup());s=act(s,1,'accept4');expect(s.hands[1]).toHaveLength(5);expect(s.current).toBe(2);expect(s.hands[0]).toHaveLength(2);expect(uno.view(s,players[1].id).board.privateChallenge).toBeUndefined();});
 it.each(['accept4','challenge4'])('settles a final +4 only after %s penalties are counted',resolution=>{let s=setup(true);s.hands[0]=[card('w4','wild','wild4')];s=play4(s);expect(s.finished).toBe(false);expect(s.phase).toBe('wild4');s=act(s,1,resolution);if(resolution==='challenge4'){expect(s.phase).toBe('challengeResult');s=act(s,1,'confirmChallenge');}expect(s.hands[1]).toHaveLength(resolution==='accept4'?5:7);expect(s.phase).toBe('roundEnd');expect(s.roundWinner).toBe(players[0].id);const total=s.hands.flat().reduce((n,c)=>n+(typeof c.value==='number'?c.value:c.color==='wild'?50:20),0);expect(s.roundPoints).toBe(total);expect(s.scores[0]).toBe(total);});
});
describe('manual last-card call without timing races',()=>{
 const oneLeft=()=>{const s=setup();s.hands[0]=[card('play','red',4),card('last','blue',5)];return act(s,0,'play',['play']);};
 it('requires the outgoing player to choose whether to call before the next player can act',()=>{let s=oneLeft();expect(s.phase).toBe('unoCall');expect(uno.view(s,players[0].id).actions.map(a=>a.id)).toEqual(['callUno','skipUno']);expect(uno.view(s,players[1].id).actions).toEqual([]);expect(()=>act(s,1,'draw')).toThrow();s=act(s,0,'callUno');expect(s.phase).toBe('play');expect(s.called?.[players[0].id]).toBe(true);expect(()=>act(s,1,'catchUno')).toThrow();});
 it('allows all other players to respond and penalizes a missed call exactly once',()=>{let s=act(oneLeft(),0,'skipUno');expect(s.phase).toBe('unoCatch');expect(()=>act(s,1,'draw')).toThrow();s=act(s,1,'passUno');expect(uno.view(s,players[1].id).actions).toEqual([]);s=act(s,2,'catchUno');expect(s.hands[0]).toHaveLength(3);expect(s.phase).toBe('play');expect(s.current).toBe(1);expect(()=>act(s,1,'catchUno')).toThrow();});
 it('closes the opportunity after all responders pass and rejects a later catch',()=>{let s=act(oneLeft(),0,'skipUno');s=act(s,1,'passUno');s=act(s,2,'passUno');expect(s.phase).toBe('play');expect(s.hands[0]).toHaveLength(1);expect(()=>act(s,2,'catchUno')).toThrow();});
 it('retains original +4 evidence even when a missed call adds cards before a challenge',()=>{let s=setup();s.hands[0]=[card('w4','wild','wild4'),card('original-red','red',6)];s=play4(s);s=act(s,0,'skipUno');s=act(s,2,'catchUno');expect(s.phase).toBe('wild4');s=act(s,1,'challenge4');expect(uno.view(s,players[1].id).board.privateChallenge.hand.map((c:UnoCard)=>c.id)).toEqual(['original-red']);expect(s.hands[0]).toHaveLength(7);});
 it('deduplicates a network catch retry and keeps independent responders current',()=>{let match=createMatch('uno',players);match.game=act(oneLeft(),0,'skipUno');const first=viewMatch(match,'uno',players[1].id),second=viewMatch(match,'uno',players[2].id);match=applyMatch(match,'uno',players,players[1].id,{action:'passUno',values:[]},'pass-1',first.actionRevision);expect(viewMatch(match,'uno',players[2].id).actionRevision).toBe(second.actionRevision);match=applyMatch(match,'uno',players,players[2].id,{action:'catchUno',values:[]},'catch-1',second.actionRevision);const repeat=applyMatch(match,'uno',players,players[2].id,{action:'catchUno',values:[]},'catch-1',second.actionRevision);expect(repeat).toBe(match);expect(match.game.hands[0]).toHaveLength(3);});
});
describe('500-point match and checkpoints',()=>{
 it('defaults to a multi-round 500-point match',()=>{const s=uno.create(players,1);expect(s.mode).toBe('match');expect(uno.view(s,players[0].id).board.targetScore).toBe(500);});
 it('preserves points across rounds and restricts restarting to the round winner or room host',()=>{let s=setup();s.current=2;s.scores=[50,60,70];s.hands[2]=[card('finish','red',9)];s=act(s,2,'play',['finish']);expect(s.finished).toBe(false);expect(s.phase).toBe('roundEnd');const scores=[...s.scores];expect(scores[2]).toBeGreaterThan(70);expect(()=>act(s,1,'nextRound')).toThrow();expect(uno.view(s,players[0].id).actions.some(a=>a.id==='nextRound')).toBe(true);expect(uno.view(s,players[2].id).actions.some(a=>a.id==='nextRound')).toBe(true);s=act(s,2,'nextRound');expect(s.roundNumber).toBe(2);expect(s.scores).toEqual(scores);expect(s.deck.length+s.hands.flat().length+s.discard.length).toBe(108);expect(s.pendingWild4).toBeUndefined();expect(s.unoWindow).toBeUndefined();expect(s.roundResults).toHaveLength(1);});
 it('finishes at 500 and awards only the round winner the remaining-card points',()=>{let s=setup();s.scores=[490,100,30];s.hands=[[card('end','red',8)],[card('a','blue',5)],[card('b','green',6)]];s=act(s,0,'play',['end']);expect(s.finished).toBe(true);expect(s.scores).toEqual([501,100,30]);expect(s.winners).toEqual([players[0].id]);expect(uno.view(s,players[0].id).actions).toEqual([]);});
 it('retains explicit single-round mode and legacy checkpoints',()=>{for(const legacy of [false,true]){let s=setup();s.mode='single';if(legacy)delete s.mode;s.hands[0]=[card('end','red',4)];s=act(s,0,'play',['end']);expect(s.finished).toBe(true);expect(s.winners).toEqual([players[0].id]);}});
 it('validates mode options and refuses a mismatched checkpoint',()=>{expect(normalizeGameOptions('uno',{unoMode:'single',language:'en'},players[0].id)).toEqual({unoMode:'single',language:'en'});expect(()=>normalizeGameOptions('gems',{unoMode:'single'},players[0].id)).toThrow();const match=createMatch('uno',players,{unoMode:'single'});const room:RoomInfo={code:'ABC234',kind:'uno',mode:'lan',options:{unoMode:'single'},hostID:players[0].id,players:players.map(p=>({...p,connected:true,ready:true})),pending:[],started:true,revision:1};expect(validateMatchForRoom(match,room).game.mode).toBe('single');expect(()=>validateMatchForRoom({...match,game:{...match.game,mode:'match'}},room)).toThrow('存档模式');});
 it('restores a pending private challenge exactly through a JSON room checkpoint',()=>{const match=createMatch('uno',players);match.game=act(play4(setup()),1,'challenge4');const room:RoomInfo={code:'ABC234',kind:'uno',mode:'lan',hostID:players[0].id,players:players.map(p=>({...p,connected:true,ready:true})),pending:[],started:true,revision:1};const restored=validateMatchForRoom(JSON.parse(JSON.stringify(match)),room);expect(viewMatch(restored,'uno',players[1].id).view.board.privateChallenge.hand[0].id).toBe('private-card');expect(viewMatch(restored,'uno',players[2].id).view.board.privateChallenge).toBeUndefined();});
});

describe('optional +4 challenge switch',()=>{
 it('defaults to enabled for fresh games and checkpoints without the field',()=>{const s=uno.create(players,8);expect(uno.view(s,players[0].id).board.challengeEnabled).toBe(true);delete s.challengeEnabled;expect(uno.view(s,players[0].id).board.challengeEnabled).toBe(true);});
 it('when disabled, prevents a matching-color bluff and leaves the rejected state untouched',()=>{const s=setup();s.challengeEnabled=false;const before=JSON.stringify(s);expect(uno.view(s,players[0].id).actions.some(a=>a.id==='wild:w4')).toBe(false);expect(()=>play4(s)).toThrow();expect(JSON.stringify(s)).toBe(before);});
 it('when disabled, a legal +4 automatically draws four and skips with no private window',()=>{let s=setup(true);s.challengeEnabled=false;s=play4(s);expect(s.hands[1]).toHaveLength(5);expect(s.current).toBe(2);expect(s.phase).toBe('play');expect(s.pendingWild4).toBeUndefined();for(const p of players){const v=uno.view(s,p.id);expect(v.board.challengeEnabled).toBe(false);expect(v.board.privateChallenge).toBeUndefined();expect(v.actions.some(a=>a.id==='accept4'||a.id==='challenge4')).toBe(false);}expect(()=>act(s,1,'challenge4')).toThrow();});
 it('keeps the manual last-card call after an automatically resolved +4',()=>{let s=setup(true);s.challengeEnabled=false;s.hands[0]=[card('w4','wild','wild4'),card('last','blue',7)];s=play4(s);expect(s.hands[1]).toHaveLength(5);expect(s.phase).toBe('unoCall');s=act(s,0,'callUno');expect(s.phase).toBe('play');expect(s.current).toBe(2);});
 it('counts automatic final-card penalties before round scoring',()=>{let s=setup(true);s.challengeEnabled=false;s.hands[0]=[card('w4','wild','wild4')];s=play4(s);expect(s.phase).toBe('roundEnd');expect(s.hands[1]).toHaveLength(5);expect(s.scores[0]).toBe(s.hands.flat().reduce((n,c)=>n+(typeof c.value==='number'?c.value:c.color==='wild'?50:20),0));});
 it('persists false, canonicalizes the default, and rejects invalid or unrelated settings',()=>{expect(normalizeGameOptions('uno',{unoChallenge:false},players[0].id)).toEqual({unoChallenge:false});expect(normalizeGameOptions('uno',{unoChallenge:true},players[0].id)).toBeUndefined();for(const value of ['false',0,null])expect(()=>normalizeGameOptions('uno',{unoChallenge:value},players[0].id)).toThrow('质疑');expect(()=>normalizeGameOptions('gems',{unoChallenge:false},players[0].id)).toThrow('质疑');});
 it('restores disabled-challenge checkpoints and rejects a changed engine setting',()=>{const match=createMatch('uno',players,{unoChallenge:false}),room:RoomInfo={code:'ABC234',kind:'uno',mode:'lan',options:{unoChallenge:false},hostID:players[0].id,players:players.map(p=>({...p,ready:true,connected:true})),pending:[],started:true,revision:1};expect(validateMatchForRoom(JSON.parse(JSON.stringify(match)),room).game.challengeEnabled).toBe(false);expect(()=>validateMatchForRoom({...match,game:{...match.game,challengeEnabled:true}},room)).toThrow('质疑设置');expect(()=>validateMatchForRoom({...match,game:{...match.game,challengeEnabled:undefined}},room)).toThrow('质疑设置');});
});
