import { describe, expect, it } from 'vitest';
import { werewolf, werewolfPreset, werewolfVictory, standardWerewolf, type WerewolfState, type WolfRole } from '../src/core/games/werewolf';
import { werewolfHosted, type HostedWerewolfState } from '../src/core/games/werewolfHosted';
import { createMatch, normalizeGameOptions, optionsKey, roomLimits, validateMatchForRoom, type RoomInfo } from '../src/core/room';
import type { GameOptions, Player } from '../src/core/types';
const players=(n:number):Player[]=>Array.from({length:n},(_,i)=>({id:`wolf-option-${i}`,name:`Player ${i}`,avatar:'🦊'}));
function exile(state:WerewolfState,target:string){let s=state;for(const id of state.alive)s=standardWerewolf.apply(s,id,{action:'vote',values:[target]});return s;}
function standard(rule:'sides'|'parity'){const s=standardWerewolf.create(players(8),8,{werewolfPreset:'hunter',werewolfWin:rule});const roles:WolfRole[]=['wolf','wolf','villager','villager','seer','witch','hunter','villager'];s.roles=Object.fromEntries(s.players.map((p,i)=>[p.id,roles[i]]));s.stage='vote';s.electionPending=false;s.sheriff=null;return s;}
describe('werewolf role presets',()=>{
 it('preserves auto and supports exclusive hunter or guard configurations from 8 through 18 players',()=>{for(let n=6;n<=18;n++){const auto=werewolfPreset(n);expect(auto).toHaveLength(n);expect(auto.filter(r=>r==='wolf')).toHaveLength(Math.floor(n/3));expect(auto.includes('hunter')).toBe(n>=8);expect(auto.includes('guard')).toBe(n>=12);if(n>=8){for(const preset of ['hunter','guard'] as const){const roles=werewolfPreset(n,preset);expect(roles).toHaveLength(n);expect(roles.filter(r=>r==='wolf')).toHaveLength(Math.floor(n/3));expect(roles.filter(r=>r==='seer')).toHaveLength(1);expect(roles.filter(r=>r==='witch')).toHaveLength(1);expect(roles.filter(r=>r===preset)).toHaveLength(1);expect(roles.includes(preset==='hunter'?'guard':'hunter')).toBe(false);expect(roles.filter(r=>r==='villager')).toHaveLength(n-Math.floor(n/3)-3);}}}});
 it('rejects invalid presets and underpopulated specialized games at the engine boundary',()=>{expect(()=>werewolfPreset(7,'hunter')).toThrow();expect(()=>werewolfPreset(7,'guard')).toThrow();expect(()=>werewolfPreset(8,'bad' as any)).toThrow();expect(()=>standardWerewolf.create(players(7),1,{werewolfPreset:'guard'})).toThrow();expect(()=>werewolfHosted.create(players(8),1,{werewolfMode:'judge',moderatorID:players(8)[0].id,werewolfPreset:'hunter'})).toThrow();});
 it('applies the same selected composition and language across standard, judge and deal, excluding the judge',()=>{for(const preset of ['hunter','guard'] as const)for(const mode of ['standard','judge','deal'] as const){const ps=players(mode==='judge'?10:9),options:GameOptions={werewolfMode:mode,werewolfPreset:preset,werewolfWin:'parity',language:'en',...(mode!=='standard'?{moderatorID:ps[0].id}:{})};const s=werewolf.create(ps,14,options);expect(Object.keys(s.roles)).toHaveLength(9);expect(Object.values(s.roles).sort()).toEqual(werewolfPreset(9,preset).sort());expect(s.options?.werewolfPreset).toBe(preset);expect(s.options?.werewolfWin).toBe('parity');expect(s.options?.language).toBe('en');if(mode==='judge')expect(s.roles[ps[0].id]).toBeUndefined();const view=werewolf.view(s,ps[0].id);expect(view.board.preset).toBe(preset);expect(view.board.winRule).toBe('parity');}});
 it('preserves chosen configuration on dealer reshuffle',()=>{const ps=players(12);let s=werewolfHosted.create(ps,51,{werewolfMode:'deal',moderatorID:ps[0].id,werewolfPreset:'guard',werewolfWin:'parity',language:'en'});s=werewolfHosted.apply(s,ps[0].id,{action:'redeal',values:['confirm']});expect(s.dealNumber).toBe(2);expect(s.options.werewolfPreset).toBe('guard');expect(s.options.werewolfWin).toBe('parity');expect(Object.values(s.roles).includes('guard')).toBe(true);expect(Object.values(s.roles).includes('hunter')).toBe(false);});
});
describe('werewolf victory choice',()=>{
 it('distinguishes sides from parity and always gives good the all-wolves-out victory',()=>{expect(werewolfVictory(['wolf','wolf','villager','seer'],'parity')).toContain('人数平衡');expect(werewolfVictory(['wolf','wolf','villager','seer'],'sides')).toBeNull();expect(werewolfVictory(['wolf','seer','witch','hunter'],'sides')).toContain('屠边');expect(werewolfVictory(['wolf','seer','witch','hunter'],'parity')).toBeNull();expect(werewolfVictory(['seer','villager'],'parity')).toContain('好人');expect(()=>werewolfVictory(['wolf','villager'],'bad' as any)).toThrow();});
 it('standard parity ends at equality, while sides continues with both types of good alive',()=>{for(const rule of ['sides','parity'] as const){let s=standard(rule);s.alive=[0,1,2,4,5].map(i=>s.players[i].id);s=exile(s,s.players[5].id);expect(!!s.winner).toBe(rule==='parity');}});
 it('standard sides ends when villagers are gone, while parity continues when good outnumber wolves',()=>{for(const rule of ['sides','parity'] as const){let s=standard(rule);s.alive=[0,1,2,4,5,6].map(i=>s.players[i].id);s=exile(s,s.players[2].id);expect(!!s.winner).toBe(rule==='sides');}});
 it('resolves a dying hunter shot before testing parity',()=>{let s=standard('parity');s.alive=[0,1,2,4,6].map(i=>s.players[i].id);s=exile(s,s.players[6].id);expect(s.stage).toBe('hunter');expect(s.winner).toBeNull();s=standardWerewolf.apply(s,s.players[6].id,{action:'shoot',values:[s.players[0].id]});expect(s.winner).toBeNull();expect(s.alive).toHaveLength(3);});
 it('judge mode uses parity with the same ordering as standard',()=>{for(const rule of ['sides','parity'] as const){const ps=players(9);let s=werewolfHosted.create(ps,9,{werewolfMode:'judge',moderatorID:ps[0].id,werewolfPreset:'guard',werewolfWin:rule});s.roles={[ps[1].id]:'wolf',[ps[2].id]:'wolf',[ps[3].id]:'villager',[ps[4].id]:'seer',[ps[5].id]:'witch',[ps[6].id]:'guard',[ps[7].id]:'villager',[ps[8].id]:'villager'};s.alive=[1,2,3,4,5].map(i=>ps[i].id);s.stage='day';s.electionPending=false;s=werewolfHosted.apply(s,ps[0].id,{action:'judge-exile',values:[ps[5].id]});expect(!!s.winner).toBe(rule==='parity');if(rule==='parity')expect(s.stage).toBe('finished');}});
});
describe('trusted room rules and old saves',()=>{
 it('normalizes default options compatibly and enforces mode-specific room size',()=>{const host=players(1)[0].id;expect(optionsKey('werewolf',{},host)).toBe(optionsKey('werewolf',{werewolfPreset:'auto',werewolfWin:'sides'},host));expect(roomLimits('werewolf',{werewolfPreset:'guard'})).toEqual({min:8,max:18});expect(roomLimits('werewolf',{werewolfMode:'judge',werewolfPreset:'hunter'})).toEqual({min:9,max:19});expect(roomLimits('werewolf',{werewolfMode:'judge',werewolfPreset:'auto'})).toEqual({min:7,max:19});expect(()=>normalizeGameOptions('uno',{werewolfWin:'parity'},host)).toThrow();expect(()=>normalizeGameOptions('werewolf',{werewolfPreset:'impostor'},host)).toThrow();});
 it('retains rules in trusted checkpoints and rejects mismatched engine rules',()=>{const ps=players(9),options:GameOptions={werewolfMode:'standard',werewolfPreset:'guard',werewolfWin:'parity',language:'en'},match=createMatch('werewolf',ps,options),room:RoomInfo={code:'ABC123',kind:'werewolf',mode:'cloud',hostID:ps[0].id,options,players:ps.map(p=>({...p,ready:true,connected:true})),pending:[],started:true,revision:1};expect(validateMatchForRoom(match,room).game.options.werewolfWin).toBe('parity');const altered=structuredClone(match);altered.game.options.werewolfWin='sides';expect(()=>validateMatchForRoom(altered,room)).toThrow();});
 it('allows legacy auto/sides standard saves with no engine options',()=>{const ps=players(9),match=createMatch('werewolf',ps),room:RoomInfo={code:'ABC123',kind:'werewolf',mode:'cloud',hostID:ps[0].id,players:ps.map(p=>({...p,ready:true,connected:true})),pending:[],started:true,revision:1};delete match.game.options;expect(()=>validateMatchForRoom(match,room)).not.toThrow();});
});
