import { describe, expect, it } from 'vitest';
import { codenames, validSignalClue, type SignalsState, type SignalTeam } from '../src/core/games/codenames';
import { undercover, type UndercoverState } from '../src/core/games/undercover';
import { SIGNAL_WORDS, ODD_WORD_PAIRS } from '../src/core/games/wordBank';
import { applyMatch, createMatch, viewMatch } from '../src/core/room';
import type { Player } from '../src/core/types';
const players=(n:number):Player[]=>Array.from({length:n},(_,i)=>({id:`word-player-${i}`,name:`Player ${i}`,avatar:'🦊'}));
const captain=(s:SignalsState,team=s.turn)=>s.players.find((p,i)=>s.teams[i]===team&&s.captains.includes(p.id))!.id;
const operative=(s:SignalsState,team=s.turn)=>s.players.find((p,i)=>s.teams[i]===team&&!s.captains.includes(p.id))!.id;
const clue=(s:SignalsState,count='1')=>codenames.apply(s,captain(s),{action:'clue',values:[count],text:s.language==='en'?'Sky':'天空'});
const reveal=(s:SignalsState,identity:string)=>codenames.apply(s,operative(s),{action:'guess',values:[s.cards.find(c=>!c.revealed&&c.identity===identity)!.id]});
describe('bilingual word banks',()=>{
 it('contains unique translated neutral words and distinct paired words',()=>{expect(SIGNAL_WORDS.length).toBeGreaterThanOrEqual(150);expect(ODD_WORD_PAIRS.length).toBeGreaterThanOrEqual(80);for(const i of [0,1])expect(new Set(SIGNAL_WORDS.map(p=>p[i])).size).toBe(SIGNAL_WORDS.length);for(const pair of ODD_WORD_PAIRS){expect(pair[0][0]).not.toBe(pair[1][0]);expect(pair[0][1]).not.toBe(pair[1][1]);}expect(SIGNAL_WORDS.every(pair=>pair.every(Boolean))).toBe(true);});
});
describe('Secret Signals',()=>{
 it('deals a deterministic 5 by 5 grid with 9 starting agents, 8 opponents, 7 bystanders and 1 assassin',()=>{for(const n of [4,7,12]){const s=codenames.create(players(n),42,{language:'en'});expect(s).toEqual(codenames.create(players(n),42,{language:'en'}));expect(s.cards).toHaveLength(25);expect(new Set(s.cards.map(c=>c.word)).size).toBe(25);expect(s.cards.filter(c=>c.identity===s.turn)).toHaveLength(9);expect(s.cards.filter(c=>c.identity!=='neutral'&&c.identity!=='assassin'&&c.identity!==s.turn)).toHaveLength(8);expect(s.cards.filter(c=>c.identity==='neutral')).toHaveLength(7);expect(s.cards.filter(c=>c.identity==='assassin')).toHaveLength(1);expect(s.captains).toHaveLength(2);expect(s.cards.every(c=>/^[A-Za-z]+$/.test(c.word))).toBe(true);}});
 it('gives both captains the key but leaks no unrevealed identities to operatives',()=>{const s=codenames.create(players(6),4);for(const p of s.players){const view=codenames.view(s,p.id);for(const card of view.board.cards)expect(Object.hasOwn(card,'identity')).toBe(s.captains.includes(p.id));}expect(codenames.view(s,'outside').board).toEqual({});const copy=codenames.view(s,captain(s));copy.board.cards[0].identity='edited';expect(s.cards[0].identity).not.toBe('edited');});
 it('enforces captain and team privileges, one-word clues and strict clue matching',()=>{const s=codenames.create(players(4),7,{language:'en'});expect(()=>codenames.apply(s,operative(s),{action:'clue',values:['1'],text:'Sky'})).toThrow();expect(()=>codenames.apply(s,captain(s),{action:'clue',values:['1'],text:s.cards[0].word})).toThrow();for(const bad of ['',undefined,'two words','123','A'.repeat(33),'<script>'])expect(()=>validSignalClue(s,bad)).toThrow();const next=clue(s);expect(next.phase).toBe('guess');expect(next.limit).toBe(2);expect(()=>codenames.apply(next,captain(next),{action:'guess',values:[next.cards[0].id]})).toThrow();expect(()=>codenames.apply(next,operative(next,next.turn==='red'?'blue':'red'),{action:'guess',values:[next.cards[0].id]})).toThrow();});
 it('permits the extra guess, blocks passing before first guess, and ends at the limit',()=>{let s=clue(codenames.create(players(4),8));const team=s.turn;expect(codenames.view(s,operative(s)).actions.some(a=>a.id==='stop')).toBe(false);s=reveal(s,s.turn);expect(s.turn).toBe(team);expect(codenames.view(s,operative(s)).actions.some(a=>a.id==='stop')).toBe(true);s=reveal(s,s.turn);expect(s.turn).not.toBe(team);expect(s.phase).toBe('clue');});
 it('zero and unlimited clues permit more guesses, with a manual stop after a correct guess',()=>{for(const count of ['0','unlimited']){let s=clue(codenames.create(players(4),6),count);expect(s.limit).toBeNull();const team=s.turn;for(let i=0;i<3;i++)s=reveal(s,team);expect(s.turn).toBe(team);s=codenames.apply(s,operative(s),{action:'stop',values:[]});expect(s.turn).not.toBe(team);}});
 it('ends the turn on bystanders and opponents, loses immediately on assassin, and can win on an opponent turn',()=>{for(const identity of ['neutral','opponent']){let s=clue(codenames.create(players(4),5));const team=s.turn;s=reveal(s,identity==='opponent'?(team==='red'?'blue':'red'):identity);expect(s.turn).not.toBe(team);expect(s.finished).toBe(false);}let s=clue(codenames.create(players(4),5));const losing=s.turn;s=reveal(s,'assassin');expect(s.finished).toBe(true);expect(s.winnerTeam).not.toBe(losing);expect(codenames.view(s,operative(s)).board.cards.every((c:any)=>c.identity)).toBe(true);
 s=clue(codenames.create(players(4),11));const enemy:SignalTeam=s.turn==='red'?'blue':'red';const cards=s.cards.filter(c=>c.identity===enemy);cards.slice(1).forEach(c=>c.revealed=true);s=reveal(s,enemy);expect(s.finished).toBe(true);expect(s.winnerTeam).toBe(enemy);});
 it('finishes a full team win while preserving chosen word language',()=>{let s=clue(codenames.create(players(4),15,{language:'zh'}),'unlimited');const team=s.turn;for(let i=0;i<9;i++)s=reveal(s,team);expect(s.finished).toBe(true);expect(s.winners).toHaveLength(2);expect(s.cards.every(c=>/[\u3400-\u9fff]/.test(c.word))).toBe(true);expect(codenames.view(s,captain(s)).actions).toEqual([]);});
 it('passes free text through real match validation and rejects stale concurrent guesses',()=>{const roster=players(6);let match=createMatch('codenames',roster,{language:'en'});const cap=captain(match.game);match=applyMatch(match,'codenames',roster,cap,{action:'clue',values:['1'],text:'Sky'},'clue-1',match.actorRevisions[cap]);expect(match.game.clue.word).toBe('Sky');const actor=operative(match.game),other=roster.find((p,i)=>p.id!==actor&&match.game.teams[i]===match.game.turn&&!match.game.captains.includes(p.id))!.id,revision=match.actorRevisions[other],card=match.game.cards.find((c:any)=>c.identity===match.game.turn);match=applyMatch(match,'codenames',roster,actor,{action:'guess',values:[card.id]},'guess-1',match.actorRevisions[actor]);expect(()=>applyMatch(match,'codenames',roster,other,{action:'guess',values:[card.id]},'guess-stale',revision)).toThrow();});
});
describe('Odd Word Out',()=>{
 it('deals only the viewer word, hides even their own role, and preserves English pairs',()=>{for(const n of [3,6,7,10,12]){const s=undercover.create(players(n),35,{language:'en'});expect(s.roles.filter(r=>r==='odd')).toHaveLength(n<=6?1:n<=10?2:3);expect(s).toEqual(undercover.create(players(n),35,{language:'en'}));for(const p of s.players){const view=undercover.view(s,p.id),me=s.players.findIndex(x=>x.id===p.id),otherWord=s.words[s.roles[me]==='common'?1:0];expect(view.board.word).toBe(s.words[s.roles[me]==='common'?0:1]);expect(view.board.players.every((p:any)=>!Object.hasOwn(p,'role')&&!Object.hasOwn(p,'word'))).toBe(true);expect(JSON.stringify(view)).not.toContain(otherWord);}}});
 it('acknowledges words without introducing turns, voting or a terminal reveal',()=>{let s=undercover.create(players(12),9);for(const p of s.players)s=undercover.apply(s,p.id,{action:'ready',values:[]});expect(s.ready.every(Boolean)).toBe(true);for(const p of s.players){const v=undercover.view(s,p.id);expect(v.finished).toBe(false);expect(v.actions).toEqual([]);expect(v.board).not.toHaveProperty('words');expect(v.board).not.toHaveProperty('ownVote');}const before=structuredClone(s);for(const action of ['ready','described','vote','cancel_vote'])expect(()=>undercover.apply(s,s.players[0].id,{action,values:[]})).toThrow();expect(s).toEqual(before);});
 it('reopens legacy finished and voting checkpoints without exposing identities or vote history',()=>{for(const phase of ['vote','defend','describe'] as const){const s=undercover.create(players(4),1);s.phase=phase;s.finished=true;s.lastVotes={[s.players[0].id]:s.players[1].id};s.history=['SECRET VOTE'];for(const p of s.players){const v=undercover.view(JSON.parse(JSON.stringify(s)),p.id);expect(v.finished).toBe(false);expect(v.board.phase).toBe('deal');expect(JSON.stringify(v)).not.toContain('SECRET VOTE');expect(v.board.players.every((p:{role?:string})=>!p.role)).toBe(true);}const spectator=undercover.view(s,'',true);for(const word of s.words)expect(JSON.stringify(spectator)).not.toContain(word);}});
 it('allows simultaneous acknowledgements using actor revisions',()=>{const roster=players(4);let m=createMatch('undercover',roster);const revision=m.actorRevisions[roster[1].id];m=applyMatch(m,'undercover',roster,roster[0].id,{action:'ready',values:[]},'ack-0',m.actorRevisions[roster[0].id]);expect(m.actorRevisions[roster[1].id]).toBe(revision);m=applyMatch(m,'undercover',roster,roster[1].id,{action:'ready',values:[]},'ack-1',revision);expect(viewMatch(m,'undercover',roster[1].id).view.board.ready).toBe(true);});
});

describe('Secret Signals invalid-clue procedure',()=>{
 it('lets the current captain concede and gives only the opponent captain an optional compensating reveal',()=>{let s=clue(codenames.create(players(4),81));const first=s.turn;s=codenames.apply(s,captain(s),{action:'invalid_clue',values:[]});expect(s.turn).not.toBe(first);expect(s.phase).toBe('penalty');const a=codenames.view(s,captain(s)).actions.find(a=>a.id==='penalty_cover')!;expect(a.choices).toHaveLength(8);expect(codenames.view(s,operative(s)).actions.map(a=>a.id)).toEqual(['mark']);const card=a.choices[0].id;s=codenames.apply(s,captain(s),{action:'penalty_cover',values:[card]});expect(s.cards.find(c=>c.id===card)?.revealed).toBe(true);expect(s.phase).toBe('clue');});
 it('allows declining compensation without giving operatives extra guesses',()=>{let s=clue(codenames.create(players(4),82));s=codenames.apply(s,captain(s),{action:'invalid_clue',values:[]});s=codenames.apply(s,captain(s),{action:'skip_penalty',values:[]});expect(s.phase).toBe('clue');expect(s.cards.some(c=>c.revealed)).toBe(false);});
});
