import {useEffect, useRef, useState, type FormEvent, type KeyboardEvent as ReactKeyboardEvent} from 'react';
import type {Action, Command, GameView} from '../core/types';
import {t, useLocale} from '../i18n';
import {DrawGuessCanvas} from './DrawGuessCanvas';
import './draw-guess-table.css';
import './draw-guess-private.css';

type Props={view:GameView;selfID:string;command:(command:Command)=>void;open:(action:Action,selected?:string[])=>void};
const colors=['#1f2937','#c2413b','#246a8b','#54824d','#7b5da7'];
export function DrawGuessTable({view,selfID,command,open}:Props){useLocale();const b=view.board,[guess,setGuess]=useState(''),[now,setNow]=useState(Date.now()),[confirmClear,setConfirmClear]=useState(false),[canvasVersion,setCanvasVersion]=useState(0),clearButton=useRef<HTMLButtonElement>(null),composing=useRef(false),stroke=view.actions.find((a:Action)=>a.id==='stroke'),choose=view.actions.find((a:Action)=>a.id==='choose'),clear=view.actions.find((a:Action)=>a.id==='clear');
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(timer);},[]);useEffect(()=>{setGuess('');setConfirmClear(false);composing.current=false;},[b.round,b.phase,selfID]);useEffect(()=>{if(!confirmClear)return;clearButton.current?.focus();const cancel=(event:KeyboardEvent)=>{if(event.key==='Escape')setConfirmClear(false);};window.addEventListener('keydown',cancel);return()=>window.removeEventListener('keydown',cancel);},[confirmClear]);const remaining=b.deadlineAt?Math.max(0,Math.ceil((b.deadlineAt-now)/1000)):0;
 const submitGuess=(event:FormEvent)=>{event.preventDefault();if(composing.current||!guess.trim()||!b.canGuess)return;command({action:'guess',values:[],text:guess});setGuess('');};
 const guardGuessComposition=(event:ReactKeyboardEvent<HTMLInputElement>)=>{if(event.key==='Enter'&&(composing.current||event.nativeEvent.isComposing||event.nativeEvent.keyCode===229))event.preventDefault();};
 return <div className="dg-table"><header className="dg-header"><div><small>{t('第')} {b.cycle} / {b.rounds} {t('轮')} · {t('第')} {b.round} {t('手')}</small><h2>{view.finished?t('本局结束'):t(view.instruction)}</h2></div><strong className={`dg-timer ${remaining<=10&&b.phase==='draw'?'urgent':''}`} aria-live="polite">{b.phase==='reveal'?t('揭晓中'):b.phase==='choose'?t('选词中'):`${remaining}s`}</strong></header>
 <section className="dg-scoreboard">{b.players.map((p:any)=><div key={p.id} className={`${p.id===selfID?'self':''} ${p.drawing?'drawing':''}`}><span>{p.avatar}</span><b>{p.name}{p.id===selfID?` · ${t('你')}`:''}</b><strong>{p.score}</strong>{p.drawing&&<small>{t('画手')}</small>}</div>)}</section>
 <section className="dg-stage"><DrawGuessCanvas key={`${b.round}:${b.phase}:${selfID}:${canvasVersion}`} strokes={b.strokes||[]} enabled={b.phase==='draw'&&b.isDrawer&&!view.spectating&&(b.strokes||[]).length<180} color={colors[(b.strokes||[]).length%colors.length]} onStroke={(points,color)=>command({action:'stroke',values:points.map(([x,y])=>`${x},${y}`),text:color})}/>{b.phase==='choose'&&b.isDrawer&&!view.spectating&&choose&&<div className="dg-private-choice"><small>{t('仅你可见')}</small><h3>{t('选择要画的词')}</h3><div>{choose.choices.map(choice=><button key={choice.id} onClick={()=>command({action:'choose',values:[choice.id]})}>{choice.title}</button>)}</div></div>}{b.phase==='choose'&&!b.isDrawer&&<div className="dg-waiting">{t('画手正在秘密选词')}</div>}{b.phase==='draw'&&b.isDrawer&&b.answer&&<div className="dg-private-answer"><small>{t('你的画词')}</small><strong>{b.answer}</strong></div>}{(b.phase==='reveal'||view.finished)&&b.answer&&<div className="dg-reveal"><small>{t('本轮答案')}</small><strong>{b.answer}</strong></div>}</section>
 <div className="dg-side">{clear&&<div className="dg-draw-tools"><span>{t('作画中')} · {remaining}s</span><button ref={clearButton} aria-describedby={confirmClear?'draw-clear-warning':undefined} onClick={()=>{if(confirmClear){command({action:'clear',values:[]});setCanvasVersion(value=>value+1);setConfirmClear(false);}else setConfirmClear(true);}}>{t(confirmClear?'确认清空画布':'清空画布')}</button>{confirmClear&&<small id="draw-clear-warning" role="status">{t('再次确认后清空本轮画布，按 Escape 取消')}</small>}</div>}
 <section className="dg-bottom"><div className="dg-guesses" aria-live="polite">{b.guesses.length?b.guesses.slice(-5).map((item:any,index:number)=><p key={index} className={item.correct?'correct':''}>{item.label}</p>):<p>{t('猜词会显示在这里')}</p>}</div>{b.canGuess&&!view.spectating&&<form className="dg-guess-form" onSubmit={submitGuess}><label>{t('猜一猜')}<input value={guess} maxLength={32} onChange={event=>setGuess(event.target.value)} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}} onKeyDown={guardGuessComposition} placeholder={t('输入你的答案')} autoComplete="off"/></label><button disabled={!guess.trim()}>{t('提交猜词')}</button></form>}</section></div>
 <details className="dg-rules"><summary>{t('查看本桌规则')}</summary><p>{t('画手从三个秘密词中选择一个，在倒计时内画图。其他玩家输入猜词；第一位猜中者得 2 分，画手得 1 分。每位玩家按设定轮数轮流作画，最高分获胜。')}</p><p>{t('画板和普通猜词公开同步；答案与备选词只发送给画手，并在本轮揭晓后显示。断线会暂停联机牌局，恢复后继续同一回合。')}</p></details></div>;
}
