import {useEffect,useRef,useState,type PointerEvent,type KeyboardEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,Eye,EyeOff,Undo2,Trash2,Send,BookOpen} from 'lucide-react';
import {decodeRelayStroke,encodeRelayStroke,RELAY_COLORS,RELAY_WIDTHS,RELAY_MAX_POINTS,RELAY_MAX_STROKES,type RelayEntry,type RelayPoint} from '../core/games/drawrelay';
import type {Command,GameView,Player} from '../core/types';
import {t,useLocale} from '../i18n';
import {useDialog} from './useDialog';
import './draw-relay-table.css';

type Props={view:GameView;selfID:string;command:(command:Command)=>void;onReplay?:()=>void};
const colorNames=['墨黑','珊瑚红','金黄','松绿','湖蓝','紫罗兰','白色'];
function Stroke({encoded}:{encoded:string}){const {color,width,points}=decodeRelayStroke(encoded);return <polyline points={points.length===1?[points[0],points[0]].map(p=>p.join(',')).join(' '):points.map(p=>p.join(',')).join(' ')} stroke={RELAY_COLORS[color]} strokeWidth={RELAY_WIDTHS[width]} fill="none" strokeLinecap="round" strokeLinejoin="round"/>;}
function RelayCanvas({strokes,enabled=false,onStroke,color=0,width=1}:{strokes:string[];enabled?:boolean;onStroke?:(encoded:string)=>void;color?:number;width?:number}){
 const [preview,setPreview]=useState<RelayPoint[]>([]),[cursor,setCursor]=useState<RelayPoint|null>(null),points=useRef<RelayPoint[]>([]),pointer=useRef<number|null>(null);
 const position=(event:PointerEvent<SVGSVGElement>):RelayPoint=>{const matrix=event.currentTarget.getScreenCTM();if(!matrix)return [0,0];const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());return [Math.round(Math.max(0,Math.min(1023,p.x))),Math.round(Math.max(0,Math.min(767,p.y)))];};
 const finish=(event:PointerEvent<SVGSVGElement>)=>{if(pointer.current!==event.pointerId)return;pointer.current=null;event.currentTarget.releasePointerCapture?.(event.pointerId);const path=points.current;points.current=[];setPreview([]);if(!enabled||!path.length)return;const sampled=path.length<=RELAY_MAX_POINTS?path:Array.from({length:RELAY_MAX_POINTS},(_,i)=>path[Math.round(i*(path.length-1)/(RELAY_MAX_POINTS-1))]);onStroke?.(encodeRelayStroke(sampled,color,width));};
 const keyboard=(event:KeyboardEvent<SVGSVGElement>)=>{if(!enabled)return;const current=cursor||[512,384] as RelayPoint,delta:Record<string,RelayPoint>={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-24],ArrowDown:[0,24]};if(event.key==='Enter'||event.key===' '){event.preventDefault();onStroke?.(encodeRelayStroke([current],color,width));setCursor(current);return;}const d=delta[event.key];if(!d)return;event.preventDefault();const next:RelayPoint=[Math.max(0,Math.min(1023,current[0]+d[0])),Math.max(0,Math.min(767,current[1]+d[1]))];setCursor(next);onStroke?.(encodeRelayStroke([current,next],color,width));};
 return <svg className={`relay-canvas ${enabled?'editable':''}`} viewBox="0 0 1023 767" role="img" aria-label={t('接龙画板')} aria-description={enabled?t('方向键作画，回车落点'):undefined} tabIndex={enabled?0:undefined} onKeyDown={keyboard} onBlur={()=>setCursor(null)} onPointerDown={event=>{if(!enabled||pointer.current!==null)return;pointer.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);points.current=[position(event)];setPreview([...points.current]);}} onPointerMove={event=>{if(pointer.current!==event.pointerId||points.current.length>=2048)return;const p=position(event),previous=points.current.at(-1)!;if(Math.hypot(p[0]-previous[0],p[1]-previous[1])<2)return;points.current.push(p);setPreview([...points.current]);}} onPointerUp={finish} onPointerCancel={event=>{if(pointer.current!==event.pointerId)return;pointer.current=null;points.current=[];setPreview([]);event.currentTarget.releasePointerCapture?.(event.pointerId);}}>
 <rect width="1023" height="767" fill="#fff"/>{strokes.map((encoded,i)=><Stroke key={`${i}:${encoded}`} encoded={encoded}/>)}{preview.length>0&&<polyline points={preview.map(p=>p.join(',')).join(' ')} stroke={RELAY_COLORS[color]} strokeWidth={RELAY_WIDTHS[width]} fill="none" strokeLinecap="round" strokeLinejoin="round"/>}{enabled&&cursor&&<circle cx={cursor[0]} cy={cursor[1]} r="12" fill="none" stroke="#658793" strokeWidth="3" strokeDasharray="5 4"/>}
 </svg>;
}
function Entry({entry}:{entry:RelayEntry}){return entry.skipped?<div className="relay-skipped">{t('上一步未完成')}</div>:entry.kind==='drawing'?<RelayCanvas strokes={entry.strokes||[]}/>:<blockquote className="relay-sentence">{entry.text}</blockquote>;}
function Editor({view,command}:{view:GameView;command:Props['command']}){
 const b=view.board,draft=b.draft as RelayEntry,[text,setText]=useState(draft.text||''),[submitWanted,setSubmitWanted]=useState(false),[color,setColor]=useState(0),[width,setWidth]=useState(1),[clearOpen,setClearOpen]=useState(false);
 const [sending,setSending]=useState<string|null>(null),[saveFailed,setSaveFailed]=useState(false),composing=useRef(false),sendRef=useRef(command);sendRef.current=command;
 const clearDialog=useDialog<HTMLDivElement>(clearOpen,()=>setClearOpen(false));
 const values=[String(b.step)],drawing=draft.kind==='drawing',saved=draft.text||'',valid=drawing?!!draft.strokes?.length:!!text.trim();
 // Wait for each acknowledged draft before sending the next edit or submission.
 useEffect(()=>{if(sending!==null&&sending===saved){setSending(null);setSaveFailed(false);}},[saved,sending]);
 useEffect(()=>{if(sending===null)return;const timer=setTimeout(()=>{setSending(null);setSaveFailed(true);setSubmitWanted(false);},5000);return()=>clearTimeout(timer);},[sending]);
 useEffect(()=>{if(drawing||b.submitted||composing.current)return;if(text===saved){if(submitWanted){setSubmitWanted(false);sendRef.current({action:'submit',values:[String(b.step)]});}return;}if(sending!==null||saveFailed)return;const timer=setTimeout(()=>{setSending(text);sendRef.current({action:'draft',values:[String(b.step)],text});},submitWanted?0:350);return()=>clearTimeout(timer);},[text,saved,drawing,submitWanted,b.submitted,b.step,sending,saveFailed]);
 return <><div className={`relay-work ${drawing?'draw':'write'}`}>
 {b.previous&&<section className="relay-previous"><small>{t(drawing?'上一页的句子':'上一页的画')}</small><Entry entry={b.previous}/></section>}
 <section className="relay-draft">{drawing?<><div className="relay-paper"><RelayCanvas strokes={draft.strokes||[]} enabled={!b.submitted&&(draft.strokes?.length||0)<RELAY_MAX_STROKES} color={color} width={width} onStroke={encoded=>command({action:'stroke',values:[String(b.step),encoded]})}/></div>{!b.submitted&&<div className="relay-tools"><div className="relay-palette" role="group" aria-label={t('画笔')}>{RELAY_COLORS.map((value,i)=><button key={value} style={{'--ink':value} as React.CSSProperties} aria-label={t(colorNames[i])} aria-pressed={color===i} onClick={()=>setColor(i)}><i/>{color===i&&<Check size={16}/>}</button>)}</div><div className="relay-brush-row"><label>{t('笔刷粗细')}<select aria-label={t('笔刷粗细')} value={width} onChange={e=>setWidth(Number(e.target.value))}>{['细笔','中笔','粗笔'].map((name,i)=><option key={name} value={i}>{t(name)}</option>)}</select></label><button aria-label={t('撤销上一笔')} disabled={!draft.strokes?.length} onClick={()=>command({action:'undo',values})}><Undo2 size={18}/></button><button aria-label={t('清空画布')} disabled={!draft.strokes?.length} onClick={()=>setClearOpen(true)}><Trash2 size={18}/></button><small aria-label={t('笔迹数量')}>{draft.strokes?.length||0}/{RELAY_MAX_STROKES}</small></div></div>}</>:<label className="relay-writing"><span>{t(b.step?'你的描述':'开场句')}</span><textarea value={text} rows={3} maxLength={240} disabled={b.submitted} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={e=>{composing.current=false;setText([...e.currentTarget.value].slice(0,120).join(''));}} onChange={e=>{setSaveFailed(false);setText([...e.target.value].slice(0,120).join(''));}} autoComplete="off"/><span className="relay-draft-status"><small role="status">{t(saveFailed?'草稿尚未保存':text===saved?'草稿已保存':'正在保存草稿')}</small><small>{[...text].length}/120</small></span>{saveFailed&&<button type="button" onClick={()=>setSaveFailed(false)}>{t('重试保存')}</button>}</label>}</section></div>
 {!b.submitted&&<footer className="relay-submit"><small>{t('提交后不能修改')}</small><button className="primary" disabled={!valid||submitWanted} onClick={()=>drawing||text===saved?command({action:'submit',values}):setSubmitWanted(true)}><Send size={17}/>{t('传给下一位')}</button></footer>}
 {clearOpen&&<div className="modal-shade"><div ref={clearDialog} className="panel relay-clear-dialog" role="dialog" aria-modal="true" aria-label={t('清空这幅画？')} tabIndex={-1}><h2>{t('清空这幅画？')}</h2><p>{t('清空后不能恢复')}</p><div><button onClick={()=>setClearOpen(false)}>{t('保留画作')}</button><button className="primary" onClick={()=>{command({action:'clear',values});setClearOpen(false);}}>{t('确认清空')}</button></div></div></div>}
 </>;
}
export function DrawRelayTable({view,selfID,command,onReplay}:Props){useLocale();const b=view.board,[revealed,setRevealed]=useState(false),[now,setNow]=useState(Date.now());const players=b.players as (Player&{ready:boolean})[];
 useEffect(()=>{if(!b.deadlineAt)return;const timer=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(timer);},[b.deadlineAt]);
 const seconds=Math.max(0,Math.ceil((b.deadlineAt-now)/1000)),gallery=b.gallery as {book:number;page:number;entry:RelayEntry}|undefined;
 return <section className={`relay-table ${gallery?'gallery':''}`}><header className="relay-heading"><div><small>{gallery?`${b.totalSteps} ${t('画册')}`:`${t('第几步')} ${b.step+1} / ${b.totalSteps}`}</small><h2>{t(view.phase)}</h2></div>{!gallery&&<strong className={`relay-time ${seconds<=10&&b.deadlineAt?'urgent':''}`}>{b.seconds?b.deadlineAt?`${seconds}s`:'—':t('不限时')}</strong>}</header>
 {!gallery&&<div className="relay-progress" aria-label={t('已提交')}>{players.map(p=><span className={`${p.ready?'ready':''} ${p.id===selfID?'self':''}`} key={p.id} title={p.name}><i>{p.avatar}</i><b>{p.name}</b>{p.ready?<Check size={14}/>:<small>·</small>}</span>)}</div>}
 {gallery?<><div className="relay-gallery-controls"><label>{t('画册')}<select aria-label={t('更换画册')} value={gallery.book} disabled={view.spectating} onChange={e=>command({action:'album',values:[e.target.value]})}>{players.map((p,i)=><option key={p.id} value={i}>{i+1}. {p.name}</option>)}</select></label><span>{gallery.page+1} / {b.totalSteps}</span></div><article className="relay-gallery-page"><header><span>{players.find(p=>p.id===gallery.entry.author)?.avatar} {players.find(p=>p.id===gallery.entry.author)?.name}</span><small>{gallery.entry.skipped?t('未完成'):gallery.entry.timedOut?t('到时保存'):''}</small></header><Entry entry={gallery.entry}/></article><footer className="relay-gallery-footer"><button aria-label={t('上一页')} disabled={view.spectating||gallery.page===0} onClick={()=>command({action:'page',values:[String(gallery.page-1)]})}><ArrowLeft size={18}/>{t('上一页')}</button><button aria-label={t('下一页')} disabled={view.spectating||gallery.page===b.totalSteps-1} onClick={()=>command({action:'page',values:[String(gallery.page+1)]})}>{t('下一页')}<ArrowRight size={18}/></button></footer>{onReplay&&<button className="relay-replay" onClick={onReplay}>{t('再玩接龙')}</button>}</>:view.spectating?<div className="relay-sealed"><BookOpen size={42}/><p>{t(view.instruction)}</p></div>:!revealed?<div className="relay-sealed"><BookOpen size={42}/><button className="primary" onClick={()=>setRevealed(true)}><Eye size={18}/>{t('查看我的接龙页')}</button><small>{t('仅你可见')}</small></div>:<><div className="relay-private-bar"><p role="status">{t(b.submitted?'已提交，等待其他玩家':'仅你可见')}</p><button aria-label={t('隐藏接龙页')} onClick={()=>setRevealed(false)}><EyeOff size={18}/></button></div><Editor view={view} command={command}/></>}
 </section>;
}
