import {useEffect, useRef, useState, type FormEvent, type KeyboardEvent as ReactKeyboardEvent, type PointerEvent} from 'react';
import type {Action, Command, GameView} from '../core/types';
import {t, useLocale} from '../i18n';
import './draw-guess-table.css';
import './draw-guess-private.css';

type Props={view:GameView;selfID:string;command:(command:Command)=>void;open:(action:Action,selected?:string[])=>void};
type Stroke={points:[number,number][];color:string};
const colors=['#1f2937','#c2413b','#246a8b','#54824d','#7b5da7'];
function Canvas({strokes,enabled,onStroke}:{strokes:Stroke[];enabled:boolean;onStroke:(points:[number,number][])=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),points=useRef<[number,number][]>([]),keyboardPoint=useRef<[number,number]>([500,500]);
 useEffect(()=>{const node=canvas.current;if(!node)return;const draw=()=>{const rect=node.getBoundingClientRect(),scale=Math.max(1,devicePixelRatio||1);node.width=Math.round(rect.width*scale);node.height=Math.round(rect.height*scale);const ctx=node.getContext('2d')!;ctx.scale(scale,scale);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=Math.max(3,Math.min(8,rect.width/70));ctx.clearRect(0,0,rect.width,rect.height);for(const stroke of strokes){ctx.strokeStyle=stroke.color;ctx.beginPath();stroke.points.forEach(([x,y],i)=>{const px=x/1000*rect.width,py=y/1000*rect.height;i?ctx.lineTo(px,py):ctx.moveTo(px,py);});ctx.stroke();}};draw();const observer=new ResizeObserver(draw);observer.observe(node);return()=>observer.disconnect();},[strokes]);
 const point=(event:PointerEvent<HTMLCanvasElement>):[number,number]=>{const rect=event.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1000,Math.round((event.clientX-rect.left)/rect.width*1000))),Math.max(0,Math.min(1000,Math.round((event.clientY-rect.top)/rect.height*1000)))];};
 const finish=(event:PointerEvent<HTMLCanvasElement>)=>{if(!enabled||!points.current.length)return;event.currentTarget.releasePointerCapture?.(event.pointerId);const final=points.current;points.current=[];if(final.length===1)final.push(final[0]);onStroke(final.filter((_,i)=>i===0||i===final.length-1||i%Math.ceil(final.length/30)===0));};
 const keyboardDraw=(event:ReactKeyboardEvent<HTMLCanvasElement>)=>{if(!enabled)return;const delta:{[key:string]:[number,number]}={ArrowUp:[0,-40],ArrowDown:[0,40],ArrowLeft:[-40,0],ArrowRight:[40,0]};if(event.key==='Enter'||event.key===' '){event.preventDefault();onStroke([keyboardPoint.current,keyboardPoint.current]);return;}const move=delta[event.key];if(!move)return;event.preventDefault();const previous=keyboardPoint.current,next:[number,number]=[Math.max(0,Math.min(1000,previous[0]+move[0])),Math.max(0,Math.min(1000,previous[1]+move[1]))];keyboardPoint.current=next;onStroke([previous,next]);};
 return <canvas ref={canvas} className={`dg-canvas ${enabled?'dg-can-draw':''}`} aria-label={t(enabled?'作画区域':'共享画板')} aria-description={enabled?t('方向键作画，回车落点') : undefined} tabIndex={enabled?0:-1} onKeyDown={keyboardDraw} onPointerDown={event=>{if(!enabled)return;event.currentTarget.setPointerCapture(event.pointerId);points.current=[point(event)];}} onPointerMove={event=>{if(enabled&&points.current.length<96&&event.currentTarget.hasPointerCapture(event.pointerId))points.current.push(point(event));}} onPointerUp={finish} onPointerCancel={finish}/>;
}
export function DrawGuessTable({view,selfID,command,open}:Props){useLocale();const b=view.board,[guess,setGuess]=useState(''),[now,setNow]=useState(Date.now()),[confirmClear,setConfirmClear]=useState(false),clearButton=useRef<HTMLButtonElement>(null),stroke=view.actions.find((a:Action)=>a.id==='stroke'),choose=view.actions.find((a:Action)=>a.id==='choose'),clear=view.actions.find((a:Action)=>a.id==='clear');
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(timer);},[]);useEffect(()=>{setGuess('');setConfirmClear(false);},[b.round,b.phase,selfID]);useEffect(()=>{if(!confirmClear)return;clearButton.current?.focus();const cancel=(event:KeyboardEvent)=>{if(event.key==='Escape')setConfirmClear(false);};window.addEventListener('keydown',cancel);return()=>window.removeEventListener('keydown',cancel);},[confirmClear]);const remaining=b.deadlineAt?Math.max(0,Math.ceil((b.deadlineAt-now)/1000)):0;
 const submitGuess=(event:FormEvent)=>{event.preventDefault();if(!guess.trim()||!b.canGuess)return;command({action:'guess',values:[],text:guess});setGuess('');};
 return <div className="dg-table"><header className="dg-header"><div><small>{t('第')} {b.cycle} / {b.rounds} {t('轮')} · {t('第')} {b.round} {t('手')}</small><h2>{view.finished?t('本局结束'):t(view.instruction)}</h2></div><strong className={`dg-timer ${remaining<=10&&b.phase==='draw'?'urgent':''}`} aria-live="polite">{b.phase==='reveal'?t('揭晓中'):b.phase==='choose'?t('选词中'):`${remaining}s`}</strong></header>
 <section className="dg-scoreboard">{b.players.map((p:any)=><div key={p.id} className={`${p.id===selfID?'self':''} ${p.drawing?'drawing':''}`}><span>{p.avatar}</span><b>{p.name}{p.id===selfID?` · ${t('你')}`:''}</b><strong>{p.score}</strong>{p.drawing&&<small>{t('画手')}</small>}</div>)}</section>
 <section className="dg-stage"><Canvas strokes={b.strokes||[]} enabled={b.phase==='draw'&&b.isDrawer&&!view.spectating} onStroke={points=>command({action:'stroke',values:points.map(([x,y])=>`${x},${y}`),text:colors[(b.strokes||[]).length%colors.length]})}/>{b.phase==='choose'&&b.isDrawer&&!view.spectating&&choose&&<div className="dg-private-choice"><small>{t('仅你可见')}</small><h3>{t('选择要画的词')}</h3><div>{choose.choices.map(choice=><button key={choice.id} onClick={()=>command({action:'choose',values:[choice.id]})}>{choice.title}</button>)}</div></div>}{b.phase==='choose'&&!b.isDrawer&&<div className="dg-waiting">{t('画手正在秘密选词')}</div>}{b.phase==='draw'&&b.isDrawer&&b.answer&&<div className="dg-private-answer"><small>{t('你的画词')}</small><strong>{b.answer}</strong></div>}{(b.phase==='reveal'||view.finished)&&b.answer&&<div className="dg-reveal"><small>{t('本轮答案')}</small><strong>{b.answer}</strong></div>}</section>
 <div className="dg-side">{clear&&<div className="dg-draw-tools"><span>{t('作画中')} · {remaining}s</span><button ref={clearButton} aria-describedby={confirmClear?'draw-clear-warning':undefined} onClick={()=>{if(confirmClear){command({action:'clear',values:[]});setConfirmClear(false);}else setConfirmClear(true);}}>{t(confirmClear?'确认清空画布':'清空画布')}</button>{confirmClear&&<small id="draw-clear-warning" role="status">{t('再次确认后清空本轮画布，按 Escape 取消')}</small>}</div>}
 <section className="dg-bottom"><div className="dg-guesses" aria-live="polite">{b.guesses.length?b.guesses.slice(-5).map((item:any,index:number)=><p key={index} className={item.correct?'correct':''}>{item.label}</p>):<p>{t('猜词会显示在这里')}</p>}</div>{b.canGuess&&!view.spectating&&<form className="dg-guess-form" onSubmit={submitGuess}><label>{t('猜一猜')}<input value={guess} maxLength={32} onChange={event=>setGuess(event.target.value)} placeholder={t('输入你的答案')} autoComplete="off"/></label><button disabled={!guess.trim()}>{t('提交猜词')}</button></form>}</section></div>
 <details className="dg-rules"><summary>{t('查看本桌规则')}</summary><p>{t('画手从三个秘密词中选择一个，在倒计时内画图。其他玩家输入猜词；第一位猜中者得 2 分，画手得 1 分。每位玩家按设定轮数轮流作画，最高分获胜。')}</p><p>{t('画板和普通猜词公开同步；答案与备选词只发送给画手，并在本轮揭晓后显示。断线会暂停联机牌局，恢复后继续同一回合。')}</p></details></div>;
}
