import {useEffect,useState} from 'react';
import {ArrowUpFromLine,Check,PlusSquare,Share,Smartphone,X} from 'lucide-react';
import './install.css';
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function InstallButton(){
 const [show,setShow]=useState(false),[prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(()=>matchMedia('(display-mode: standalone)').matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);
 const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;
 useEffect(()=>{const capture=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPrompt);};const done=()=>{setInstalled(true);setShow(false);};window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',done);};},[]);
 const install=async()=>{if(prompt){await prompt.prompt();const choice=await prompt.userChoice;if(choice.outcome==='accepted')setInstalled(true);setPrompt(null);}else setShow(true);};
 return <><button className="install-button" onClick={()=>void install()}><Smartphone size={16}/>{installed?'已添加到主屏幕':isiOS?'添加到 iPhone 主屏幕':'添加到主屏幕'}{installed?<Check size={14}/>:<PlusSquare size={14}/>}</button>{show&&<div className="modal-shade install-shade" onClick={()=>setShow(false)}><section className="panel install-panel" role="dialog" aria-modal="true" aria-label="添加到主屏幕" onClick={e=>e.stopPropagation()}><header><h2>添加到主屏幕</h2><button className="icon" aria-label="关闭安装说明" onClick={()=>setShow(false)}><X/></button></header><div className="install-preview"><img src="/mocha-icon-180.png" alt="桌游图标"/><b>Mocha 桌游</b></div>{installed?<p>已在独立窗口中打开。</p>:<><ol className="install-steps"><li><span>1</span><div>用 <b>Safari</b> 打开此页面</div></li><li><span>2</span><div>点击 <Share size={18}/> <b>分享</b><small>部分版本先点“更多 ···”，再点“分享”</small></div></li><li><span>3</span><div>选择 <PlusSquare size={18}/> <b>添加到主屏幕</b><small>如有“作为网页 App 打开”，保持开启</small></div></li><li><span>4</span><div>点 <b>添加</b>，从桌面图标进入</div></li></ol>{!isiOS&&<p className="install-other">Android 或电脑：也可以在浏览器菜单中选择“安装应用”。</p>}<small className="install-note">iPhone 需要在系统分享菜单中完成添加。</small></>}</section></div>}</>;
}
