import { t } from '../i18n';
function tx<T>(value: T): T | string { return typeof value === 'string' ? t(value) : value; }
import { useEffect, useState, type CSSProperties } from 'react';
import type { Action, Command, GameView } from '../core/types';
import { SUSHI_INFO, sushiPlateScore, type SushiCard } from '../core/games/sushi';
import { SPICES, SPICE_SYMBOLS, spiceCardTitle, spiceText, type SpiceCard, type SpiceOrder } from '../core/games/century';
import { UNO_LABEL, unoTitle, type UnoCard } from '../core/games/uno';
import './new-games-table.css';
type Props = {
    view: GameView;
    selfID: string;
    command: (c: Command) => void;
    open: (a: Action, selected?: string[]) => void;
};
function Controls({ view, command, open, omit = [] }: Props & {
    omit?: string[];
}) { return <div className="ng-controls">{tx(view.actions.filter(a => !omit.includes(a.id) && !a.id.startsWith('wild:')).map(a => <button type="button" key={a.id} className="ng-action" onClick={() => a.choices.length ? open(a) : command({ action: a.id, values: [] })}>{tx(a.title)}</button>))}</div>; }
function Header({ view }: {
    view: GameView;
}) { return <header className="ng-heading"><span>{tx(view.phase)}</span><strong role="status">{tx(view.instruction)}</strong></header>; }
function Scoreboard({ view, selfID }: {
    view: GameView;
    selfID: string;
}) { return <div className="ng-players">{tx(view.board.players.map((p: any) => <div className={`ng-player ${p.id === selfID ? 'ng-self' : ''} ${p.id === view.board.current ? 'ng-current' : ''}`} key={p.id}><span className="ng-avatar">{tx(p.avatar)}</span><div><b>{p.name}{tx(p.id === selfID ? ' · 你' : '')}</b><small>{tx(view.kind === 'sushi' ? `${view.finished ? '已结算' : p.ready ? '✓ 已选' : '选牌中'} · 布丁 ${p.puddings + (view.finished ? 0 : p.table.filter((c: SushiCard) => c.kind === 'pudding').length)}` : view.kind === 'century' ? `${p.orderCount} 单 · 金 ${p.gold} / 银 ${p.silver}` : `${p.handCount} 张手牌${p.handCount === 1 ? ' · UNO!' : ''}`)}</small></div><strong>{tx(p.score)}<small>{" " + t("分")}</small></strong></div>))}</div>; }
function SushiFace({ card, selected, onClick, order, small = false }: {
    card: SushiCard;
    selected?: boolean;
    onClick?: () => void;
    order?: number;
    small?: boolean;
}) { const info = SUSHI_INFO[card.kind]; return <button type="button" disabled={!onClick} aria-label={tx(`${info.title}：${info.detail}`)} aria-pressed={onClick ? !!selected : undefined} className={`ng-sushi-card ${selected ? 'ng-selected' : ''} ${small ? 'ng-small' : ''}`} onClick={onClick}><span className="ng-food">{tx(info.symbol)}</span><b>{tx(info.title)}</b>{tx(!small && <small>{tx(info.detail)}</small>)}{tx(order !== undefined && <span className="ng-order">{tx(order)}</span>)}</button>; }
function SushiTable(props: Props) { const { view, command, selfID } = props, b = view.board, [selected, setSelected] = useState<string[]>([]), pick = view.actions.find(a => a.id === 'pick'); useEffect(() => setSelected([]), [b.round, b.step, selfID]); const shown = b.selected || selected; const toggle = (id: string) => setSelected(old => old.includes(id) ? old.filter(v => v !== id) : old.length < (pick?.max || 1) ? [...old, id] : [id]); const valid = pick && selected.length >= pick.min && selected.length <= pick.max; return <div className="ng-table ng-sushi"><Header view={view}/><Scoreboard view={view} selfID={selfID}/><section className="ng-panel"><h3>{t("传到你面前的手牌") + " "}<small>{tx(b.hand.length)}{" " + t("张 · 仅你可见")}</small></h3><div className="ng-hand">{tx((b.hand as SushiCard[]).map(c => <SushiFace key={c.id} card={c} selected={shown.includes(c.id)} order={shown.includes(c.id) ? shown.indexOf(c.id) + 1 : undefined} onClick={pick ? () => toggle(c.id) : undefined}/>))}</div><div className="ng-controls">{tx(pick && <button className="ng-action" type="button" disabled={!valid} onClick={() => { command({ action: 'pick', values: selected }); setSelected([]); }}>{t("确认") + " "}{tx(selected.length)}{" " + t("张")}{tx(pick.max === 2 ? ' · 可用筷子选两张' : '')}</button>)}<Controls {...props} omit={['pick']}/></div>{tx(pick?.max === 2 && <p className="ng-hint">{t("选择顺序就是出牌顺序：先芥末、后握寿司才会三倍计分。筷子会传给下家。")}</p>)}</section><section className="ng-plates">{tx(b.players.map((p: any) => <article className="ng-panel" key={p.id}><h3>{tx(p.avatar)} {p.name}<small>{t("盘面") + " "}{tx(sushiPlateScore(p.table))}{" " + t("分 · 卷数另算")}</small></h3><div className="ng-plate">{tx(p.table.length ? p.table.map((c: SushiCard) => <SushiFace key={c.id} card={c} small/>) : <p className="ng-hint">{t("等待大家同时揭晓第一道")}</p>)}</div></article>))}</section><details className="ng-rules"><summary>{t("计分与玩法")}</summary><p>{t("共三轮，每手同时选牌，余牌向左传递。最后一张自动揭晓。寿司卷按图标数排名：第一 6 分、第二 3 分；并列平分取整，并列第一不发第二名分。布丁留到三轮后：最多 +6、最少 −6，并列平分；两人局不扣布丁分。总分相同以布丁多者胜。")}</p><p>{t("天妇罗每两张 5 分；刺身每三张 10 分；饺子 1 / 3 / 6 / 10 / 15 分。握寿司玉子 1、三文鱼 2、鱿鱼 3 分，先放下的芥末令之后第一张握寿司分数乘三。数字版按基础 108 张牌组。")}</p></details></div>; }
const unoColors: Record<string, string> = { red: '#b73d48', yellow: '#936b19', green: '#2d826b', blue: '#376da6', wild: '#665482' };
function UnoFace({ card, onClick, drawn = false, selected = false }: {
    card: UnoCard;
    onClick?: () => void;
    drawn?: boolean;
    selected?: boolean;
}) { return <button type="button" disabled={!onClick} aria-pressed={onClick ? selected : undefined} className={`ng-uno-card ${drawn ? 'ng-drawn' : ''} ${selected ? 'ng-uno-selected' : ''}`} style={{ '--uno-color': unoColors[card.color] } as CSSProperties} onClick={onClick} aria-label={tx(unoTitle(card))}><small>{tx(card.color === 'wild' ? '万能牌' : UNO_LABEL[card.color])}</small><strong>{tx(typeof card.value === 'number' ? card.value : ({ skip: '⊘', reverse: '⇄', draw2: '+2', wild: '✦', wild4: '+4' }[card.value]))}</strong><b>{tx(typeof card.value === 'number' ? `${card.value} 点` : UNO_LABEL[card.value])}</b>{tx(drawn && <span>{t("刚抽到")}</span>)}</button>; }
function UnoTable(props: Props) {
 const {view,selfID,open,command}=props,b=view.board,play=view.actions.find(a=>a.id==='play'),challenge=b.privateChallenge?.challenger===selfID?b.privateChallenge:null;
 const [selectedID,setSelectedID]=useState<string|null>(null),[selectedColor,setSelectedColor]=useState<string|null>(null);
 const handIDs=(b.hand as UnoCard[]).map(c=>c.id).join('|');
 useEffect(()=>{setSelectedID(null);setSelectedColor(null);},[selfID,b.roundNumber,b.round,b.phase,b.current,b.drawn,b.top?.id,handIDs]);
 const actionFor=(c:UnoCard)=>c.color==='wild'?view.actions.find(a=>a.id===`wild:${c.id}`):play?.choices.some(choice=>choice.id===c.id)?play:undefined;
 const selectedCard=(b.hand as UnoCard[]).find(c=>c.id===selectedID),selectedAction=selectedCard? actionFor(selectedCard):undefined;
 const valid=!!selectedAction&&(selectedCard?.color!=='wild'||!!selectedAction.choices.find(c=>c.id===selectedColor));
 const choose=(id:string)=>{setSelectedID(old=>old===id?null:id);setSelectedColor(null);};
 const submit=()=>{if(!valid||!selectedCard||!selectedAction)return;command({action:selectedAction.id,values:[selectedCard.color==='wild'?selectedColor!:selectedCard.id]});setSelectedID(null);setSelectedColor(null);};
 const playerName=(id:string)=>b.players.find((p:any)=>p.id===id)?.name||id;
 return <div className="ng-table ng-uno"><Header view={view}/><Scoreboard view={view} selfID={selfID}/>
  <p className="ng-edition"><span>{t(`第 ${b.roundNumber} 轮`)}</span><span>{b.mode==='single'?t('单局竞速'):t('累计 500 分获胜')}</span><span>{t(b.challengeEnabled===false?'+4 质疑已关闭':'+4 质疑已开启')}</span></p>
  {challenge&&<section className="ng-panel ng-challenge" aria-label={t('质疑核验 · 仅你可见')}><h3>{t('质疑核验 · 仅你可见')}</h3><p className="ng-hint">{playerName(challenge.actor)} · {t('出 +4 时的手牌')} · {t('原颜色')} {t(UNO_LABEL[challenge.previousColor])}</p><strong className="ng-challenge-result">{t(challenge.wasLegal?'出牌合法，质疑失败':'持有原颜色，质疑成功')}</strong><p className="ng-hint">{t(challenge.wasLegal?'你已抽 6 张，确认后跳过。':'对方已抽 4 张，你继续正常回合。')}</p><div className="ng-hand">{(challenge.hand as UnoCard[]).map(c=><UnoFace key={c.id} card={c}/>)}</div><div className="ng-controls"><button className="ng-action" onClick={()=>command({action:'confirmChallenge',values:[]})}>{t('看完了，继续')}</button></div></section>}
  {(b.phase==='roundEnd'||view.finished)&&b.roundWinner&&<section className="ng-panel ng-round-result"><h3>{t('本轮结算')}</h3><strong>{playerName(b.roundWinner)} · +{b.roundPoints} {t('分')}</strong><p className="ng-hint">{t('上方分数已计入本轮所得。')}</p></section>}
  <section className="ng-uno-center ng-panel"><div><h3>{t('当前弃牌')}</h3><UnoFace card={b.top}/></div><div className="ng-uno-status"><span className="ng-color-badge" style={{background:unoColors[b.color]}}>{t(UNO_LABEL[b.color])}</span><strong>{t(b.direction===1?'顺时针 →':'← 逆时针')}</strong><small>{t('抽牌堆')} {b.deckCount} {t('张')}</small><Controls {...props} omit={['play','confirmChallenge','draw','pass']}/></div></section>
  <section className="ng-panel ng-uno-hand-panel"><h3>{t('你的手牌')}<small>{b.hand.length} {t(b.phase==='play'?'张 · 先选牌，再出牌':'张 · 请先完成当前提示')}</small></h3><div className="ng-hand ng-uno-hand">{(b.hand as UnoCard[]).map(c=><UnoFace card={c} key={c.id} drawn={b.drawn===c.id} selected={selectedID===c.id&&!!selectedAction} onClick={actionFor(c)?()=>choose(c.id):undefined}/>)}</div>
  {b.phase==='play'&&<div className="ng-uno-playbar"><div className="ng-uno-selection" aria-live="polite">{selectedCard&&selectedAction?<><strong>{t('选中手牌')} · {t(unoTitle(selectedCard))}</strong>{selectedCard.color==='wild'&&<div className="ng-uno-colors" role="group" aria-label={t('选择出牌颜色')}>{selectedAction.choices.map(c=><button key={c.id} type="button" aria-pressed={selectedColor===c.id} className={selectedColor===c.id?'selected':''} style={{'--uno-color':unoColors[c.id]} as CSSProperties} onClick={()=>setSelectedColor(c.id)}>{t(c.title)}</button>)}</div>}</>:<span>{t('点选一张亮起的牌')}</span>}</div><div className="ng-uno-play-actions"><button type="button" className="ng-action ng-uno-play" disabled={!valid} onClick={submit}>{t('出牌')}</button>{view.actions.filter(a=>['draw','pass'].includes(a.id)).map(a=><button type="button" className="ng-action ng-uno-secondary" key={a.id} onClick={()=>{setSelectedID(null);setSelectedColor(null);command({action:a.id,values:[]});}}>{t(a.title)}</button>)}</div></div>}
  </section>
  <details className="ng-rules"><summary>{t('本桌规则：报单、质疑与累计计分')}</summary><p>{t('每轮先出完手牌者获得其他玩家余牌的分数：数字牌按数字，功能牌 20 分，万能牌 50 分。默认累计到 500 分获胜，也可选择单局竞速。')}</p><p>{t('匹配当前颜色、数字或功能。主动抽牌后，只能打出刚抽到的牌，或保留并结束回合。+2 和 +4 不叠加。两人局的反转与跳过都让自己再出一手；牌堆用完后重洗弃牌。')}</p><p>{t('打出倒数第二张后，明确选择报单或不报。漏报时其他玩家可抓漏报，令你抽 2 张；也可全部选择放过。不用计时器，也不比网络速度。')}</p><p>{t(b.challengeEnabled===false?'质疑已关闭：只有没有当前颜色牌时才能出 +4，下家直接抽 4 张并跳过。':'+4 可以被质疑。出牌者当时若持有原颜色牌，质疑成功，出牌者抽 4 张；否则质疑者抽 6 张并跳过。只有质疑者能核验出牌时的手牌。接受 +4 则抽 4 张并跳过。')}</p></details>
 </div>;
}
function Cubes({ values }: {
    values: number[];
}) { return <div className="ng-cubes">{tx(values.map((n, i) => <span key={i} title={tx(SPICES[i])}><i>{tx(SPICE_SYMBOLS[i])}</i><b>{tx(n)}</b><small>{tx(SPICES[i])}</small></span>))}</div>; }
function CenturyTable(props: Props) {
    const { view, selfID, open } = props, b = view.board;
    const choice = (actionID: string, id: string) => { const a = view.actions.find(a => a.id === actionID); return a?.choices.some(c => c.id === id) ? () => actionID === "play" ? props.command({action: "play", values: [id]}) : open(a, [id]) : undefined; };
    return <div className="ng-table ng-century"><Header view={view}/><Scoreboard view={view} selfID={selfID}/><p className="ng-edition">{t("香料商旅 · 基础牌组") + " "}<span>{t("完成") + " "}{tx(b.goalTarget)}{" " + t("单触发最后一轮")}</span></p><section className="ng-panel"><h3>{t("公开订单") + " "}<small>{t("金币余") + " "}{tx(b.gold)}{" " + t("· 银币余") + " "}{tx(b.silver)}</small></h3><div className="ng-market">{tx((b.goals as SpiceOrder[]).map((o, i) => { const onClick = choice('claim', o.id); return <button type="button" className="ng-spice-card ng-goal" key={o.id} disabled={!onClick} onClick={onClick}><small>{tx(i === 0 && b.gold ? '🟡 金币 +3' : ((i === 1 && b.gold) || (i === 0 && !b.gold)) && b.silver ? '⚪ 银币 +1' : '订单')}</small><strong>{tx(o.points)}<small>{" " + t("分")}</small></strong><span>{tx(spiceText(o.cost))}</span>{tx(onClick && <b>{t("完成订单 →")}</b>)}</button>; }))}</div></section><section className="ng-panel"><h3>{t("商人市场") + " "}<small>{t("从左向右支付路费")}</small></h3><div className="ng-market">{tx(b.market.map((slot: {
            card: SpiceCard;
            bonus: number[];
        }, i: number) => { const onClick = choice('acquire', slot.card.id); return <button type="button" className="ng-spice-card" key={slot.card.id} disabled={!onClick} onClick={onClick}><small>{tx(i === 0 ? '免费招募' : `支付 ${i} 枚任选香料`)}</small><span className="ng-merchant-icon">{tx(slot.card.type === 'upgrade' ? '⇧' : slot.card.type === 'trade' ? '⇄' : '✦')}</span><b>{tx(spiceCardTitle(slot.card))}</b><small>{t("附赠：")}{tx(spiceText(slot.bonus))}</small></button>; }))}</div></section><section className="ng-panel"><h3>{t("你的商队") + " "}<small>{tx(b.cubes.reduce((n: number, v: number) => n + v, 0))}{" " + t("/ 10 枚")}</small></h3><Cubes values={b.cubes}/>{tx(b.active && <p className="ng-hint">{t("正在使用：")}{tx(spiceCardTitle(b.active))}{tx(b.phase === 'upgrade' ? ` · 还可升级 ${b.remaining} 次` : '')}</p>)}<Controls {...props} omit={['play', 'acquire', 'claim']}/><h3>{t("可用商人") + " "}<small>{tx(b.hand.length)}{" " + t("张")}</small></h3><div className="ng-market">{tx((b.hand as SpiceCard[]).map(c => { const onClick = choice('play', c.id); return <button type="button" className="ng-spice-card" key={c.id} disabled={!onClick} onClick={onClick}><span className="ng-merchant-icon">{tx(c.type === 'upgrade' ? '⇧' : c.type === 'trade' ? '⇄' : '✦')}</span><b>{tx(spiceCardTitle(c))}</b>{tx(onClick && <small>{t("使用这位商人 →")}</small>)}</button>; }))}</div><details className="ng-rules"><summary>{t("已用商人") + " "}{tx(b.played.length)}{" " + t("张 · 休整后收回")}</summary>{tx((b.played as SpiceCard[]).map(c => <p key={c.id}>{tx(spiceCardTitle(c))}</p>))}</details></section><section className="ng-plates">{tx(b.players.filter((p: any) => p.id !== selfID).map((p: any) => <article className="ng-panel" key={p.id}><h3>{tx(p.avatar)} {p.name}{" " + t("的商队")}</h3><Cubes values={p.cubes}/></article>))}</section><details className="ng-rules"><summary>{t("本桌规则与牌组说明")}</summary><p>{t("每回合使用一张商人、招募商人、完成一单或休整。升级可逐次选择同一枚或不同枚香料，也可提前停止；交易可以重复任意次，只要付得起。回合结束归还超过 10 枚的香料。招募时逐一支付给左侧商人，再获得该牌上的香料。")}</p><p>{t("两三人完成 6 单、四五人完成 5 单后完成当前整轮。订单、金币 3 分、银币 1 分和每枚非黄色香料 1 分相加；同分时座次靠后者胜。")}</p><p>{t("使用基础牌组：43 张市场商人、36 张订单，每人另有两张起始牌。商人效果、交换比例与订单分数均按原版数值逐张核对。")}</p></details></div>;
}
export function NewGamesTable(props: Props) { return props.view.kind === 'sushi' ? <SushiTable {...props}/> : props.view.kind === 'uno' ? <UnoTable {...props}/> : <CenturyTable {...props}/>; }
