import { useLayoutEffect, useState } from 'react';
import { Eye, EyeOff, KeyRound, MessageCircle, Shield, Skull, UserRound, Fingerprint, Check, FileKey } from 'lucide-react';
import type { Action, Command, GameView } from '../core/types';
import { t, useLocale } from '../i18n';
import './word-games-table.css';
import { IllustratedTile } from './IllustratedTile';
type Props={view:GameView;selfID:string;command:(c:Command)=>void;open:(a:Action,selected?:string[])=>void};
const teamText=(team:string)=>t(team==='red'?'红队':'蓝队');
const identityText=(identity:string)=>identity==='red'||identity==='blue'?teamText(identity):t(identity==='assassin'?'危险目标':'路人');
function SecretSignals({view,selfID,command,open}:Props){
 const b=view.board,[keyState,setKeyState]=useState({viewer:'',shown:false}),[clue,setClue]=useState(''),[count,setCount]=useState('1'),[error,setError]=useState('');
 useLayoutEffect(()=>setKeyState({viewer:selfID,shown:false}),[selfID]);
 const showKey=keyState.viewer===selfID&&keyState.shown,canClue=view.actions.some(a=>a.id==='clue'),guess=view.actions.find(a=>a.id==='guess'),stop=view.actions.find(a=>a.id==='stop');
 const send=()=>{try{command({action:'clue',values:[count],text:clue});setClue('');setError('');}catch(e){setError(t((e as Error).message));}};
 return <div className="wg-table wg-signals"><header className="wg-heading wg-illustrated-heading"><IllustratedTile kind="covers" index={3} className="wg-heading-art"/><div><small>{t('回合')} {b.round} · {t(b.startingTeam==='red'?'红方先手':'蓝方先手')}</small><h2>{view.finished?`${t('胜方')} · ${teamText(b.winnerTeam)}`:teamText(b.turn)}</h2></div><div className="wg-role-controls"><span className={`wg-role wg-${b.myTeam}`}>{teamText(b.myTeam)} · {t(b.isCaptain?'队长':'队员')}</span>{b.isCaptain&&!view.finished&&<button type="button" className="wg-button wg-key-toggle" aria-pressed={showKey} onClick={()=>setKeyState({viewer:selfID,shown:!showKey})}>{showKey?<EyeOff size={15}/>:<Eye size={15}/>} {t(showKey?'收起密钥':'查看密钥')}</button>}</div></header>
 <div className="wg-operation-layout"><aside className="wg-command-zone"><div className="wg-teams">{['red','blue'].map(team=><section key={team} className={`wg-team wg-${team} ${b.turn===team&&!view.finished?'wg-active':''}`}><header><strong>{teamText(team)}</strong><span>{t('剩余')} <b>{b.remaining[team]}</b></span></header><div>{b.players.filter((p:any)=>p.team===team).map((p:any)=><span className={`wg-member ${p.id===selfID?'wg-me':''}`} key={p.id}>{p.avatar} {p.name}{p.captain&&<KeyRound size={12} aria-label={t('队长')}/>}</span>)}</div></section>)}</div>
 {!canClue&&<section className="wg-clue-panel"><div><small>{t('当前线索')}</small><strong>{b.clue?b.clue.word:t(canClue?'给队友一个词和一个数字':'等待队长线索')}{b.clue&&<span>{b.clue.count==='unlimited'?'∞':b.clue.count}</span>}</strong></div>{b.phase==='guess'&&!view.finished&&<div className="wg-guess-status"><span>{t('还可猜')} <b>{b.limit===null?'∞':b.limit-b.guesses}</b></span>{stop?<button className="wg-button" onClick={()=>command({action:'stop',values:[]})}>{t('结束猜测')}</button>:guess&&<small>{t('至少猜一个词后才能结束')}</small>}</div>}</section>}
 {canClue&&<form className="wg-clue-form" onSubmit={e=>{e.preventDefault();send();}}><label>{t('线索词')}<input value={clue} onChange={e=>{setClue(e.target.value);setError('');}} maxLength={32} placeholder={t('例如：天空')} autoComplete="off" autoCapitalize="none"/></label><label>{t('线索数量')}<select value={count} onChange={e=>setCount(e.target.value)}>{Array.from({length:10},(_,i)=><option key={i} value={i}>{i}</option>)}<option value="unlimited">∞ {t('不限')}</option></select></label><button className="wg-button wg-primary" disabled={!clue.trim()} type="submit">{t('发送线索')}</button>{error&&<p className="wg-error" role="alert">{error}</p>}</form>}
 <div className="wg-extra-actions">{view.actions.filter(a=>['invalid_clue','penalty_cover','skip_penalty'].includes(a.id)).map(a=><button type="button" className="wg-button" key={a.id} onClick={()=>open(a)}>{t(a.title)}</button>)}</div>
 </aside><section className="wg-board-zone"><div className="wg-grid-heading"><h3>{t('公开牌桌')}</h3></div>
 {b.isCaptain&&!view.finished&&<p className="wg-note">{t('密钥仅队长可见')}</p>}{guess&&<p className="wg-note">{t('同队讨论后，由一位队员点选并确认')}</p>}
 <div className="wg-word-grid">{b.cards.map((card:any)=>{const identity=card.revealed||showKey||view.finished?card.identity:null,enabled=guess?.choices.some(c=>c.id===card.id);return <button type="button" key={card.id} className={`wg-word ${identity?'wg-'+identity:'wg-unknown'} ${card.revealed?'wg-revealed':''}`} disabled={!enabled} onClick={()=>guess&&open(guess,[card.id])} aria-label={`${card.word} · ${identity?identityText(identity):t('未揭晓')}`}><span className="wg-card-emblem" aria-hidden="true">{identity==='assassin'?<Skull/>:identity==='red'||identity==='blue'?<Shield/>:identity==='neutral'?<UserRound/>:<Fingerprint/>}</span><span className="wg-cell-index">{Number(card.id.split('-')[1])+1}</span><strong>{card.word}</strong><small>{identity?identityText(identity):t('未揭晓')}{identity==='assassin'&&<Skull size={12}/>}</small>{card.revealed&&<span className="wg-revealed-mark" aria-hidden="true"><Check size={12}/></span>}</button>;})}</div>
 </section></div><details className="wg-rules"><summary>{t('查看本桌规则')}</summary><p>{t('两队交替行动，队长只能用一个词和一个数字给线索。先手找出 9 个词，后手找出 8 个词。队长不可参与点选。')}</p><p>{t('猜中己方词可以继续，最多猜线索数量加一次；猜到路人或对方词立即结束回合。猜中危险目标立即失败。先找齐己方词的一队获胜，也可能在对方回合获胜。')}</p><p>{t('0 和不限线索均不限制猜测次数，但仍须至少猜一次。线索不可是未揭晓的牌面词或其变形，也不可暗示位置、拼写或发音；含义是否合法由在场玩家共同判断。')}</p><p>{t('队长密钥属于私密信息。同屏试玩时，切换座位前请先收起密钥。')}</p><p>{t('词库语言')}：{t(b.language==='en'?'英文':'中文')}</p></details></div>;
}
function OddWordOut({view,selfID,command,open}:Props){const b=view.board,[peekState,setPeekState]=useState({viewer:'',shown:false}),peek=peekState.viewer===selfID&&peekState.shown;const byID=(id:string)=>b.players.find((p:any)=>p.id===id);const phase=t(view.finished?'本局结束':b.phase==='deal'?'秘密发词':b.phase==='vote'?'秘密投票':b.phase==='defend'?'平票辩护':'轮流描述');const ready=view.actions.find(a=>a.id==='ready'),vote=view.actions.find(a=>a.id==='vote'),described=view.actions.find(a=>a.id==='described'),cancel=view.actions.find(a=>a.id==='cancel_vote');
 useLayoutEffect(()=>setPeekState({viewer:selfID,shown:false}),[selfID]);
 return <div className="wg-table wg-odd"><header className="wg-heading"><div><small>{t('回合')} {b.round||1}</small><h2>{phase}</h2></div><span className="wg-role"><UserRound size={14}/>{b.players.filter((p:any)=>p.alive).length} / {b.players.length}</span></header>
 <section className={`wg-secret-panel ${b.phase!=='deal'&&!peek?'wg-secret-compact':''}`}><small>{t('你的秘密词')}</small><button type="button" className={`wg-secret ${peek?'wg-open':''}`} onClick={()=>setPeekState({viewer:selfID,shown:!peek})} aria-label={t(peek?'收起我的词':'查看我的词')} aria-pressed={peek}><IllustratedTile kind="covers" index={4} className="wg-secret-art"/>{peek?<><strong>{b.word}</strong><span><EyeOff size={16}/> {t('收起我的词')}</span></>:<><FileKey size={28} className="wg-secret-seal"/><strong>{t('查看我的词')}</strong><span>{t('只展示给自己，别念出这个词')}</span></>}</button>{ready?<button className="wg-button wg-primary" disabled={!peek} onClick={()=>{command({action:'ready',values:[]});setPeekState({viewer:selfID,shown:false});}}>{t('记住了，准备描述')}</button>:<p className="wg-note">{t('记住词后请收起，避免他人看到')}</p>}</section>
 {!view.finished&&<section className="wg-speaking"><MessageCircle size={23}/><div><strong>{b.phase==='deal'?t('正在等待其他玩家准备'):b.phase==='vote'?t(b.ownVote?'你的投票已锁定':'秘密投票'):`${byID(b.current)?.avatar||''} ${byID(b.current)?.name||''}`}</strong><p>{b.phase==='vote'?t('讨论后选择最可疑的人，不能投自己'):b.phase==='deal'?t('看词后再准备'):t('线下或语音通话中描述，完成后点击按钮')}</p></div>{described&&<button className="wg-button wg-primary" onClick={()=>command({action:'described',values:[]})}>{t(b.phase==='defend'?'辩护结束':'描述结束')}</button>}{cancel&&<button className="wg-button" onClick={()=>command({action:'cancel_vote',values:[]})}>{t('修改我的投票')}</button>}</section>}
 {!b.alive&&!view.finished&&<p className="wg-note">{t('淘汰后可以旁观，本局仍可随阵营获胜')}</p>}
 {b.runoff&&!view.finished&&<p className="wg-note">{t('复投候选')}：{b.tied.map((id:string)=>byID(id)?.name).join(' · ')}</p>}
 <div className="wg-odd-players">{b.players.map((p:any)=>{const enabled=vote?.choices.some(c=>c.id===p.id);return <button type="button" className={`wg-odd-player ${p.id===b.current&&!view.finished?'wg-speaking-now':''} ${!p.alive?'wg-out':''} ${b.ownVote===p.id?'wg-voted-for':''}`} key={p.id} disabled={!enabled} onClick={()=>vote&&open(vote,[p.id])}><span className="wg-player-avatar">{p.avatar}<span className="wg-player-seal" aria-hidden="true">{p.id===b.current&&!view.finished?<MessageCircle size={12}/>:<Fingerprint size={12}/>}</span></span><strong>{p.name}{p.id===selfID?` · ${t('你')}`:''}</strong><small>{view.finished||!p.alive?t(p.role==='odd'?'异词阵营':'多数词阵营'):b.phase==='deal'?t(p.ready?'已准备':'等待看词'):b.phase==='vote'?t(p.voted?'已投票':'等待投票'):p.id===b.current?t('当前发言'):t('仍在局中')}</small>{view.finished?<span className="wg-final-word">{p.word}</span>:!p.alive&&<span>{t('已淘汰')}</span>}{enabled&&<span className="wg-vote-label">{t('确认投票')} →</span>}</button>;})}</div>
 {Object.keys(b.lastVotes).length>0&&<details className="wg-rules"><summary>{t('上一轮投票')}</summary>{Object.entries(b.lastVotes).map(([id,target])=><p key={id}>{byID(id)?.name} → {byID(target as string)?.name}</p>)}</details>}
 <details className="wg-rules"><summary>{t('查看本桌规则')}</summary><p>{t('每人收到一个秘密词。多数人拿到相同词，少数人拿到相近的另一词；你只知道自己的词，不知道阵营。请用一句话轮流描述，不直接说出词本身。')}</p><p>{t('描述后秘密投票，所有存活玩家投完再同时公布。最高票者淘汰并公开阵营。平票者依次辩护后，仅对平票候选复投；再次平票则本轮无人淘汰。')}</p><p>{t('多数词阵营淘汰全部异词玩家即获胜；异词玩家人数达到或超过多数词玩家时获胜。3–6 人有 1 位异词玩家，7–10 人有 2 位，11–12 人有 3 位。本桌不含白板角色。')}</p><p>{t('规则存在不同地区版本，本桌固定使用上述平票与阵营胜负规则。')}</p><p>{t('词库语言')}：{t(b.language==='en'?'英文':'中文')}</p></details></div>;
}
export function WordGamesTable(props:Props){useLocale();return props.view.kind==='codenames'?<SecretSignals {...props}/>:<OddWordOut {...props}/>;}
