import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {createMatch,advanceMatchClock} from '../../src/core/room';
import {drawrelay,encodeRelayStroke} from '../../src/core/games/drawrelay';
vi.mock('cloudflare:workers',()=>({DurableObject:class {}}));
const {GameRoom}=await import('../../worker/'+'index');
class Socket{messages:any[]=[];constructor(public attachment:any){}deserializeAttachment(){return this.attachment;}serializeAttachment(a:any){this.attachment=a;}send(raw:string){this.messages.push(JSON.parse(raw));}close(){}get latest(){return this.messages.at(-1);}}
let server:any,sockets:Socket[],alarm:number;
function setup(mode='cloud',count=3){const players=Array.from({length:count},(_,i)=>({id:`player_${i}`,name:`Player ${i}`,avatar:'🦊',ready:true,connected:true}));sockets=players.map(p=>new Socket({id:p.id,authenticated:true,opened:Date.now()}));server=Object.create(GameRoom.prototype);server.data={info:{kind:'drawrelay',code:'RLY123',mode,hostID:players[0].id,players,pending:[],spectators:[],started:true,revision:1,matchID:'relay-test',options:{relaySeconds:60}},tokens:Object.fromEntries(players.map(p=>[p.id,'x'.repeat(48)])),pendingTokens:{},invite:'inv',expires:Date.now()+3600000,controlSeen:{},match:advanceMatchClock(createMatch('drawrelay',players,{relaySeconds:60}),'drawrelay',players,Date.now())};server.ctx={getWebSockets:()=>sockets,storage:{put:vi.fn(async()=>{}),setAlarm:vi.fn(async(at:number)=>{alarm=at;}),deleteAll:vi.fn(async()=>{})}};server.env={DIRECTORY:{getByName:()=>({fetch:async()=>new Response('{}')})}};}
async function message(seat:number,body:any){await server.webSocketMessage(sockets[seat],JSON.stringify({requestID:crypto.randomUUID(),...body}));}
async function act(seat:number,command:any){await message(seat,{type:'action',command,actionRevision:server.data.match.actorRevisions[`player_${seat}`]});expect(sockets[seat].latest.type).not.toBe('error');}
beforeEach(()=>{vi.useFakeTimers();setup();});afterEach(()=>vi.useRealTimers());
describe('drawing relay authoritative lifecycle',()=>{
 it('arms the next step immediately when the last player submits',async()=>{for(let i=0;i<3;i++){await act(i,{action:'draft',values:['0'],text:`private${i}`});await act(i,{action:'submit',values:['0']});}expect(server.data.match.game.step).toBe(1);expect(server.data.match.game.deadlineAt).toBe(Date.now()+60000);expect(alarm).toBe(server.data.match.game.deadlineAt);});
 it('expires before accepting an input arriving behind a delayed alarm',async()=>{const revision=server.data.match.actorRevisions.player_0;vi.setSystemTime(Date.now()+60001);await message(0,{type:'action',actionRevision:revision,command:{action:'draft',values:['0'],text:'late'}});expect(sockets[0].latest.type).toBe('error');expect(server.data.match.game.step).toBe(1);expect(server.data.match.game.books[0][0]).toMatchObject({skipped:true});expect(JSON.stringify(server.data.match.game)).not.toContain('late');expect(sockets[0].messages.some(m=>m.type==='snapshot'&&m.view.board.step===1)).toBe(true);});
 it('freezes on disconnect and schedules no past game alarm',async()=>{vi.setSystemTime(Date.now()+20000);await server.webSocketClose(sockets[2]);expect(server.data.match.game.pausedRemaining).toBe(40000);expect(server.data.match.game.deadlineAt).toBe(0);expect(alarm).toBeGreaterThan(Date.now());vi.setSystemTime(Date.now()+90000);await server.alarm();expect(server.data.match.game.step).toBe(0);expect(server.data.match.game.pausedRemaining).toBe(40000);});
 it('accepts a valid large album handoff only from its authenticated LAN owner',async()=>{setup('lan',12);let state=server.data.match.game;const stroke=encodeRelayStroke(Array.from({length:48},(_,i)=>[i*21,i*16]),3,2);for(let step=0;step<4;step++){state.drafts.forEach((draft:any,i:number)=>{if(step%2)draft.strokes=Array(96).fill(stroke);else draft.text=`sentence${i}`;state.submitted[i]=i<11;});state=drawrelay.apply(state,'player_11',{action:'submit',values:[String(step)]});}server.data.match.game=state;const match=structuredClone(server.data.match);delete server.data.match;expect(JSON.stringify(match).length).toBeGreaterThan(150000);await message(1,{type:'switchToCloud',match});expect(sockets[1].latest.error).toBe('消息过大');expect(server.data.info.mode).toBe('lan');await message(0,{type:'switchToCloud',match});expect(sockets[0].latest.type).toBe('snapshot');expect(server.data.info.mode).toBe('cloud');expect(server.data.match.game.books).toEqual(state.books);expect(server.data.match.game.deadlineAt).toBeGreaterThan(Date.now());});
 it('rejects forged and oversized relay checkpoints without a partial mode switch',async()=>{setup('lan');const match=structuredClone(server.data.match);match.game.books[0].push({author:'player_0',kind:'text',text:'leak'});await message(0,{type:'switchToCloud',match});expect(sockets[0].latest.type).toBe('error');expect(server.data.info.mode).toBe('lan');await server.webSocketMessage(sockets[0],JSON.stringify({type:'action',padding:'x'.repeat(160000)}));expect(sockets[0].latest.error).toBe('消息过大');});
 it('keeps queued albums available with another player offline and preserves drafts across reconnect',async()=>{
  server.data.info.options={relayMode:'queue'};server.data.match=createMatch('drawrelay',server.data.info.players,{relayMode:'queue'});
  await server.webSocketClose(sockets[2]);await act(0,{action:'draft',values:['0:0'],text:'independent'});await act(0,{action:'submit',values:['0:0']});
  expect(sockets[1].latest.type).toBe('snapshot');expect(sockets[1].latest.paused).toBe(false);
  expect(sockets[1].latest.view.board.tasks.map((t:any)=>t.id)).toContain('0:1');await act(1,{action:'stroke',values:['0:1',encodeRelayStroke([[0,0],[10,10]],0,1)]});
  expect(server.data.match.game.queue.drafts[0].strokes).toHaveLength(1);expect(server.data.match.game.deadlineAt).toBe(0);
  await act(1,{action:'submit',values:['0:1']});expect(server.data.match.game.books[0]).toHaveLength(2);
  expect(JSON.stringify(sockets[0].latest.view)).not.toContain('independent');
 });
});
