import {describe,it,expect} from 'vitest';
import {createMatch,normalizeGameOptions,optionsKey,roomLimits,validateMatchForRoom,type RoomInfo} from '../../src/core/room';
const players=Array.from({length:7},(_,i)=>({id:'player00'+i,name:'玩家'+i,avatar:'🦊',ready:true,connected:true}));
const room=(mode:'standard'|'judge'|'deal'='standard'):RoomInfo=>({code:'ABC234',kind:'werewolf',mode:'lan',hostID:players[0].id,players,pending:[],started:true,revision:1,options:normalizeGameOptions('werewolf',{werewolfMode:mode},players[0].id)});
describe('room game options',()=>{
 it('defaults old werewolf rooms to standard and leaves other games unchanged',()=>{expect(normalizeGameOptions('werewolf',undefined,players[0].id)).toEqual({werewolfMode:'standard'});expect(normalizeGameOptions('gems',undefined,players[0].id)).toBeUndefined();expect(optionsKey('werewolf',undefined,players[0].id)).toBe(optionsKey('werewolf',{werewolfMode:'standard'},players[0].id));});
 it('assigns judge and dealer authorization to the host',()=>{for(const werewolfMode of ['judge','deal'] as const)expect(normalizeGameOptions('werewolf',{werewolfMode},players[0].id)).toEqual({werewolfMode,moderatorID:players[0].id});});
 it.each([null,[],{werewolfMode:'evil'},{werewolfMode:'judge',moderatorID:'player001'},{werewolfMode:'deal',moderatorID:'player001'},{werewolfMode:'standard',moderatorID:'player000'},{extra:'option'}])('rejects invalid/forged options %j',options=>{expect(()=>normalizeGameOptions('werewolf',options,players[0].id)).toThrow();});
 it('does not permit werewolf-only options on other games',()=>{expect(()=>normalizeGameOptions('gems',{werewolfMode:'judge'},players[0].id)).toThrow();});
 it('adds one nonplaying judge seat, without changing standard/deal limits',()=>{expect(roomLimits('werewolf',{werewolfMode:'judge'})).toEqual({min:7,max:19});expect(roomLimits('werewolf',{werewolfMode:'deal'})).toEqual({min:6,max:18});expect(roomLimits('werewolf')).toEqual({min:6,max:18});expect(roomLimits('gems')).toEqual({min:2,max:4});});
 it('accepts a compatible legacy standard match and rejects metadata/roster tampering',()=>{const r=room();const match=createMatch(r.kind,r.players);delete match.options;delete match.schemaVersion;expect(validateMatchForRoom(match,r).game).toEqual(match.game);expect(()=>validateMatchForRoom({...match,options:{werewolfMode:'judge',moderatorID:r.hostID}},r)).toThrow();const invalid=structuredClone(match);invalid.game.players[0].id='intruder';expect(()=>validateMatchForRoom(invalid,r)).toThrow('玩家');expect(()=>validateMatchForRoom({...match,schemaVersion:99},r)).toThrow('版本');});
 it('rejects handoff which changes only the engine moderator/mode despite correct envelope',()=>{const r=room(),match=createMatch(r.kind,r.players);match.game.options={werewolfMode:'judge',moderatorID:players[1].id};expect(()=>validateMatchForRoom(match,r)).toThrow();});
});

describe('hosted mode state transfer boundary',()=>{
 it.each(['judge','deal'] as const)('retains %s authorization through JSON checkpoint and rejects forged mode or moderator',mode=>{const r=room(mode);const match=createMatch(r.kind,r.players,r.options);expect(validateMatchForRoom(JSON.parse(JSON.stringify(match)),r).options).toEqual(r.options);const changed=structuredClone(match);changed.game.options.moderatorID=players[1].id;expect(()=>validateMatchForRoom(changed,r)).toThrow();const wrongMode=structuredClone(match);wrongMode.game.options.werewolfMode=mode==='judge'?'deal':'judge';expect(()=>validateMatchForRoom(wrongMode,r)).toThrow();});
 it('rejects a judge pretending to be a dealt participant',()=>{const r=room('judge');const match=createMatch(r.kind,r.players,r.options);match.game.participants.unshift(players[0]);match.game.roles[players[0].id]='wolf';expect(()=>validateMatchForRoom(match,r)).toThrow('参与发牌');});
});
