import {describe,it,expect} from 'vitest';
import {applyMatch,createMatch,validProfile,viewMatch} from '../../src/core/room';
import {modules} from '../../src/core/registry';
import type {Player} from '../../src/core/types';
const players:Player[]=Array.from({length:5},(_,i)=>({id:'player00'+i,name:'玩家'+i,avatar:'🦊'}));
describe('authoritative match boundary',()=>{
 it('rejects identities that collide with object-backed room credentials',()=>{for(const id of ['__proto__','constructor','toString','hasOwnProperty'])expect(()=>validProfile({...players[0],id})).toThrow('身份无效');});
 it('rejects malformed identity and avatar',()=>{expect(()=>validProfile({...players[0],name:' '.repeat(4)})).toThrow();expect(()=>validProfile({...players[0],avatar:'<script>'})).toThrow();expect(()=>validProfile({...players[0],id:'x'})).toThrow();});
 it('deduplicates retry before checking stale revision and never mutates prior state',()=>{const match=createMatch('gems',players.slice(0,2));const snapshot=JSON.stringify(match);const actor=players.find(p=>viewMatch(match,'gems',p.id).view.actions.length)!;const action=viewMatch(match,'gems',actor.id).view.actions[0];const command={action:action.id,values:action.choices.slice(0,action.min).map(c=>c.id)};const next=applyMatch(match,'gems',players.slice(0,2),actor.id,command,'request1',1);expect(JSON.stringify(match)).toBe(snapshot);expect(next.revision).toBe(2);expect(applyMatch(next,'gems',players.slice(0,2),actor.id,command,'request1',1)).toBe(next);expect(()=>applyMatch(next,'gems',players.slice(0,2),actor.id,command,'request2',1)).toThrow('变化');});
 it('keeps independent simultaneous votes usable after another player votes',()=>{let match=createMatch('avalon',players);for(let step=0;step<10;step++){const candidate=players.map(p=>({p,v:viewMatch(match,'avalon',p.id)})).find(x=>x.v.view.actions.some(a=>a.id==='propose'));if(!candidate)break;const a=candidate.v.view.actions[0];match=applyMatch(match,'avalon',players,candidate.p.id,{action:a.id,values:a.choices.slice(0,a.min).map(c=>c.id)},'team'+step,candidate.v.actionRevision);if(players.every(p=>viewMatch(match,'avalon',p.id).view.actions.some(a=>/vote|approve/i.test(a.id))))break;}
 const simultaneous=players.filter(p=>viewMatch(match,'avalon',p.id).view.actions.length>0);if(simultaneous.length<2)throw new Error('Test must reach simultaneous Avalon vote');const before=simultaneous.map(p=>({p,v:viewMatch(match,'avalon',p.id)}));const {p,v}=before[0],a=v.view.actions[0];const next=applyMatch(match,'avalon',players,p.id,{action:a.id,values:a.choices.slice(0,a.min).map(c=>c.id)},'voter1',v.actionRevision);for(const x of before.slice(1)){const oldActions=JSON.stringify(x.v.view.actions),newActions=JSON.stringify(modules.avalon.view(next.game,x.p.id).actions);if(oldActions===newActions)expect(next.actorRevisions[x.p.id]).toBe(x.v.actionRevision);}
 });
});
