import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
vi.mock('cloudflare:workers',()=>({DurableObject:class {}}));
// Keep the Workers runtime out of the DOM-only application typecheck.
const {GameRoom}=await import('../../worker/'+'index');
const host={id:'host0000',name:'房主',avatar:'🦊',ready:true,connected:true};
const guest={id:'guest000',name:'朋友',avatar:'🐻',ready:true,connected:true};
class ServerSocket {messages:any[]=[];closed?:number;constructor(public attachment:any={opened:Date.now()}){}deserializeAttachment(){return this.attachment;}serializeAttachment(a:any){this.attachment=a;}send(raw:string){this.messages.push(JSON.parse(raw));}close(code:number){this.closed=code;}get snapshot(){return this.messages.filter(m=>m.type==='snapshot').at(-1);}}
let server:any,sockets:ServerSocket[],alarm:number|undefined;
const member=(id:string,pending=false)=>new ServerSocket({id,authenticated:true,pending,opened:Date.now(),lastSeen:Date.now()});
const message=(ws:ServerSocket,msg:any)=>server.webSocketMessage(ws,JSON.stringify({requestID:crypto.randomUUID(),...msg}));
beforeEach(()=>{vi.useFakeTimers();sockets=[member(host.id),member(guest.id)];server=Object.create(GameRoom.prototype);server.data={info:{code:'ABC234',kind:'gems',mode:'cloud',hostID:host.id,players:[host,guest],pending:[],started:false,revision:1},tokens:{[host.id]:'a'.repeat(48),[guest.id]:'b'.repeat(48)},pendingTokens:{},invite:'invite',expires:Date.now()+3600000,controlSeen:{}};server.ctx={getWebSockets:()=>sockets,storage:{async put(){},async setAlarm(at:number){alarm=at;},async deleteAll(){}}};server.env={DIRECTORY:{getByName:()=>({fetch:async()=>new Response('{}')})}};});
afterEach(()=>{vi.useRealTimers();});
describe('authoritative reconnect and presence',()=>{
 it('does not let a rejected socket close erase a new application from the same player',async()=>{const profile={id:'pending0',name:'申请人',avatar:'🦊'},token='c'.repeat(48);const first=new ServerSocket();sockets.push(first);await message(first,{type:'hello',profile,token});await message(sockets[0],{type:'approve',playerID:profile.id,accept:false});const retry=new ServerSocket();sockets.push(retry);await message(retry,{type:'hello',profile,token});await server.webSocketClose(first);expect(server.data.info.pending).toEqual([profile]);expect(server.data.pendingTokens[profile.id]).toBe(token);await message(sockets[0],{type:'approve',playerID:profile.id,accept:true});expect(retry.snapshot.room.players.some((p:any)=>p.id===profile.id)).toBe(true);});
 it('keeps private state and host controls unavailable to applicants and guests',async()=>{const applicant=new ServerSocket();sockets.push(applicant);await message(applicant,{type:'hello',profile:{id:'pending0',name:'申请人',avatar:'🦊'},token:'c'.repeat(48)});await message(applicant,{type:'ready',ready:true});expect(applicant.messages.at(-1).error).toContain('等待房主');expect(applicant.messages.some(m=>m.room||m.view||m.invite)).toBe(false);for(const type of ['start','endGame','selectGame','removePlayer','approve']){const revision=server.data.info.revision;await message(sockets[1],{type,kind:'uno',playerID:host.id,accept:true});expect(sockets[1].messages.at(-1).type).toBe('error');expect(server.data.info.revision).toBe(revision);}expect(sockets[1].snapshot?.invite).toBeUndefined();});
 it('reports only room existence on an unauthenticated status probe',async()=>{const response=await server.fetch(new Request('https://internal/status'));expect(response.status).toBe(200);expect(await response.json()).toEqual({ok:true});server.data.ended=true;expect((await server.fetch(new Request('https://internal/status'))).status).toBe(404);});
 it('allows a disconnected host to rejoin a running match with the same identity and preserves the round',async()=>{await message(sockets[0],{type:'start'});const match=structuredClone(server.data.match),matchID=server.data.info.matchID;await server.webSocketClose(sockets[0]);expect(sockets[1].snapshot.paused).toBe(true);const restored=new ServerSocket();sockets.push(restored);await message(restored,{type:'hello',profile:host,token:'a'.repeat(48)});expect(restored.snapshot.paused).toBe(false);expect(restored.snapshot.room.matchID).toBe(matchID);expect(server.data.match).toEqual(match);expect(restored.snapshot.room.players).toHaveLength(2);expect(restored.snapshot.room.expiresAt).toBe(server.data.expires);});
 it('replaces a duplicate socket without creating duplicate seats or letting its later close mark the new one offline',async()=>{const original=sockets[1],replacement=new ServerSocket();sockets.push(replacement);await message(replacement,{type:'hello',profile:guest,token:'b'.repeat(48)});expect(original.closed).toBe(4001);expect(original.attachment.authenticated).toBeUndefined();await server.webSocketClose(original);expect(sockets[0].snapshot.room.players.find((p:any)=>p.id===guest.id).connected).toBe(true);expect(server.data.info.players).toHaveLength(2);});
 it('rejects identity takeover with the wrong token',async()=>{const attacker=new ServerSocket();sockets.push(attacker);await message(attacker,{type:'hello',profile:host,token:'c'.repeat(48)});expect(attacker.messages.at(-1).error).toContain('身份不匹配');expect(attacker.attachment.authenticated).toBeUndefined();expect(sockets[0].closed).toBeUndefined();});
 it('sweeps silent authenticated sockets, pauses the game, and keeps their seats recoverable',async()=>{await message(sockets[0],{type:'start'});await vi.advanceTimersByTimeAsync(70000);await message(sockets[0],{type:'ping'});await server.alarm();expect(sockets[1].closed).toBe(4000);expect(sockets[0].snapshot.paused).toBe(true);expect(server.data.tokens[guest.id]).toBe('b'.repeat(48));expect(alarm).toBeLessThan(server.data.expires);});
 it('accepts heartbeat from an applicant waiting for approval',async()=>{const pending=member('pending0',true);sockets.push(pending);await message(pending,{type:'ping'});expect(pending.messages.at(-1)).toEqual({type:'pong'});});
 it('clears abandoned approval requests so the queue cannot fill with offline applicants',async()=>{const pending=member('pending0',true);sockets.push(pending);server.data.info.pending=[{id:'pending0',name:'申请人',avatar:'🦊'}];server.data.pendingTokens.pending0='c'.repeat(48);await server.webSocketClose(pending);expect(server.data.info.pending).toHaveLength(0);expect(server.data.pendingTokens.pending0).toBeUndefined();});
 it('allows only the lobby host to remove an offline seat',async()=>{await message(sockets[0],{type:'removePlayer',playerID:guest.id});expect(sockets[0].messages.at(-1).error).toContain('只能移除离线');await server.webSocketClose(sockets[1]);await message(sockets[0],{type:'removePlayer',playerID:guest.id});expect(server.data.info.players.map((p:any)=>p.id)).toEqual([host.id]);expect(server.data.tokens[guest.id]).toBeUndefined();});
 it('never removes a player midgame and gives each new round a distinct persistent match ID',async()=>{await message(sockets[0],{type:'start'});const firstID=server.data.info.matchID;expect(firstID).toBeTruthy();await server.webSocketClose(sockets[1]);await message(sockets[0],{type:'removePlayer',playerID:guest.id});expect(sockets[0].messages.at(-1).error).toContain('准备室');expect(server.data.info.players).toHaveLength(2);await message(sockets[0],{type:'endGame'});expect(server.data.info.matchID).toBeUndefined();sockets[1].attachment={id:guest.id,authenticated:true,opened:Date.now()};await message(sockets[1],{type:'ready',ready:true});await message(sockets[0],{type:'start'});expect(server.data.info.matchID).toBeTruthy();expect(server.data.info.matchID).not.toBe(firstID);});
});

describe('authoritative spectator seats',()=>{
 const observer={id:'observer0',name:'Observer',avatar:'🐼'},hello={type:'hello',profile:observer,token:'c'.repeat(48),invite:'invite',spectator:true};
 it('defaults old stored rooms to allowing observers, without using a player seat',async()=>{const ws=new ServerSocket();sockets.push(ws);await message(ws,hello);expect(ws.snapshot.room.allowSpectators).toBe(true);expect(ws.snapshot.room.spectators).toHaveLength(1);expect(ws.snapshot.room.players).toHaveLength(2);await message(ws,{type:'ready',ready:true});expect(ws.messages.at(-1).error).toBe('观众不能操作牌局');});
 it('rejects full spectator capacity atomically and does not let an observer take a full player seat',async()=>{server.data.info.spectators=Array.from({length:20},(_,i)=>({...observer,id:`observer${i+1}`,connected:false}));const ws=new ServerSocket();sockets.push(ws);const before=structuredClone(server.data);await message(ws,hello);expect(ws.messages.at(-1).error).toBe('观战席已满');expect(server.data).toEqual(before);server.data.info.spectators=[];await message(ws,hello);server.data.info.players.push({...guest,id:'player02'},{...guest,id:'player03'});const roster=structuredClone(server.data.info);await message(ws,{type:'setSeat',spectator:false});expect(ws.messages.at(-1).error).toBe('房间已满');expect(server.data.info).toEqual(roster);});
 it('revokes tokens and pending observer requests on disable, with no effect on active players',async()=>{const ws=new ServerSocket(),pending=new ServerSocket();sockets.push(ws,pending);await message(ws,hello);await message(pending,{...hello,profile:{...observer,id:'pending0'},invite:undefined});await message(sockets[1],{type:'setSpectators',allowed:false});expect(sockets[1].messages.at(-1).error).toBe('只有房主能设置观战');await message(sockets[0],{type:'setSpectators',allowed:false});expect(server.data.info.spectators).toEqual([]);expect(server.data.info.pending).toEqual([]);expect(server.data.tokens[observer.id]).toBeUndefined();expect(server.data.pendingTokens.pending0).toBeUndefined();expect(ws.closed).toBe(4003);expect(pending.closed).toBe(4003);expect(server.data.info.players).toHaveLength(2);});
 it('converts pre-start join requests to observers and makes midgame admission depend on the spectator switch',async()=>{const ws=new ServerSocket();sockets.push(ws);await message(ws,{...hello,invite:undefined,spectator:false});expect(server.data.info.pending[0].spectator).toBeUndefined();await message(sockets[0],{type:'start'});expect(server.data.info.pending[0].spectator).toBe(true);await message(sockets[0],{type:'approve',playerID:observer.id,accept:true});expect(ws.snapshot.view.spectating).toBe(true);expect(server.data.match.game.players).toHaveLength(2);await message(ws,{type:'setSeat',spectator:false});expect(ws.messages.at(-1).error).toBe('牌局已开始');});
 it('ignores observer disconnects for pause, preserves identity, and permits midgame leave',async()=>{const ws=new ServerSocket();sockets.push(ws);await message(ws,hello);await message(sockets[0],{type:'start'});const match=structuredClone(server.data.match);await server.webSocketClose(ws);expect(sockets[0].snapshot.paused).toBe(false);const resumed=new ServerSocket();sockets.push(resumed);await message(resumed,{...hello,spectator:false});expect(resumed.snapshot.view.spectating).toBe(true);expect(server.data.match).toEqual(match);await message(resumed,{type:'leave'});expect(server.data.tokens[observer.id]).toBeUndefined();expect(server.data.info.spectators).toEqual([]);expect(sockets[0].snapshot.paused).toBe(false);});
});
