import type { GameKind, GameModule } from './types';
import { gems } from './games/gems';
import { bombs } from './games/bombs';
import { werewolf } from './games/werewolf';
import { avalon } from './games/avalon';
import { sushi } from './games/sushi';
import { century } from './games/century';
import { uno } from './games/uno';
import { codenames } from './games/codenames';
import { undercover } from './games/undercover';
export const modules:Record<GameKind,GameModule>={gems,bombs,werewolf,avalon,sushi,century,uno,codenames,undercover};
